addon-name: "FunFact"
addon-description: "displays random fun facts"
urls:
  curseforge: "https://www.curseforge.com/wow/addons/funfact"
  wago: "https://addons.wago.io/addons/J96EYg6g"
  discord: "https://discord.gg/Qc9TRBv"
