local FunFact = FunFact
local module = FunFact:NewModule('FactList_Cats')
module.desciption = 'Meow?'

module.Facts = {
	"Cats can't taste sweetness.",
	'Owning a cat can reduce the risk of stroke and heart attack by a third.',
	'Wikipedia has a recording of a cat meowing because why not?',
	"The world's largest cat measured 48.5 inches long.",
	"Evidence suggests domesticated cats have been around since 3600 B.C., 2,000 years before Egypt's pharaohs.",
	"A cat's purr may be a form of self-healing, as it can be a sign of nervousness as well as contentment.",
	"Similarly, the frequency of a domestic cat's purr is the same at which muscles and bones repair themselves.",
	'Adult cats only meow to communicate with humans.',
	"The world's richest cat is worth $13 million after his human passed away and left her fortune to him.",
	'Your cat recognizes your voice but just acts too cool to care (probably because they are).',
	"Cats are often lactose intolerant, so stop givin' them milk!",
	'Basically all cartoon cats lied to us: Raw fish is off the table for cats as well.',
	'The oldest cat video on YouTube dates back to 1894 (when it was made, not when it was uploaded, duh).',
	'In the 1960s, the CIA tried to turn a cat into a bonafide spy by implanting a microphone into her ear and a radio transmitter at the base of her skull.',
	'The technical term for "hairball" is "bezoar."',
	'Female cats are typically right-pawed while male cats are typically left-pawed.',
	'Cats make more than 100 different sounds whereas dogs make around 10.',
	"A cat's brain is 90% similar to a human's — more similar than to a dog's.",
	'Cats and humans have nearly identical sections of the brain that control emotion.',
	"A cat's cerebral cortex (the part of the brain in charge of cognitive information processing) has 300 million neurons, compared with a dog's 160 million.",
	'Cats have a longer-term memory than dogs, especially when they learn by actually doing rather than simply seeing.',
	'Basically, cats have a lower social IQ than dogs but can solve more difficult cognitive problems when they feel like it.',
	'Cats have 1,000 times more data storage than an iPad.',
	'It was illegal to slay cats in ancient Egypt, in large part because they provided the great service of controlling the rat population.',
	'In the 15th century, Pope Innocent VIII began ordering the killing of cats, pronouncing them demonic.',
	"A cat has five toes on his front paws, and four on the back, unless he's a polydactyl.",
	'Polydactyl cats are also referred to as "Hemingway cats" because the author was so fond of them.',
	"There are 45 Hemingway cats living at the author's former home in Key West, Fla.",
	'Original kitty litter was made out of sand but it was replaced by more absorbent clay in 1948.',
	'Abraham Lincoln kept four cats in the White House.',
	'When asked if her husband had any hobbies, Mary Todd Lincoln is said to have replied "cats."',
	'Isaac Newton is credited with inventing the cat door.',
	"One legend claims that cats were created when a lion on Noah's Ark sneezed and two kittens came out.",
	'A cat can jump up to six times its length.',
	'A house cat is faster than Usain Bolt.',
	"When cats leave their poop uncovered, it is a sign of aggression to let you know they don't fear you.",
	'Cats can change their meow to manipulate a human. They often imitate a human baby when they need food, for example.',
	'Cats use their whiskers to detect if they can fit through a space.',
	'Cats only sweat through their foot pads.',
	'The first cat in space was French. She was named Felicette, or "Astrocat." She survived the trip.',
	'Cats have free-floating clavicle bones that attach their shoulders to their forelimbs, which allows them to squeeze through very small spaces.',
	"Hearing is the strongest of cat's senses: They can hear sounds as high as 64 kHz — compared with humans, who can hear only as high as 20 kHz.",
	'Cats can move their ears 180 degrees.',
	'They can also move their ears separately.',
	"A cat has detected his human's breast cancer.",
	"A cat's nose is ridged with a unique pattern, just like a human fingerprint.",
	'Cats have scent glands along their tail, their forehead, lips, chin, and the underside of their front paws.',
	'A cat rubs against people to mark its territory.',
	'Cats lick themselves to get your scent off.',
	'When a family cat died in ancient Egypt, family members would shave off their eyebrows as they mourned.',
	'They also had elaborate memorials that included mummifying the cat and either burying it in a family tomb or pet cemetery.',
	'Cats were mythic symbols of divinity in ancient Egypt.',
	'Black cats are bad luck in the United States, but they are good luck in the United Kingdom and Australia.',
	"Most cats don't like water because their coats do not insulate them well enough.",
	'However, a cat called the Turkish Van does not have that insulation problem and LOVES it.',
	'The Egyptian Mau is the oldest breed of cat.',
	'This breed is also the fastest pedigreed cat.',
	'The Egyptian word for cat is, in fact, "mau."',
	'Only 11.5% of people consider themselves "cat people."',
	'Cat people are also 11% more likely to be introverted.',
	'Still, cat people are more open to new experiences than typical "dog people."',
	'Cat owners who are male tend to be luckier in love, as they are perceived as more sensitive.',
	'Cat owners are 17% more likely to have a graduate degree.',
	'Cat people are 25% likely to pick George as their favorite Beatle.',
	"A cat's carbon footprint is similar to that of a VW Bug, whereas a dog's is more like a Hummer.",
	'When your cat brings home a dead mouse or bird, it may do so to show you that you suck at hunting.',
	'Cats have inferior daytime sight, but during the night they need seven times less light than humans to see.',
	'The largest litter of kittens produced 19 kittens.',
	'Eighty-eight percent of cats in the U.S. are spayed or neutered.',
	'Only 24% of cats who enter animal shelters are adopted.',
	'Cats are really cool.',
	'Cats are the most popular pet in the United States: There are 88 million pet cats and 74 million dogs.',
	'There are cats who have survived falls from over 32 stories (320 meters) onto concrete.',
	'A group of cats is called a clowder.',
	'Cats have over 20 muscles that control their ears.',
	'Cats sleep 70% of their lives.',
	'A cat has been mayor of Talkeetna, Alaska, for 15 years. His name is Stubbs.',
	'And one ran for mayor of Mexico City in 2013.',
	'In tigers and tabbies, the middle of the tongue is covered in backward-pointing spines, used for breaking off and gripping meat.',
	'When cats grimace, they are usually "taste-scenting." They have an extra organ that, with some breathing control, allows the cats to taste-sense the air.',
	"A house cat's genome is 95.6 percent tiger, and they share many behaviors with their jungle ancestors, says Layla Morgan Wilde, a cat behavior expert and the founder of Cat Wisdom 101. These behaviors include scent marking by scratching, prey play, prey stalking, pouncing, chinning, and urine marking.",
	"Cats are believed to be the only mammals who don't taste sweetness.",
	'Cats are nearsighted, but their peripheral vision and night vision are much better than that of humans.',
	'Cats are supposed to have 18 toes (five toes on each front paw; four toes on each back paw).',
	'Cats can jump up to six times their length.',
	"Cats' claws all curve downward, which means that they can't climb down trees head-first. Instead, they have to back down the trunk.",
	"Cats' collarbones don't connect to their other bones, as these bones are buried in their shoulder muscles.",
	'Cats have 230 bones, while humans only have 206.',
	'Cats have an extra organ that allows them to taste scents on the air, which is why your cat stares at you with her mouth open from time to time.',
	'Cats have whiskers on the backs of their front legs, as well.',
	'Cats have nearly twice the amount of neurons in their cerebral cortex as dogs.',
	'Cats have the largest eyes relative to their head size of any mammal.',
	'Cats make very little noise when they walk around. The thick, soft pads on their paws allow them to sneak up on their prey -- or you!',
	"Cats' rough tongues can lick a bone clean of any shred of meat.",
	"Cats use their long tails to balance themselves when they're jumping or walking along narrow ledges.",
	'Cats use their whiskers to "feel" the world around them in an effort to determine which small spaces they can fit into. A cat\'s whiskers are generally about the same width as its body. (This is why you should never, EVER cut their whiskers.)',
	'Cats walk like camels and giraffes: They move both of their right feet first, then move both of their left feet. No other animals walk this way.',
	'Male cats are more likely to be left-pawed, while female cats are more likely to be right-pawed.',
	'Though cats can notice the fast movements of their prey, it often seems to them that slow-moving objects are actually stagnant.',
	'Some cats are ambidextrous, but 40 percent are either left- or right-pawed.',
	'Some cats can swim.',
	'There are cats who have more than 18 toes. These extra-digit felines are referred to as being "polydactyl."',
	"A cat's average lifespan increased by a year over the span of time between 2002 and 2012, according to a study by Banfield Pet Hospital.",
	'According to The Huffington Post, cats typically sleep for 12 to 16 hours a day.',
	"Cats are crepuscular, which means that they're most active at dawn and dusk.",
	'Cats are fastidious creatures about their "bathroom." If you have more than one cat, you should have one litter box for each.',
	'Cats can spend up to a third of their waking hours grooming.',
	'Cats live longer when they stay indoors.',
	"Cats' purring may be a self-soothing behavior, since they make this noise when they're ill or distressed, as well as when they're happy.",
	'Cats will refuse an unpalatable food to the point of starvation.',
	'Despite popular belief, many cats are actually lactose intolerant.',
	'Female cats have the ability to get pregnant when they are only 4 months old!',
	"Grapes and raisins, as well as onions, garlic, and chives, are all extremely harmful foods for cats. Grapes and raisins can cause kidney failure -- although the reasoning behind that isn't clear. Meanwhile, onions, garlic, and chives wreak havoc on your cat's gastrointestinal system and can cause anemia.",
	"If you keep your cat active during the day, he will sleep better at night. If you're not free-feeding your cat, you can also help her get a good night's sleep by providing her with a substantial evening meal.",
	"It's believed that catnip produces an effect similar to LSD or marijuana in cats. The effects of nepetalactone -- the chemical in catnip that can makes cats crazy -- wears off within 15 minutes, and won't surface again for a few hours, even if your cat remains in sniffing distance.",
	"Kittens can be spayed or neutered when they are only eight weeks old. If possible, these procedures should be performed in the first 5 months of your cat's life.",
	'Male cats who have been fixed need fewer calories to maintain their weight.',
	"Spaying and neutering can extend a cat's life. The Banfield Pet Hospital study found that neutered males live an average of 62 percent longer than unneutered cats and spayed females live an average of 39 percent longer than unspayed cats.",
	"Your cat's grooming process stimulates blood flow to his skin, regulates his body temperature and helps him relax.",
	'A cat with a question-mark-shaped tail is asking, "Want to play?"',
	'According to Wilde, a slow blink is a "kitty kiss." This movement shows contentment and trust.',
	'Cats have a unique "vocabulary" with their owner -- each cat has a different set of vocalizations, purrs and behaviors.',
	'Cats have up to 100 different vocalizations -- dogs only have 10.',
	'Cats find it threatening when you make direct eye contact with them.',
	'Cats mark you as their territory when they rub their faces and bodies against you, as they have scent glands in those areas.',
	'Cats may yawn as a way to end a confrontation with another animal. Think of it as their "talk to the hand" gesture.',
	"Hissing is defensive, not aggressive, says Wilde. \"It's an expression of fear, stress or discomfort of a threatened cat communicating 'stay away,'\" she says.",
	"If cats are fighting, the cat that's hissing is the more vulnerable one, says Wilde.",
	'If your cat approaches you with a straight, almost vibrating tail, this means that she is extremely happy to see you.',
	'Kneading -- which some people refer to as "making biscuits" -- is a sign of contentment and happiness. Cats knead their mothers when they are nursing to stimulate the let-down of milk.',
	'Meowing is a behavior that cats developed exclusively to communicate with people.',
	"When a cat flops over and exposes his belly, it's not always an invitation for a belly rub. A cat does this when he's relaxed and showing trust.",
	"When cats hit you with retracted claws, they're playing, not attacking.",
	"When dogs wag their tails, they may be expressing happiness. But this isn't the case for cats! When your cat wags her tail, it's her way of warning you that you are getting on her last nerve.",
	'When your cat sticks his butt in your face, he is doing so as a gesture of friendship.',
	"Whiskers are also good indicators of a cat's mood. When a cat is scared, he put his whiskers back. But when a cat is in hunting mode, he puts his whiskers forward.",
	'Your cat drapes its tail over another cat, your dog, or you as a symbol of friendship.',
	'Cats are very fussy about their water bowls; some prefer to ignore their bowls entirely in favor of drinking from the sink faucet.',
	'Cats groom other cats -- and sometimes people -- in a ritual called allogrooming.',
	'Cats like to sleep on things that smell like their owners, such as their pillows and dirty laundry (ick!).',
	"Cats love to sleep in laundry baskets, too, because they're basically hiding places with peep holes.",
	"Cats often attack your ankles when they're bored.",
	"Certain cats go crazy for foods you wouldn't expect, like olives, potato chips, and the hops in beer.",
	'For some reason, cats really dislike citrus scents.',
	"If you can't find your cat, you should look in a box or a bag, as these are some of their favorite hiding spots!",
	'Male cats who try to get to a female in heat can show very bizarre behavior -- for example, some have been known to slide down chimneys!',
	"Many cats like to lick their owner's freshly washed hair.",
	'Some cats love the smell of chlorine.',
	'Thieving behavior is not uncommon among cats. They will often grab objects like stuffed animals, feather dusters, and other things that remind them of prey.',
	'A green cat was born in Denmark in 1995. Some people believe that high levels of copper in the water pipes nearby may have given his fur a verdigris effect.',
	'It turns out that Abraham Lincoln was a crazy cat president! He had four cats that lived in the White House with him.',
	'Maria Assunta left her cat, Tomasso, her entire $13 million fortune when she died in 2011.',
	"President Bill Clinton's cat, Socks, was a media darling during the Clinton administration and was said to receive more letters than the President himself.",
	'Stubbs, a 17-year-old orange tabby, is mayor of the historic district of Talkeetna, Alaska.',
	"A cat's learning style is about the same as a 2- to 3-year-old child.",
	"A cat's purr vibrates at a frequency of 25 to 150 hertz, which is the same frequency at which muscles and bones repair themselves.",
	'A group of kittens is called a "kindle."',
	'A house cat could beat superstar runner Usain Bolt in the 200 meter dash.',
	'About half of the cats in the world respond to the scent of catnip.',
	'Cat breeders are called "catteries."',
	'Cats can be toilet-trained.',
	"Cats can drink sea water in order to survive. (In case you're wondering, we can't.)",
	"Cats don't have an incest taboo, so they may choose to mate with their brothers and sisters.",
	'Cats dream, just like people do.',
	'Cats have contributed to the extinction of 33 different species.',
	'Cats perceive people as big, hairless cats, says Wilde.',
	'Cats were first brought to the Americas in colonial times to get rid of rodents.',
	'Collective nouns for adult cats include "clowder," "clutter," "glaring," and "pounce."',
	"Each cat's nose print is unique, much like human fingerprints.",
	"It's not uncommon to see cats in food stores in big cities as a form of free -- and adorable -- pest control.",
	'Kittens in the same litter can have more than one father. This is because the female cat releases multiple eggs over the course of a few days when she is in heat.',
	'Male cats are the most sensitive to catnip, while kittens under 3 months old have no response at all.',
	'Most world languages have a similar word to describe the "meow" sound.',
	'Some 700 million feral cats live in the United States, and many shelters run trap-neuter-release programs to stem the population growth.',
	'Studies suggest that domesticated cats first appeared around 3600 B.C.',
	'The first known cat video was recorded in 1894.',
	'There are about 88 million pet cats in the United States, which makes them the most popular pet in the country!',
	"Two hundred feral cats prowl the park at Disneyland, doing their part to control rodents -- the ones who don't wear funny outfits and speak in squeaky voices.",
	'White cats with blue eyes are prone to deafness.',
	'ng to The Huffington Post, cats typically sleep for 12 to 16 hours a day.',
	"When cats hit you with retracted claws, they're playing, not attacking.",
	'They are crepuscular, which means that they are most active at dawn and dusk.',
	'As is the case with kids, if you keep your cat active during the day, he will sleep better at night.',
	"If you're not free-feeding, you can also help your cat get a good night's sleep by providing her with a substantial evening meal.",
	'Cats are fastidious creatures about their “bathroom.” If you have more than one cat, you should have one litter box for each.',
	'Cats learn to manipulate humans with their meows — some even develop a cry like a baby!',
	'Meowing is a behavior that cats developed exclusively to communicate with people.',
	'Cats mark you as their territory when they rub their faces and bodies against you, as they have scent glands in those areas.',
	'Kneading — which some people refer to as “making biscuits” — is a sign of contentment and happiness. Cats knead their mothers when they are nursing to stimulate the let-down of milk.',
	'Cats often attack your ankles when they are bored.',
	"When dogs wag their tails, they may be expressing happiness. But this is not the case for cats! When your cat wags her tail, it's her way of warning you that you are getting on her last nerve.",
	'Cats live longer when they stay indoors.',
	'Cats walk like camels and giraffes: They move both of their right feet first, then move both of their left feet. No other animals walk this way.',
	'Cats make very little noise when they walk around. The thick, soft pads on their paws allow them to sneak up on their prey — or you!',
	'Female cats have the ability to get pregnant when they are only 4 months old!',
	'Some cat facts are, well, a little gross. For instance, these animals do not have an incest taboo, so they may choose to mate with their brothers and sisters.',
	"Kittens can be spayed or neutered when they are only eight weeks old. If possible, these procedures should be performed in the first 5 months of your cat's life.",
	'Male cats who have been fixed need fewer calories to maintain their weight.',
	'Cats were first brought to the Americas in colonial times to get rid of rodents.',
	"It's not uncommon to see cats in food stores in big cities as a form of free — and adorable — pest control.",
	'A group of kittens is called a kindle.',
	'Collective nouns for adult cats include clowder, clutter, glaring and pounce.',
	"Cats are believed to be the only mammals who don't taste sweetness.",
	'A green cat was born in Denmark in 1995. Some people believe that high levels of copper in the water pipes nearby may have given his fur a verdigris effect.',
	'Cats will refuse an unpalatable food to the point of starvation.',
	'White cats with blue eyes are prone to deafness.',
	'Some cats are ambidextrous, but 40 percent are either left- or right-pawed.',
	'Male cats are more likely to be left-pawed, while female cats are more likely to be right-pawed.',
	'Cats can spend up to a third of their waking hours grooming.',
	"Your cat's grooming process stimulates blood flow to his skin, regulates his body temperature and helps him relax.",
	'Cats groom other cats — and sometimes people — in a ritual called allogrooming.',
	'Cats may yawn as a way to end a confrontation with another animal. Think of it as their “talk to the hand” gesture.',
	"Each cat's nose print is unique, much like human fingerprints.",
	'Cats dislike citrus scents.',
	'Certain cats go crazy for foods you would not expect, like olives, potato chips and the hops in beer.',
	'Some cats love the smell of chlorine.',
	"Many cats like to lick their owner's freshly washed hair.",
	'Cats like to sleep on things that smell like their owners, like their pillows and dirty laundry (ick!).',
	'Cats also love to sleep in laundry baskets, because they appear to be a hiding place with peep holes.',
	"Cats use their whiskers to “feel” the world around them in an effort to determine which small spaces they can fit into. A cat's whiskers are generally about the same width as its body.",
	"Whiskers are also good indicators of a cat's mood. When a cat is scared, he put his whiskers back. But when a cat is in hunting mode, he puts his whiskers forward.",
	'Cats have whiskers on the backs of their front legs, as well.',
	'Kittens in the same litter can have more than one father. This is because the female cat releases multiple eggs over the course of a few days when she is in heat.',
	'Cats dream, just like people do.',
	'Cats have the largest eyes relative to their head size of any mammal.',
	"Cats' rough tongues can lick a bone clean of any shred of meat.",
	'Cats can be toilet-trained.',
	'Cats have 230 bones, while humans only have 206.',
	"Cats' collarbones don't connect to their other bones, as these bones are buried in their shoulder muscles.",
	"A cat's average lifespan increased by a year over the span of time between 2002 and 2012, according to a study by Banfield Pet Hospital.",
	"Male cats who trying to get to a female in heat can show very bizarre behavior — they've even been known to slide down chimneys!",
	'Cats can jump up to six times their length.',
	'Cats use their long tails to balance themselves when they are jumping or walking along narrow ledges.',
	'If your cat approaches you with a straight, almost vibrating tail, this means that she is extremely happy to see you.',
	'A cat with a question-mark-shaped tail is asking, “Want to play?”',
	'Your cat drapes its tail over another cat, your dog or you as a symbol of friendship.',
	'Most world languages have a similar word to describe the “meow” sound.',
	'If cats are fighting, the cat that is hissing is the more vulnerable one.',
	'Cats have a unique “vocabulary” with their owner — each cat has a different set of vocalizations, purrs and behaviors.',
	"If you can't find your cat, you should look in a box or a bag, as these are some of their favorite hiding spots!",
	'Cats are very fussy about their water bowls, and some prefer to ignore their bowls entirely in favor of drinking from the sink faucet.',
	'Thieving behavior is not uncommon among cats. They will often grab objects like stuffed animals, feather dusters and other things that remind them of prey.',
	'When your cat sticks his butt in your face, he is doing so as a gesture of friendship.',
	'Cats perceive people as big, hairless cats, says Wilde.',
	'Some 700 million feral cats live in the United States, and many shelters run trap-neuter-release programs to stem the population growth.',
	'Cat breeders are called catteries.',
	'Only about half of the cats in the world respond to the scent of catnip.',
	"It's believed that catnip produces an effect similar to LSD or marijuana in cats.",
	"The effects of nepetalactone — the chemical in catnip that can makes cats crazy — wears off within 15 minutes, and won't surface again for a few hours, even if your cat remains in sniffing distance.",
	'Male cats are the most sensitive to catnip, while kittens under 3 months old have no response at all.',
	'Cats can drink sea water in order to survive.',
	'Some cats can swim.',
	'Cats have contributed to the extinction of 33 different species.',
	"Two hundred feral cats prowl the park at Disneyland, doing their part to control rodents — the ones who don't wear funny outfits and speak in squeaky voices.",
	'There are about 88 million pet cats in the United States, which makes them the most popular pet in the country!',
	'Cats have an extra organ that allows them to taste scents on the air, which is why your cat stares at you with her mouth open from time to time.',
	'Stubbs, a 17-year-old orange tabby, is mayor of the historic district of Talkeetna, Alaska.',
	"President Bill Clinton's cat, Socks, was a media darling during the Clinton administration and was said to receive more letters than the President himself.",
	'Cat videos are so popular online that there is an annual film festival that features the best ones.',
	'In August 2013, 11,000 people attended the Internet Cat Video Festival at the Minnesota State Fair.',
	'“Surprised Kitty,” which is the most popular cat video in history, has been viewed more than 65 million times on YouTube.',
	'The first Internet cat video, “Puppy Vs. Cat,” was initially uploaded in 2006.',
	"A cat's purr can be self-soothing, as these animals makes this noise when they are ill or distressed.",
	"A cat's purr vibrates at a frequency of 25 to 150 hertz, which is the same frequency at which muscles and bones repair themselves.",
	'The first known cat video was recorded in 1894.',
	'Maria Assunta left her cat, Tomasso, her entire $13 million fortune when she died in 2011.',
	'Cats have nearly twice the amount of neurons in their cerebral cortex as dogs.',
	"A cat's learning style is about the same as a 2- to 3-year-old child.",
	'There is an urban legend that Sir Isaac Newton invented the cat door, but in fact they were mentioned in literature centuries before he was born.',
	'A house cat could beat superstar runner Usain Bolt in the 200 meter dash.',
	'Cats are nearsighted, but their peripheral vision and night vision are much better than those of humans.',
	'Though cats can notice the fast movements of their prey, it often seems to them that slow-moving objects are actually stagnant.',
	'Cats have up to 100 different vocalizations.',
	'According to Wilde, a slow blink is a “kitty kiss.” This movement shows contentment and trust.',
	'Americans really love their pet cats. There are approximately 14 million more house cats than dogs in the US.',
	'Male cats are called toms and females are called queens or mollies.',
	"The saying, 'A cat always lands on its feet' isn't just an old myth. Some cats have fallen more than 320 metres onto concrete and come away unharmed.",
	"There's a reason why cats are likely to survive high falls - they have more time to prepare for the landing.",
	"It's not a flock, it's not a herd - a group of cats together is known as a 'clowder'.",
	'According to statistics, cat owners are healthier than those without cats. The risk of heart attack is cut by a third among people who have a pet cat.',
	"Just as a dog's bark has several different meanings, a cat may purr because it is nervous, happy or feeling unwell.",
	"It's common knowledge that cats are fans of milk, but many of them are lactose intolerant. This means that they are actually allergic to milk.",
	'Garfield, the lasagne-loving feline, was featured in the Guinness Book of World Records for being the most widely published cartoon.',
	"Cats are thought to be pretty smart, and with a brain 90% similar to the human brain, it's no surprise.",
	'When Abraham Lincoln was US President, he had four pet cats which lived with him in the White House.',
	"Felicette was the first feline to make a trip to space. She luckily survive the mission and was nicknamed 'Astrocat'.",
	"If you think of yourself as a 'cat person', you're among 11.5% of people in the world.",
	"If you're a male with a pet cat, you're more likely to find true love. This is due to the fact that people view cat owners are kind, trustworthy and sensitive.",
	'The record for the largest number of kittens in the same litter was 19.',
	'Over her lifetime, a cat called Dusty had a total of 420 kittens.',
	'The oldest cat to give birth to kittens was called Kitty. She was 30 years old when she birthed her last kittens.',
	"Bagpuss was a 1999 TV show which featured an old cloth cat. In 2001, it came fourth in a poll of the greatest kids' TV shows.",
	'While people dote over their cats in the West, around 4 million cats are killed and eaten over in Asia.',
	'There are about 70 different cat breeds and a staggering 500 million pet cats in the world.',
	'Ancient Egyptians worshipped a goddess who was half cat and half woman.',
	'In Ancient Egypt, civilians would suffer a severe punishment if they hurt a cat.',
	'Ever noticed your cat sleeping most of the time? On average, cats sleep for about 16 hours per day.',
	'Kittens sleep even more often, since growth hormones are released when they are napping.',
	'The front paws of a cat are different from the back paws. They have five toes on the front but only four on the back.',
	"Some cats are known as 'polydactyl' and have extra toes. Some polydactyl have as many as eight toes per paw.",
	'Unlike dogs, cats have no sense of what is sweet. No wonder they never seem happy with cakes!',
	'Did you think the cat flap was an ultra-modern idea? Isaac Newton is credited with the invention of the cat flap - something which most cat owners now have.',
	'Isaac Newton himself had a cat called Spithead, which influenced his invention. Spithead went on to have kittens, who all got their very own cat flap.',
	'Many cat owners take their pets to the vet to be neutered, and by doing so, increase the life expectancy of their pets by 2-3 years.',
	'Cats can see very well in the dark, which explains why they are always wandering around at night.',
	"Adolf Hitler hated cats, so there's another reason why you shouldn't like him.",
	'Taurine is an amino acid which can be found in cat food. Without this substance, your pet cat would eventually go blind.',
	'House cats can run at a speed of 30 miles per hour.',
	'The kidneys of a cat are quite amazing, since they can filter water before using it. This means that a cat can drink sea water and the salt will be filtered out.',
	"Those cute furry bits inside a cat's ear are called 'ear furnishings'. They ensure that dirt doesn't go inside and also helps them to hear well.",
	'Cats have a great sense of hearing and can hear ultrasonic noises. They could potentially hear dolphins.',
	"It's not just humans who are right-handed or left-handed. Most female cats prefer using their right paw, while male are more likely to be 'left-pawed'.",
	"A 'haw' is the third eyelid of a cat, which can only be seen when the cat isn't well.",
	"They might have an extra eyelid, but they don't have any eyelashes.",
	'The original version of Cinderella in Italy featured a cat as the fairy godmother.',
	'Dogs make 10 different sounds, while cats can make as many as 100 different noises.',
	'Cats seem like such sweet creatures, but approximately 40,000 people suffer from cat bites every single year in America.',
	'When you see a cat rubbing up against a human, it is being affectionate but also marking its territory to make other cats aware.',
	'The cat family consists of many different animals, but the largest is the Siberian Tiger, which can be as large as 12 feet long.',
	'The black-footed cat is the smallest wild cat, at just 20 inches long.',
	'The wealthiest cat ever was Blackie, a multi-millionaire. It owned £15 million after its rich owner died.',
	'London was the home of the first ever cat show. It took place in 1871 and started a trend which has continued ever since.',
	"While cats like to catch mice and eat them, it's not necessarily a good meal. They can contract tapeworm through eating these rodents.",
	"Cats' hearts beat at a rate of 110-140 beats per minutes - around twice as fast as the average human.",
	'Ancient Egyptian cat owners would shave off their eyebrows when mourning for their dead kitties.',
	"'Mau' is the Egyptian word for cat, and the oldest surviving cat breed is known as the Egyptian Mau, translated to mean the 'Egyptian cat'.",
	'While people are hesitant to buy cats of opposite sexes, they will actually get along better than those of the same sex.',
	'If you own a cat, you should feed them 10-20 small meals every day, rather than fewer and larger meals.',
	'Over the Christmas season, cats should avoid poinsettias as they are poisonous.',
	'Stray and feral cats which live outdoors have a life span of around 4 years. Those which live indoors can live up to 16 years or more.',
	'Cats are lovers of fish, but too much tuna can cause them to become addicted to this meat.',
	'They use their tongues to thoroughly clean themselves, but they also use them to get rid of human scent.',
	'When cats are first born, they have blue eyes. Over time, the colour changes.',
	'Kittens also have much sharper teeth than adult cats. Their teeth become blunt when they are around 6 months old.',
	'Cats which have blue eyes for the duration of their lives are likely to be deaf.',
	'They usually hate water, but the Turkish Van cats actually enjoy getting wet!',
	"Unlike many other animals, cats cannot produce fat on their own. It's important to give your pet a balanced diet which includes good fats.",
	"Just as a human's fingerprints are unique, each cat has a completely different nose.",
	'Many people are allergic to cats, but cats can actually be allergic to humans too. Around one in 200 domestic cats suffer from asthma due to smoke, dust and other particles within houses.',
	'As long as you introduce your cat to your dog before they are both six months old, they should get along well.',
	"Although studies suggested that cats didn't enjoy being stroked by humans, further research has proven that they do in fact like it.",
	"A cat's brain is so quick that even a super-computer in 2015 couldn't beat it.",
	'Feral cats will go out exploring more often and much further than house cats. House cats can normally be found within the area they live.',
	'It is thought that 55% of house cats are obese due to overeating.',
	"Alzheimer's disease can be found in cats, just as it can be found in humans.",
	'Cats were first kept as pets about 5,000 years ago in China. Farmers were the first to realise that felines could be kept in the home.',
	'In 2011, scientists concluded that your pet cat may become very ill if you interfere with its routine.',
	'The high-pitched cry which you may have heard from your cat is an attempt for cats to get their own way. The cry is similar to that of a new-born baby.',
	'Cats enjoy sitting on warm objects, which is probably why your kitty likes to sit on your computer so often.',
	"It's a well-known fact that cats are very fussy creatures, and if your pet doesn't always drink water from its water bowl, it may not like the shape of the bowl!",
	'Cats might look harmless, but they have worked together to make over 30 different species extinct. Even house cats love hunting, and have contributed heavily to this figure.',
	'They only sweat through their paws, as this is the only place which has sweat glands.',
	"In the 1950's, Disneyland bought several cats in order to hunt mice at night. There are now more than 200 felines at the amusement park.",
	'Their whiskers are used to measure gaps and openings. They allow the cat to work out whether or not they will fit through spaces.',
	'Historians believe that every species of the cat family came from one of just five different wild cats from Africa.',
	'Female cats can breed with several males when they are in heat. These means that a litter of kittens could potentially have a few different fathers!',
	'A cat can rotate each of its ears separately. Each ear has a total of 32 muscles.',
	"Don't feed chocolate to your cat - it's poisonous.",
	'Cats are pretty amazing at jumping; they can jump up to seven times higher than the length of their tail.',
	"There's a charming reason your cat brings dead mice to you. It means that your pet likes you!",
	"They cannot survive eating a vegetarian diet, which is why it's important to feed your cat meat.",
	'Cats can find their way home even if they have travelled miles away.',
	'Black cats are the least likely to be adopted from an animal home, although people love buying jet black kittens.',
	"A cat's tail will quiver if it is near somebody it loves.",
	'Think your cat purrs a lot? Cats purr up to 26 times per second.',
	"Felines enjoy spending time alone. Unlike dogs, they don't need much attention and can be very happy without any companionship.",
	"You shouldn't feed many cats from the same food bowl. It is very likely that some of them will refuse to eat from it, choosing rather to eat alone.",
	"Don't stare at your cat for long periods of time. This is seen as threatening and will make it feel uneasy.",
	"There are many plants which are poisonous for cats, although parsley, sage and other herbs are among a cat's favourite foods.",
	"If you put a collar on your cat, make sure it's not too tight. You should be able to fit two fingers between the collar and your cat's neck, or you could risk strangling it.",
	'The fear of cats is known as Ailurophobia.',
	'A town called Talkeetna in Alaska had a cat as mayor for 15 years.',
	"The record for the world's longest cat was 48.5 inches.",
	"Cats do recognise their owners' voices, but often act like they don't care.",
	"Cats have over 1,000 times more data storage space than an iPad…and yet they're still perpetually foiled by doors!",
	'Cats can move their ears 180 degrees and at separate times, this is very useful for remaining constantly alert while on the hunt.',
	'Cat noses are ridged and are completely unique to every single cat. They are basically the equivalent of a human fingerprint.',
	'Cats need 7 times less light to see at night than you do, which is why they run around your house in the middle of the night in pitch blackness with ease!',
	"It sucks for them, but cats can't taste sweet things. The upside to this is that, unlike dogs, most cats won't be that excited about sharing your dessert.[11]",
	'Cats have between 230-250 bones in their body, some of their bones can fuse together with age hence there is no exact number.',
	"Cats can jump up to 7 times their length…that's about 3 times as high as a dog can jump, you may have witnessed this is you tried the scare your cat with a cucumber trick.",
	'Cats can hear 2 octaves higher than a human, which is how ultrasonic cat deterrants work….by broadcasting annoying high pitch noises which cats hate!',
	'Cats normally have 18 toes.',
	"Cats can run as fast as 30mph when they absolutely need to (if they are being chased), this is a couple of miles per hour faster than Usain Bolt's top speed!",
	'here is evidence that people have had cats as pets for over 11,500 years; a young wildcat was found buried with a human in Cyprus at a burial site believed to date from 9,500 B.C. [12]',
	'The earliest evidence of widespread cat domestication comes from China around 5,300 years ago. Where cats were used to keep the rodent population in check and stop them from eating all their grain.[13]',
	'When a family cat died in Ancient Egypt, the family mourned their loss by shaving their eyebrows. We think this is one tradition that should be bought back!',
	"There are 8 million pets cats in the UK, making them the UK's second favourite pet trailing narrowly behind dogs of which there are 9 million in the UK. [14]",
	"Do you think you're the first pet owner to dress their kitty up? Think again. Ancient Egyptians dressed their cats in jewels and ornate costumes. Step your game up.",
	'Cats represented sexuality and fertility in Ancient Egypt. The Egyptians also thought they were magic animals capable of bringing good luck.',
	'As many as 300,000 cats were found mummified, many with their owners, at a temple dedicated to Bastet (a god depicted as a feline/human).',
	'Brits with cats are 33% less likely to have a stroke. Yes apparently owning a cat helps you relax and lowers your heart rate![19]',
	'The average house cat lives about 15 years, so remember a cat is a big responsibility which is for life not just for Christmas.',
	'Your cat perceives you as just another cat. Only a big, hairless one that dispenses food and cleans up poop.',
	'Owning a cat decreases your risk of heart disease.[20]',
	'A litter of cats is called a kindle, sometimes groups of kittens are also known as Intrigues or Entanglements.',
	"In 2004 the first commercially cloned cat, little Nicky, was cloned from 17-year-old “big” Nicky at a cost of £27,000 - unsurprisingly this was a controversial move and pet cloning hasn't taken off!",
	"Cats will lick an owner's hair or massage your lap to signify they love you and consider you part of their family.",
	"Cats also display their love for you by kneading - it's just a shame it hurts so much, the sharp claws often ruin the moment!",
	"Cats rub against you to mark their territory and show affection, yes that's right, your cat considers you to be their territory…their property!",
	"Cats are believed to be the only mammals who don't taste sweetness.",
	'Cats are nearsighted, but their peripheral vision and night vision are much better than that of humans.',
	'Cats are supposed to have 18 toes (five toes on each front paw; four toes on each back paw).',
	'Cats can jump up to six times their length.',
	"Cats' claws all curve downward, which means that they can't climb down trees head-first. Instead, they have to back down the trunk.",
	"Cats' collarbones don't connect to their other bones, as these bones are buried in their shoulder muscles.",
	'Cats have 230 bones, while humans only have 206.',
	'Cats have an extra organ that allows them to taste scents on the air, which is why your cat stares at you with her mouth open from time to time.',
	'Cats have whiskers on the backs of their front legs, as well.',
	'Cats have nearly twice the amount of neurons in their cerebral cortex as dogs.',
	'Cats have the largest eyes relative to their head size of any mammal.',
	'Cats make very little noise when they walk around. The thick, soft pads on their paws allow them to sneak up on their prey — or you!',
	"Cats' rough tongues can lick a bone clean of any shred of meat.",
	"Cats use their long tails to balance themselves when they're jumping or walking along narrow ledges.",
	'Cats walk like camels and giraffes: They move both of their right feet first, then move both of their left feet. No other animals walk this way.',
	'Male cats are more likely to be left-pawed, while female cats are more likely to be right-pawed.',
	'Though cats can notice the fast movements of their prey, it often seems to them that slow-moving objects are actually stagnant.',
	'Some cats are ambidextrous, but 40 percent are either left- or right-pawed.',
	'Some cats can swim.',
	'There are cats who have more than 18 toes. These extra-digit felines are referred to as being “polydactyl.”',
	"A cat's average lifespan increased by a year over the span of time between 2002 and 2012, according to a study by Banfield Pet Hospital.",
	'According to The Huffington Post, cats typically sleep for 12 to 16 hours a day.',
	"Cats are crepuscular, which means that they're most active at dawn and dusk.",
	'Cats are fastidious creatures about their “bathroom.” If you have more than one cat, you should have one litter box for each.',
	'Cats can spend up to a third of their waking hours grooming.',
	'Cats live longer when they stay indoors.',
	"Cats' purring may be a self-soothing behavior, since they make this noise when they're ill or distressed, as well as when they're happy.",
	'Cats will refuse an unpalatable food to the point of starvation.',
	'Despite popular belief, many cats are actually lactose intolerant.',
	'Female cats have the ability to get pregnant when they are only 4 months old!',
	"If you keep your cat active during the day, he will sleep better at night. If you're not free-feeding your cat, you can also help her get a good night's sleep by providing her with a substantial evening meal.",
	"Kittens can be spayed or neutered when they are only eight weeks old. If possible, these procedures should be performed in the first 5 months of your cat's life.",
	'Male cats who have been fixed need fewer calories to maintain their weight.',
	"Your cat's grooming process stimulates blood flow to his skin, regulates his body temperature and helps him relax.",
	'Facts About Cat Communication Cues',
	'A cat with a question-mark-shaped tail is asking, “Want to play?”',
	'According to Wilde, a slow blink is a “kitty kiss.” This movement shows contentment and trust.',
	'Cats have a unique “vocabulary” with their owner — each cat has a different set of vocalizations, purrs and behaviors.',
	'Cats have up to 100 different vocalizations — dogs only have 10.',
	'Cats find it threatening when you make direct eye contact with them.',
	'Cats mark you as their territory',
	'when they rub their faces and bodies against you, as they have scent glands in those areas.',
	'Cats may yawn as a way to end a confrontation with another animal. Think of it as their “talk to the hand” gesture.',
	"Hissing is defensive, not aggressive, says Wilde. “It's an expression of fear, stress or discomfort of a threatened cat communicating 'stay away,'” she says.",
	"If cats are fighting, the cat that's hissing is the more vulnerable one, says Wilde.",
	'If your cat approaches you with a straight, almost vibrating tail, this means that she is extremely happy to see you.',
	'Kneading — which some people refer to as “making biscuits” — is a sign of contentment and happiness. Cats knead their mothers when they are nursing to stimulate the let-down of milk.',
	'Meowing is a behavior that cats developed exclusively to communicate with people.',
	"When a cat flops over and exposes his belly, it's not always an invitation for a belly rub. A cat does this when he's relaxed and showing trust.",
	"When cats hit you with retracted claws, they're playing, not attacking.",
	"When dogs wag their tails, they may be expressing happiness. But this isn't the case for cats! When your cat wags her tail, it's her way of warning you that you are getting on her last nerve.",
	'When your cat sticks his butt in your face, he is doing so as a gesture of friendship.',
	"Whiskers are also good indicators of a cat's mood. When a cat is scared, he put his whiskers back. But when a cat is in hunting mode, he puts his whiskers forward.",
	'Your cat drapes its tail over another cat, your dog, or you as a symbol of friendship.',
	'Cats are very fussy about their water bowls; some prefer to ignore their bowls entirely in favor of drinking from the sink faucet.',
	'Cats groom other cats — and sometimes people — in a ritual called allogrooming.',
	'Cats like to sleep on things that smell like their owners, such as their pillows and dirty laundry (ick!).',
	"Cats love to sleep in laundry baskets, too, because they're basically hiding places with peep holes.",
	"Cats often attack your ankles when they're bored.",
	"Certain cats go crazy for foods you wouldn't expect, like olives, potato chips, and the hops in beer.",
	'For some reason, cats really dislike citrus scents.',
	"If you can't find your cat, you should look in a box or a bag, as these are some of their favorite hiding spots!",
	'Male cats who try to get to a female in heat can show very bizarre behavior — for example, some have been known to slide down chimneys!',
	"Many cats like to lick their owner's freshly washed hair.",
	'Some cats love the smell of chlorine.',
	'Thieving behavior is not uncommon among cats. They will often grab objects like stuffed animals, feather dusters, and other things that remind them of prey.',
	'A green cat was born in Denmark in 1995. Some people believe that high levels of copper in the water pipes nearby may have given his fur a verdigris effect.',
	'It turns out that Abraham Lincoln was a crazy cat president! He had four cats that lived in the White House with him.',
	'Maria Assunta left her cat, Tomasso, her entire $13 million fortune when she died in 2011.',
	"President Bill Clinton's cat, Socks, was a media darling during the Clinton administration and was said to receive more letters than the President himself.",
	'Stubbs, a 17-year-old orange tabby, is mayor of the historic district of Talkeetna, Alaska.',
	"A cat's learning style is about the same as a 2- to 3-year-old child.",
	"A cat's purr vibrates at a frequency of 25 to 150 hertz, which is the same frequency at which muscles and bones repair themselves.",
	'A group of kittens is called a “kindle.”',
	'A house cat could beat superstar runner Usain Bolt in the 200 meter dash.',
	'About half of the cats in the world respond to the scent of catnip.',
	'Cat breeders are called “catteries.”',
	'Cats can be toilet-trained.',
	"Cats can drink sea water in order to survive. (In case you're wondering, we can't.)",
	"Cats don't have an incest taboo, so they may choose to mate with their brothers and sisters.",
	'Cats dream, just like people do.',
	'Cats have contributed to the extinction of 33 different species.',
	'Cats perceive people as big, hairless cats, says Wilde.',
	'Cats were first brought to the Americas in colonial times to get rid of rodents.',
	'Collective nouns for adult cats include “clowder,” “clutter,” “glaring,” and “pounce.”',
	"Each cat's nose print is unique, much like human fingerprints.",
	"It's not uncommon to see cats in food stores in big cities as a form of free — and adorable — pest control.",
	'Kittens in the same litter can have more than one father. This is because the female cat releases multiple eggs over the course of a few days when she is in heat.',
	'Male cats are the most sensitive to catnip, while kittens under 3 months old have no response at all.',
	'Most world languages have a similar word to describe the “meow” sound.',
	'Some 700 million feral cats live in the United States, and many shelters run trap-neuter-release programs to stem the population growth.',
	'Studies suggest that domesticated cats first appeared around 3600 B.C.',
	'The first known cat video was recorded in 1894.',
	'There are about 88 million pet cats in the United States, which makes them the most popular pet in the country!',
	"Two hundred feral cats prowl the park at Disneyland, doing their part to control rodents — the ones who don't wear funny outfits and speak in squeaky voices.",
	'White cats with blue eyes are prone to deafness.',
}
