local FunFact = FunFact
local module = FunFact:NewModule('FactList_Dinosaurs')
module.desciption = 'Facts about dinosaurs and prehistoric life.'
module.displayname = 'Dinosaurs'

module.Facts = {
	'The word "dinosaur" means "terrible lizard" in Greek.',
	'Dinosaurs lived on Earth for about 165 million years.',
	'The largest dinosaur ever discovered is Argentinosaurus, weighing up to 100 tons.',
	'T-Rex had the strongest bite of any land animal ever, at 12,800 pounds of force.',
	'Velociraptors were actually about the size of a turkey, not human-sized like in movies.',
	'The Stegosaurus had a brain the size of a walnut.',
	'Many dinosaurs swallowed stones to help digest their food.',
	'The longest dinosaur name is Micropachycephalosaurus, meaning "tiny thick-headed lizard".',
	'Some dinosaurs had feathers, including close relatives of T-Rex.',
	'The first dinosaur fossil was described scientifically in 1824.',
	'Triceratops had up to 800 teeth that were constantly replaced.',
	'The asteroid that killed the dinosaurs was about 6 miles wide.',
	'Pterodactyls were not actually dinosaurs - they were flying reptiles.',
	'The smallest dinosaur ever discovered is Microraptor at about 16 inches long.',
	'Dinosaur fossils have been found on every continent, including Antarctica.',
	'T-Rex could eat up to 500 pounds of meat in a single bite.',
	'The Brachiosaurus could grow to be 85 feet long.',
	'Some hadrosaurs had over 1,000 teeth.',
	'The name "Tyrannosaurus Rex" means "tyrant lizard king".',
	'Dinosaurs first appeared during the Triassic period, about 230 million years ago.',
	'The Spinosaurus was likely the largest carnivorous dinosaur, bigger than T-Rex.',
	'Most dinosaurs were herbivores (plant-eaters).',
	'The Ankylosaurus had a club-like tail it used for defense.',
	'Dinosaur eggs have been found that are over 150 million years old.',
	'The Diplodocus had a tail that could crack like a whip.',
	'Birds are the only living descendants of dinosaurs.',
	'The Pachycephalosaurus used its thick skull dome to headbutt rivals.',
	'Some dinosaurs could run up to 40 miles per hour.',
	'The Giganotosaurus had a skull over 5 feet long.',
	'Dinosaurs dominated Earth for over 170 million years.',
	'The Therizinosaurus had claws up to 3 feet long.',
	'Mary Anning was one of the first professional fossil hunters in the 1800s.',
	'Some sauropods took over 100 years to reach full size.',
	'The Mosasaurus was a marine reptile, not a dinosaur.',
	'Dinosaur bones have been found with cancer tumors.',
	'The Parasaurolophus used its crest to make trumpet-like sounds.',
	'Some dinosaurs lived in herds for protection.',
	'The Compsognathus was one of the smallest dinosaurs, about the size of a chicken.',
	'T-Rex had tiny arms but they could still lift 430 pounds.',
	'The Quetzalcoatlus had a wingspan of up to 36 feet.',
	'Dinosaurs likely had different colored skin and feathers.',
	'The Iguanodon was the second dinosaur to be formally named.',
	'Some dinosaurs may have been warm-blooded.',
	'The Allosaurus was one of the top predators of the Jurassic period.',
	'Dinosaur teeth could regrow, with some replacing thousands over a lifetime.',
	'The Carnotaurus had tiny arms that were even smaller than T-Rex\'s.',
	'The Dreadnoughtus was one of the largest dinosaurs ever, weighing 65 tons.',
	'Some dinosaur footprints have been preserved for millions of years.',
	'The Oviraptor\'s name means "egg thief" but it was likely a caring parent.',
	'The Megalodon shark lived after the dinosaurs but was not a dinosaur.',
	'Ammonites were common sea creatures during the age of dinosaurs.',
	'The Jurassic Park raptors were actually modeled after Deinonychus.',
	'Some dinosaurs had hollow bones, making them lighter.',
	'The Edmontosaurus had a duck-like bill.',
	'Dinosaurs went extinct about 66 million years ago.',
	'The first complete dinosaur skeleton found was a Hadrosaurus in 1858.',
	'Some theropod dinosaurs had feathered tails.',
	'The Mamenchisaurus had the longest neck of any dinosaur at 35 feet.',
	'Dinosaur Provincial Park in Canada has over 40 dinosaur species.',
	'The T-Rex had excellent binocular vision.',
	'Some pterosaurs were as small as sparrows.',
	'The Plesiosaur was a marine reptile with a very long neck.',
	'Dinosaur skin impressions show they had scales and sometimes feathers.',
	'The Archaeopteryx is considered the first bird-like dinosaur.',
	'Some dinosaurs migrated seasonally.',
	'The Styracosaurus had six long horns on its frill.',
	'The Cretaceous period ended with a mass extinction event.',
	'Dinosaur coprolites (fossilized poop) tell us what they ate.',
	'The Gallimimus could run at speeds up to 40 mph.',
	'Some sauropod dinosaurs laid eggs the size of footballs.',
	'The Dilophosaurus didn\'t actually spit venom - that was made up for Jurassic Park.',
	'Dinosaurs evolved from reptiles called archosaurs.',
	'The Utahraptor was much larger than Velociraptor at 20 feet long.',
	'Some dinosaurs had crests for display and communication.',
	'The Hell Creek Formation is one of the best places to find dinosaur fossils.',
	'Dinosaur teeth are the most commonly found fossils.',
	'The Majungasaurus was a cannibal, eating its own species.',
	'Some dinosaurs had air sacs in their bones like modern birds.',
	'The Nigersaurus had over 500 teeth in rows.',
	'Dinosaurs likely communicated through sounds, displays, and colors.',
	'The Baryonyx had a crocodile-like snout and ate fish.',
	'Sue the T-Rex is the most complete T-Rex skeleton ever found.',
	'Some dinosaurs had armor plating for protection.',
	'The Dimetrodon is often mistaken for a dinosaur but lived 40 million years earlier.',
	'Dinosaurs laid eggs in nests, and some may have sat on them.',
	'The Ceratosaurus had a horn on its nose.',
	'Some dinosaur embryos have been found preserved in eggs.',
	'The Morrison Formation in North America is rich in Jurassic dinosaur fossils.',
	'Dinosaurs had different types of hips: lizard-hipped and bird-hipped.',
	'The Irritator was named because scientists were irritated by its damaged skull.',
	'Some dinosaurs lived to be over 100 years old.',
	'The Protoceratops was likely preyed upon by Velociraptors.',
	'Dinosaur trackways show they walked upright.',
	'The Citipati was found fossilized while brooding its eggs.',
	'Some dinosaurs had binocular vision for hunting.',
	'The last non-avian dinosaurs died at the end of the Cretaceous.',
	'Dinosaur fossils were once thought to be dragon bones.',
	'The Supersaurus could grow up to 110 feet long.',
	'Some baby dinosaurs had proportionally larger eyes than adults.',
	'The study of dinosaurs is called paleontology.',
	'The Apatosaurus was once called Brontosaurus due to a naming mix-up.',
	'Dinosaur blood vessels and soft tissue have been found in some fossils.',
	'The Kentrosaurus had spikes running down its back and tail.',
	'Some dinosaurs had thumb spikes they used for defense.',
	'The Carcharodontosaurus had teeth like a great white shark.',
	'Dinosaurs breathed using a system similar to modern birds.',
	'The Sinosauropteryx was the first dinosaur proven to have feathers.',
	'Ankylosaur tail clubs could shatter bone on impact.',
	'The Acrocanthosaurus had a ridge of tall spines along its back.',
	'Some dinosaur nests have been found with dozens of eggs.',
	'The Suchomimus had a crocodile-like snout for catching fish.',
	'Dinosaurs ranged in size from a hummingbird to a blue whale.',
	'The Coelophysis was one of the earliest dinosaurs.',
	'Some theropods had bony crests on their heads for display.',
	'The Titanosaur could weigh as much as a dozen elephants.',
	'Pachyrhinosaurus had a massive bony boss instead of a nose horn.',
	'The first dinosaur bone was described in 1676 but thought to be a giant human.',
	'Dinosaurs evolved to become smaller as they became birds.',
	'The Spinosaurus could swim and likely spent time in water.',
	'Some ornithopods walked on two legs as juveniles and four as adults.',
	'The Euoplocephalus had bony armor even on its eyelids.',
	'Dinosaurs existed during the Mesozoic Era, also called the Age of Reptiles.',
	'The Herrerasaurus was one of the earliest known dinosaurs.',
	'Some dinosaur eggs were round while others were elongated.',
	'The Ornithomimus looked like an ostrich and could run very fast.',
	'Dinosaurs had a four-chambered heart like birds and mammals.',
	'The Plateosaurus was one of the first large dinosaurs.',
	'Some predatory dinosaurs hunted in packs.',
	'The Massospondylus could walk on two or four legs.',
	'Dinosaur fossils have been found in deserts, mountains, and even underwater.',
	'The Concavenator had a strange hump on its back.',
	'Some baby dinosaurs left the nest shortly after hatching.',
	'The Gigantoraptor was an 8-meter tall bird-like dinosaur.',
	'Dinosaurs could get infections that left marks on their bones.',
	'The Sauropelta had large shoulder spikes for defense.',
	'Some dinosaurs had grinding teeth for eating tough plants.',
	'The Albertosaurus was a smaller cousin of T-Rex.',
	'Dinosaur feathers may have been used for warmth, display, or flight.',
	'The Torvosaurus was one of the largest Jurassic predators.',
	'Some hadrosaurs had elaborate head crests for making sounds.',
	'The Nothosaurus was a marine reptile with paddle-like limbs.',
	'Dinosaurs grew faster than modern reptiles.',
	'The Dracorex has a skull that looks like a dragon.',
	'Some plant-eating dinosaurs had cheeks to hold food while chewing.',
	'The Megaraptor had huge claws on its hands.',
	'Dinosaurs went through growth spurts as teenagers.',
	'The Sinraptor was a medium-sized Asian predator.',
	'Some dinosaurs had specialized teeth for different types of food.',
	'The Psittacosaurus had a beak like a parrot.',
	'Dinosaur bones can be distinguished by their honeycomb-like internal structure.',
	'The Shantungosaurus was one of the largest hadrosaurs at 50 feet.',
	'Some dinosaurs had false eyes on their frills to confuse predators.',
	'The Tarbosaurus was the Asian equivalent of T-Rex.',
	'Dinosaurs could suffer from arthritis.',
	'The Microvenator was a small, fast-running dinosaur.',
	'Some sauropods could rear up on their hind legs to reach high branches.',
	'The Cryolophosaurus was discovered in Antarctica.',
	'Dinosaurs shed their skin like modern reptiles.',
	'The Mapusaurus hunted in groups to take down giant sauropods.',
	'Some dinosaur species are known from only a single bone.',
	'The Liopleurodon was a massive marine reptile with huge jaws.',
	'Dinosaurs had excellent senses of smell and hearing.',
	'The Gasparinisaura was a small ornithopod from South America.',
	'Some dinosaurs had specialized stomach stones called gastroliths.',
	'The Einiosaurus had a curved forward-pointing nose horn.',
	'Dinosaur populations fluctuated due to climate changes.',
	'The Bambiraptor was named after the Disney character.',
	'Some dinosaurs could change color for camouflage.',
	'The Zuniceratops was an early horned dinosaur from New Mexico.',
	'Dinosaurs had different growth rates depending on species.',
	'The Yangchuanosaurus was a top predator in Jurassic China.',
	'Some theropods had venomous bites, according to some researchers.',
	'The Stygimoloch had a dome head covered in spikes.',
	'Dinosaurs could get bone cancer.',
	'The Efraasia was one of the earliest prosauropods.',
	'Some dinosaurs lived in polar regions with months of darkness.',
	'The Borealopelta is the best-preserved armored dinosaur ever found.',
	'Dinosaurs left behind trace fossils like footprints and bite marks.',
	'The Camarasaurus was one of the most common Jurassic sauropods.',
	'Some baby dinosaurs were born with teeth ready to eat.',
	'The Guanlong was an early tyrannosauroid with a crest.',
	'Dinosaurs could survive major injuries that would kill modern animals.',
	'The Huayangosaurus was an early relative of Stegosaurus.',
	'Some dinosaurs had serrated teeth like steak knives.',
	'The Sauroposeidon had one of the longest necks of any dinosaur.',
	'Dinosaurs reproduced by laying eggs, not giving live birth.',
	'The Nodosaurus had bony plates but no tail club.',
	'Some dinosaur fossils still contain original proteins.',
	'The Corythosaurus had a helmet-like crest on its head.',
	'Dinosaurs could have had complex social behaviors.',
	'The Lexovisaurus was a European stegosaur.',
	'Some carnivorous dinosaurs scavenged as well as hunted.',
	'The Muttaburrasaurus was discovered in Australia.',
	'Dinosaurs evolved over millions of years into many specialized forms.',
	'The Wuerhosaurus was one of the last stegosaurs.',
	'Some dinosaurs had specialized beaks for cracking seeds or shellfish.',
	'The Oryctodromeus lived in burrows underground.',
	'Dinosaurs left behind coprolites that contained bones, scales, and plants.',
	'The Zhenyuanlong had large wings covered in feathers.',
}
