local FunFact = FunFact
local module = FunFact:NewModule('FactList_Dogs')
module.desciption = 'Mans best friend'

module.Facts = {
	"Puppies love games such as hide and seek! Hide, then call your pup's name so she can try to find you.",
	'Dogs can learn more than 1000 words.',
	'Big happy "helicopter" tail wagging is one sign of a really nice dog',
	'Upright, stiff, rapid tail movement is not wagging or "friendly" but indicates a dog who\'s rather excited and focused.',
	'Puppies grow to half their body weight in the first four to five months!',
	'Puppies then take a year or more to gain the other half of their body weight.',
	'Puppies can sleep 18 to 20 hours a day during that rapid body growth phase.',
	'Dogs sometimes appear to smile -- much like humans -- with open mouth grinning. This may indicate a relaxed, submissive state.',
	'Tired puppies get cranky just like little kids. If you have a fussy puppy, try nap time.',
	'The fastest breed, the Greyhound, can run up to 44 miles per hour.',
	'Perky-eared dogs hear sounds better than floppy-eared dogs.',
	'There are about 400 million dogs in the world.',
	'The Labrador Retriever is the most popular breed, according to the American Kennel Club.',
	'There are hundreds of breeds of dogs.',
	'The average dog lives 10 to 14 years.',
	'In general, smaller breeds live longer than larger breeds.',
	"The world's oldest breed, the Saluki, originated in Egypt around 329 B.C.",
	'According to a study shared by Cornell University, dogs were domesticated between 9,000 and 34,000 years ago.',
	'Thomas Jefferson helped enact a dog tax in Virginia, because he was annoyed that dogs were killing his sheep.',
	'Stroking dogs and gazing into their eyes releases the "feel good" hormone oxytocin for both people and dogs.',
	'Dogs are omnivores -- they eat meat, grains and vegetables.',
	'The heaviest breed, the Mastiff, weighs about 200 pounds.',
	'More than half of all U.S. presidents have owned dogs.',
	'President Calvin Coolidge owned at least a dozen dogs.',
	"Just like human fingerprints, no two dogs' nose prints are alike.",
	'At about 6 inches, the Chihuahua is the shortest breed.',
	'Irish Wolfhounds, the tallest breed, are 30 to 35 inches tall.',
	'A Russian dog named Laika was the first animal in space, traveling around Earth in 1957.',
	'Dogs who bark the most: Miniature Schnauzers, Cairn Terriers, Yorkshire Terriers, Fox Terriers and West Highland White Terriers.',
	'Puppies have 28 teeth and adult dogs have 42.',
	'The best age to bring a puppy home is 8 to 12 weeks.',
	'Dogs can see best at dawn and dusk.',
	"Dogs aren't colorblind but their eyes don't have receptors for red. They see in shades of black and white and also in shades of blue and yellow.",
	'New puppies have heat sensors in their noses to help find their moms while their eyes and ears are closed.',
	"A dog's sense of smell is reduced by up to 40 percent when he's overheated and panting.",
	'Highly trainable dog breeds like Golden Retrievers, Labrador Retrievers, German Shepherds and Collies are more kid-friendly than some other breeds.',
	'Bichons, Portuguese Water Dogs, Kerry Blue Terriers, Maltese and Poodles are all good choices if you have allergies since they shed less than other breeds.',
	'More than one in three U.S. families owns a dog.',
	'The average number of puppies in a litter is four to six.',
	'There are nearly 14,000 animal shelters and rescue groups across North America.',
	'Service dogs are recognized in the U.S. as "necessary medical equipment."',
	'Therapy dogs, who bring healing to individuals and families by visiting hospitals,',
	'schools or retirement homes, differ from service dogs, who assist individuals who have disabilities.',
	'The Newfoundland has a water-resistant coat and webbed feet.',
	"As Disney's Cruella De Vil was aware, Dalmatian puppies are born pure white and develop spots as they grow older.",
	'Dogs sweat through the pads of their feet.',
	'Dogs have three eyelids, including one to keep their eyes moist and protected.',
	'Chow Chows are born with pink tongues, which turn blue-black at 8 to 10 weeks.',
	"Dogs are pack animals -- they don't enjoy being alone.",
	'In ancient China, people kept warm by putting dogs up their sleeves.',
	'Dogs who have been spayed or neutered live longer than intact dogs.',
	'A bloodhound named Tigger holds the record for the longest ears, each measuring more than 13 inches.',
	'Bingo is the name of the dog on the box of Cracker Jacks.',
	'In 1969, Lassie was the first animal inducted into the Animal Hall of Fame.',
	'The Alaskan Malamute can withstand temperatures as low as 70 degrees below zero.',
	'Petting a dog can lower your blood pressure.',
	'Stray dogs in Moscow have learned to ride the subway to find food.',
	'Over half of dog owners include their dogs in annual holiday photos.',
	"Although it was once illegal to keep dogs as pets in Iceland's capital city, the laws have been relaxed.",
	"President Lyndon Johnson's beagles were named Him and Her.",
	'One unspayed female dog, her mate and their puppies can produce 67,000 puppies in six years.',
	'The Basenji is the only barkless dog.',
	'Dogs are direct descendants of wolves.',
	'Puppies are blind, deaf and toothless when born.',
	'Dogs curl up to keep themselves warm and protect vital organs.',
	"A dog's sense of smell is 10,000 times stronger than a human's.",
	'The Norwegian Lundehund is the only dog with six toes on each foot.',
	'Dogs can get jealous when their humans display affection toward someone or something else.',
	'Dogs can be trained to detect cancer and other diseases in humans.',
	"A dog's whiskers are used as sensing devices.",
	'Three of the 12 dogs on the Titanic survived.',
	'Your pup reaches his full size between 12 and 24 months.',
	'The U.S. has the highest dog population in the world.',
	'Rin Tin Tin was the first Hollywood dog star.',
	"A dog's average body temperature is 38.4 degrees.",
	'Many foot disorders in dogs are caused by long toenails.',
	'The Boy Scouts and Girl Scouts both offer merit badges in dog care.',
	'The Berger Picard, Miniature American Shepherd and Lagotto Romagnolo are the newest dog breeds recognized by the American Kennel Club in 2015.',
	'Paul McCartney of the Beatles recorded a high pitched whistle at the end of "A Day in the Life" for his dog.',
	'Max, Jake, Maggie and Molly are the most popular dog names.',
	"Spiked dog collars were used to protect dogs' throats from wolf attacks in ancient Greece.",
	'Walt Disney\'s family dog -- named Sunnee -- was the inspiration behind "Lady and the Tramp."',
	'Teams of dogs compete for the fastest time without errors in Flyball races.',
	'A German Shepherd named Orient accompanied her blind owner Bill Irwin as he became the first blind person to through-hike the 2,100-mile Appalachian Trail in 1990.',
	'Chihuahuas are born with soft spots in their skulls, just like human babies.',
	'Mastiffs wore armor and were sent after mounted knights in Roman times.',
	"National Geographic's Dr. Brady Barr measured a dog's average bite force at 320 pounds of pressure per square inch.",
	'Dogs are mentioned in the Bible more than 35 times.',
	'Obesity is the top health problem among dogs.',
	'Dachshunds were originally bred to fight badgers.',
	"President Theodore Roosevelt's Bull Terrier Pete ripped the pants off French Ambassador Jules Jusserand.",
	"The Border Collie, Poodle and Golden Retriever are considered the world's smartest dog breeds.",
	'Smaller breeds of dogs mature faster than larger breeds.',
	"Dogs have twice as many muscles to move their ears as humans, if you're looking for unusual facts about dogs!",
	'Female dogs carry puppies for about nine weeks before birth.',
	'Dogs are naturally submissive to any creature with a higher pack status.',
	'The Chihuahua was named for the state in northwestern Mexico where they were discovered.',
	'Dogs can be taught to count and solve simple math problems.',
	'With love and a little patience, dogs can learn to walk backwards, salute and bow.',
	'Pit bulls have been given a bad rap. BADRAP was started in the San Francisco Bay area on behalf of "pit bulls and their people" and was ranked nationally as a No. 1 high-impact nonprofit for animal welfare.',
	'Revolutionary War soldiers sometimes brought their dogs with them into battle. Such was the case with George Washington and his dog, Sweetlips.',
	'The American Water Spaniel was the first hunting breed developed to retrieve from boats.',
	'There are hundreds of different breeds of dogs, and around 400 million dogs in the world.',
	'The most popular breed of dog is the Labrador, with their gentle nature, intelligence andobedience they make for excellent pets and reliable workers. They often work as guide dogs.',
	'Dogs have much better smell than humans, and can detect different odors nearly 100 million times lower than humans can.',
	'Dogs hearing is also much better, and they can hear sounds four times further away than humans.',
	'An average dog will live to between 10 and 14 years of age.',
	'Dogs are omnivores, which means they feed on a wide variety of foods including meat, vegetables and grains.',
	'There are 18 different muscles that dogs use to move each one of their ears.',
	'Dogs release sweat through the pads of their feet.',
	'Apart from barking, growling and whining, dogs use their ears and facial expression to communicate what they are feeling.',
	'Puppies are born blind, without teeth and the ability to hear. Their eyes only open at around 10 to 14 days old, and their hearing will start after this. Their teeth start coming through at 6 weeks.',
	"During the first week of a dog's life, 90% of their time is spent sleeping, and 10% is spent eating.",
	'Puppies are considered adults when they are one year old.',
	'The domestic dog is a descendant of the grey wolf, in a process that took around 100,000years.',
	"The nickname “man's best friend” is believed to have come from a courtroom speech in Missouri America in 1870 where a farmer was suing his neighbor who shot his dog.",
	'The very first animal to go into space was a dog, a Russian dog named Laika who travelled in the spacecraft Sputnik around the earth in 1957.',
	"To many dogs showing a smile (baring your teeth) is an act of aggression. Most dogs don't smile with their mouths like people do, but show happiness and excitement by wagging their tails.",
	"Small dogs are often called toy dogs, or lap dogs - because they're so small they look like a toy, or can easily fit on your lap.",
	"There is a hunting dog that comes from Africa that cannot bark, it is the only dog likethis and the sound is makes is commonly known as 'barroo'.",
	"The largest breed of dog in the world is the Irish Wolfhound, and the smallest dog breedis the Chihuahua. St. Bernard's are the heaviest breed of dogs.",
	'The fastest dog on earth can reach speeds of 45 miles an hour, and is the Greyhound.',
	'The oldest dog who ever lived was a cattle dog from Australia called Bluey who lived tobe 29 years and 5 months old. In human terms that makes him over 160 years old!',
	'Dogs cannot eat raisins, grapes, onion, chocolate or garlic because it makes them very sick.',
	"The first thing you should teach your dog is how to 'sit'.",
	'When your dog goes to sleep you notice he turns in a circle a few times, this is an instinct from when they were a wild dog, as they did this to pat down the grass before they slept. Despite thousands of years, they still have this instinct.',
	"If your puppy takes something you don't want them to have, don't chase them. Instead make it a game where they chase you (and you run away) and you'll have the item back in no time.",
	'Dogs see much better than humans at night because they have a special light reflecting layer behind their eyes.',
	'Dogs hearts beat much faster than ours, between 10-120 beats a minute while humans are 70-80.',
	'The world record for the heaviest dog ever recorded was set in 1989, an Old English Mastiff that weighed 343 pounds and was 8 feet 3 inches long.',
	"The rock star Ozzy Osborne rescued his wife's Pomeranian from a coyote by wrestling thecoyote until it released the dog.",
	'The most dogs ever owned by a single person was 5,000 Mastiffs which were owned by KublaKhan.',
	'The weirdest law about dogs is that in Paulding, Ohio police officers are allowed to bite a dog to get it to be quiet.',
	'In Iran, it is against the law to own a dog as a pet, you need to be able to prove theyare a guard or hunting dog.',
	'There are cave paintings of dogs in Spain in Europe that are over 12,000 years old.',
	'Even the presidents love their dogs, and President Franklin Roosevelt sent a destroyer to the Aleutian Islands just to get his dog Fala, who had been left behind.',
	"A dog's nose print is unique, and similar to human fingerprints that no two are the same.",
	'Bloodhound dogs have the best sense of smell of all dogs, and have been used to track down criminals since the middle ages.',
	'The Beagle and the Border Collie are the dogs that bark the most.',
	'A survey found that 33% of dog owners talk to their dogs on the phone when they are away, or leave messages on the answering machine.',
}
