local FunFact = FunFact
local module = FunFact:NewModule('FactList_Flags')
module.desciption = 'Fun with Flags, sheldon cooper would be proud.'

module.Facts = {
	'Lichtenstein and Haiti had the same flag and only found out at the 1936 Olympics.',
	"Nepal has the only flag in the world that doesn't have 4 sides.",
	'There are only two square shaped flags in the world',
	'Symbols used on flags normally have a specific meaning',
	'Japan is known as the “Land of the rising sun”, and therefore they have a circular shape in the middle of their flag which represents the sun.',
	'The Cross - This appears on many flags and often links back to religion, to represent Christianity',
	'Some countries will use their national bird on their flags to reflect the countries heritage, like the flag of Ecuador which has a bird of the Andes called a Condor.',
	'The colors used for national flags often ties into the history of the country.',
	'Purple is the rarest color to be used on a flag.',
	'The flag of Belize has the most colors of any flag in the world. (12)',
	'Denmark has the oldest flag in the world. First used in 1625 and is still the same today. The design itself however was created in 1219.',
	'South Sudan has the newest flag in the world it was adopted on July 9, 2010.',
	'There are 4 national flags in the world that feature firearms.',
	'Many will have items such as axes, arrows, cannons, swords, daggers, shields, spears, etc. in their emblems or crests, but only 4 have firearms.',
	'There have been 27 versions of the American Flag.',
	'The US Flag designer 17-year-old, Robert G. Heft, of Lancaster, Ohio who submitted the design in a contest in 1958. It was chosen out of over 1,500 submissions by President Dwight Eisenhower.',
	"Mozambique's flag includes an image of an AK-47, symbolizing defense and vigilance.",
	'Switzerland and Vatican City are the only two countries with square-shaped flags.',
	"The flag of Nepal is the world's only non-quadrilateral national flag, shaped like two stacked triangles.",
	'The Union Jack of the United Kingdom is a combination of the flags of England, Scotland, and Northern Ireland.',
	"Bhutan's flag features a dragon to symbolize the protection of the country.",
	"The flag of Albania features a double-headed eagle, reflecting the country's Roman heritage.",
	"Indonesia's flag is nearly identical to Monaco's, with only a slight difference in the dimensions.",
	'The flag of the Philippines has a unique feature: it is flown with the red stripe up in times of war and blue stripe up in times of peace.',
	'The flag of South Africa was designed to signify the convergence of different cultures and is one of the most colorful flags.',
	"The Olympic flag's rings represent the five inhabited continents of the world, interlaced to symbolize the universality of Olympism.",
	'The flag of Cyprus is the only national flag to feature a map of the country on it.',
	'The flag of Greece has nine horizontal stripes, representing the nine syllables of the phrase "Freedom or Death."',
	'The flag of Brazil features a celestial globe, representing the sky over Rio de Janeiro at the morning of November 15, 1889.',
	"The flag of Norway has one of the world's oldest flag designs still in use today, dating back to 1821.",
	'The flag of Canada is sometimes referred to as the "Maple Leaf flag" due to its prominent maple leaf symbol.',
	"Mexico's flag tells a story from an Aztec legend, featuring an eagle eating a snake.",
	'The rainbow flag, commonly associated with LGBTQ+ pride, was first flown in San Francisco in 1978.',
	'The flag of Papua New Guinea features the Raggiana bird-of-paradise, a national symbol.',
	'The Jolly Roger, traditionally black and white, is recognized as the flag of pirates.',
	"Kenya's flag includes a Maasai shield and two spears, symbolizing the defense of freedom.",
	'The white flag is universally recognized as a symbol of truce or surrender.',
	'The flag of Sri Lanka is one of the oldest in the world, with its lion symbol dating back to 486 BC.',
	'Qatar has the only national flag with a width more than twice its height.',
	'The flag of Kiribati features a frigatebird, symbolizing command of the sea.',
	"Wales' flag features a red dragon, a symbol of Welsh heritage and folklore.",
	'The flag of El Salvador includes the date that Central America gained independence from Spain: September 15, 1821.',
	'The flag of Libya was the only national flag in the world with just one color (green) until 2011.',
	"Argentina's flag is said to be inspired by the sky, with its blue stripes representing the sky and the white stripe a cloud.",
	'The flag of Iceland represents its nature: blue for the ocean, white for the snow, and red for the volcanic fire.',
	'The flag of the United States has been changed 27 times, the last being the addition of Hawaii in 1960.',
	'North Korea and South Korea have completely opposite flag designs, symbolizing their division.',
	'The flag of the Isle of Man is triskelion composed of three armored legs.',
	"Angola's flag features a gear, machete, and star, symbolizing workers, agriculture, and progress.",
	"Malawi's flag has a rising sun, symbolizing the dawn of hope and freedom for Africa.",
	'The flag of the United Arab Emirates was adopted on December 2, 1971, the same day the national federation was founded.',
	"The flag of Bhutan is one of the most intricately designed flags, featuring a dragon from the country's mythology.",
	'The flag of Estonia is known as the "sinimustvalge", representing the sky, soil, and commitment to freedom.',
	"The flag of Fiji includes the Union Jack and a shield from the country's coat of arms.",
	'The flag of Finland is called "Siniristilippu", meaning "blue cross flag".',
	'The flag of Cambodia features the Angkor Wat, symbolizing justice, heritage, and integrity.',
	"Iceland's flag represents the country's natural elements: red for volcanic fire, white for ice and snow, and blue for the Atlantic Ocean.",
	'The flag of Botswana symbolizes water, which is considered a precious resource, with light blue and black and white bands.',
	'The flag of Kazakhstan features a golden sun with 32 rays above a soaring golden steppe eagle, both central to Kazakh mythology.',
	"Portugal's flag features a unique shield and navigation tools representing its maritime history.",
	'The flag of Oman is one of the oldest in continuous use, dating back to the 18th century.',
	'The flag of Seychelles features a radiating color scheme to represent the vibrancy and diversity of the nation.',
	'The flag of Lesotho features a traditional Basotho hat, symbolizing the indigenous people.',
	'The flag of Vietnam has a large yellow star on a red background, representing the leadership of the Communist Party.',
	"The flag of Kuwait has a black trapezoid, symbolizing defeat of the country's enemies.",
	'The flag of Armenia features horizontal stripes with a unique color pattern that has influenced other flags in the region.',
	'The flag of the Marshall Islands represents the equator and a star for each district.',
	'The flag of the United Kingdom, known as the Union Jack, is an amalgamation of the flags of England, Scotland, and Ireland.',
	'The flag of Cuba was designed in 1849 and features a star called "La Estrella Solitaria" (The Lone Star).',
	"The flag of Greece's cross symbolizes Eastern Orthodox Christianity, the established religion of the Greek people.",
	"The flag of India was designed by Pingali Venkayya and features a spinning wheel in the center, symbolizing Gandhi's goal of making Indians self-reliant by fabricating their own clothing.",
	"The flag of Fiji includes an image of the British Union Jack, representing the country's colonial past.",
	"The flag of North Korea features a prominent red star, representing the country's commitment to communism.",
	'The flag of Belarus features a traditional pattern used in Belarusian rugs along the hoist.',
	'The flag of Australia features the Southern Cross constellation and the Commonwealth star.',
	'The flag of Uruguay has nine stripes representing the nine original departments of Uruguay.',
	'The flag of Monaco is identical to the flag of Indonesia, but with a slight difference in dimension and shade.',
	'The flag of Singapore features a crescent and five stars, symbolizing a young nation on the rise full of ideals and aspirations.',
	'The flag of Jamaica is one of only two current national flags that do not feature the colors red, white, or blue.',
	"The flag of Belgium's black, yellow, and red colors are taken from the coat of arms of the Duchy of Brabant.",
	"The flag of Finland's blue cross represents Christianity, while the white background symbolizes the country's snowy landscape.",
	'The flag of Argentina features a sun known as the Sun of May, which is a national emblem.',
	"The flag of Egypt's eagle of Saladin is a symbol of Arab nationalism.",
	'The flag of Iran features stylized Arabic script and a red tulip, symbolizing the martyrs.',
	"The flag of Tuvalu features nine stars, representing each of the country's islands.",
	"The flag of San Marino is one of the world's oldest and features the country's coat of arms.",
	'The flag of Guinea-Bissau features two black stars, symbolizing freedom and solidarity.',
	'The flag of Tonga is one of the oldest flags in the Pacific and includes a red cross on a white field, symbolizing Christianity.',
	"The flag of Andorra features a coat of arms that depicts the country's independence and history.",
	'The flag of the Dominican Republic features a cross, representing the Christian faith, and four rectangles in the corners, symbolizing liberty, democracy, progress, and protection.',
	'The flag of Chad and Romania are nearly identical, causing occasional confusion.',
	"The flag of Latvia features one of the world's oldest flag designs, dating back to a 13th-century battle.",
	'The flag of the Central African Republic features four horizontal stripes and one vertical stripe, symbolizing the geographical location and history of the country.',
	'The flag of Luxembourg has a color scheme similar to the Netherlands due to shared history, but with a lighter shade of blue.',
	"The flag of Eritrea features a wreath and an olive branch, symbolizing peace and the country's autonomy.",
	'The flag of South Korea, known as the Taegukgi, features a yin-yang symbol and four trigrams representing the principles of reality.',
	'The flag of Ethiopia has influenced the color scheme of many other African countries, known as Pan-African colors.',
	'The flag of Comoros features four stars and stripes representing the four islands of the nation.',
	'The flag of Qatar is maroon, a unique color among national flags, representing the bloodshed during its many wars.',
	'The flag of Mali is similar to the Guinea flag, with green, yellow, and red vertical stripes.',
	'The flag of New Zealand features four stars, representing the Southern Cross constellation.',
	"The flag of Barbados features a trident symbolizing the country's independence from Britain.",
	'The flag of Liberia reflects its history as a settlement for freed American slaves, similar to the U.S. flag.',
	'The flag of Myanmar features three horizontal stripes of yellow, green, and red with a large white star in the middle.',
	'The flag of Luxembourg is often confused with the Netherlands due to similar color schemes, but has lighter shades.',
	'The flag of Nigeria features vertical stripes of green representing agriculture, and white for peace.',
	'The flag of Trinidad and Tobago features a black diagonal stripe, symbolizing the dedication of its people.',
	'The flag of Austria has one of the oldest national flag designs in the world, dating back to the 13th century.',
	'The flag of Uruguay features the Sun of May, symbolizing independence and freedom.',
	'The flag of Mongolia includes the Soyombo symbol, which represents the freedom and independence of the Mongolian people.',
	'The flag of Bolivia features a coat of arms with Andean condor, symbolizing willingness to defend the country and its liberty.',
	'The flag of Haiti is one of the few national flags featuring images of weapons, reflecting its revolutionary history.',
	'The flag of Colombia features three horizontal stripes of yellow, blue, and red, representing gold, the ocean, and bloodshed for freedom.',
	'The flag of Ecuador shares the same color scheme as Colombia and Venezuela, as all were part of Gran Colombia.',
	'The flag of Chile features a star known as the "Star of Progress".',
	'The flag of Somalia features a white five-pointed star known as the Star of Unity, representing the Somali race.',
	'The flag of the Netherlands was originally orange-white-blue but later changed to the current red-white-blue.',
	'The flag of Uzbekistan features a crescent moon and twelve stars, symbolizing the history and future of the country.',
	'The flag of Vanuatu has a Y-shaped pattern symbolizing the geographical layout of the islands.',
	'The flag of Georgia features four small and one big red cross, known as the "five-cross flag".',
	'The flag of Azerbaijan includes a crescent and eight-pointed star, symbolizing the Islamic heritage.',
	'The flag of Micronesia consists of four white stars on a blue background, symbolizing the states of the federation.',
	'The flag of Moldova includes the national coat of arms, featuring an eagle holding a cross, an olive branch, and a scepter.',
	'The flag of Bulgaria consists of three horizontal stripes of white, green, and red, symbolizing peace, hope, and valor.',
	"The flag of Kazakhstan features a golden eagle and a sun on a sky-blue background, representing the country's aspirations.",
	'The flag of Kyrgyzstan features a sun with 40 rays, representing the 40 Kyrgyz tribes.',
	'The flag of Tajikistan includes a crown and seven stars, symbolizing unity, the sun, and happiness.',
	'The flag of Turkmenistan is one of the most detailed national flags, featuring traditional carpet patterns.',
	'The flag of Ukraine features two simple colors: blue and yellow, symbolizing the sky and wheat fields.',
	'The flag of Benin features green for hope, yellow for preservation, and red for courage.',
	'The flag of Burkina Faso includes a red and green half with a yellow star, symbolizing the revolution.',
	'The flag of Cape Verde features ten stars, representing the islands of the nation.',
	'The flag of Djibouti features a triangle and two horizontal bands, symbolizing the past and future.',
	"The flag of Equatorial Guinea includes a silk cotton tree, symbolizing the link to the country's history.",
	'The flag of Gabon features three horizontal stripes of green, yellow, and blue, representing the equator, the sun, and the sea.',
	"The flag of Guinea features three vertical stripes of red, yellow, and green, symbolizing the people, the sun, and the country's vegetation.",
	'The flag of Spain includes the coat of arms, which features the Pillars of Hercules, symbolizing the imperial history of Spain.',
	'The "Dannebrog" of Denmark is claimed to be the oldest continuously used national flag, originating from a 13th-century battle.',
	'The flag of Vietnam was used by the Viet Minh, a communist-led organization that fought for Vietnamese independence during the First Indochina War.',
	'The flag of the United States, with its 13 stripes, represents the original 13 colonies that declared independence from Britain.',
	"The flag of France's tricolor was adopted after the French Revolution, symbolizing liberty, equality, and fraternity.",
	'The flag of Greece was adopted after the Greek War of Independence against the Ottoman Empire.',
	'The flag of the United Kingdom, the Union Jack, includes the cross of St. George (patron saint of England), who was a prominent figure in the Crusades.',
	'The flag of Russia was inspired by the Dutch flag and was brought to Russia by Tsar Peter the Great after the Great Northern War.',
	'The flag of Japan, known as the Nisshōki, symbolizes the sun and was influential during the Meiji Restoration and subsequent military actions.',
	'The flag of Argentina was created by Manuel Belgrano during the Argentine War of Independence.',
	'The flag of the Confederate States of America during the American Civil War featured stars representing the seceded states.',
	'The flag of South Korea was adopted post-Korean War, featuring the yin-yang symbol and four trigrams from traditional Korean philosophy.',
	'The flag of Pakistan was adopted during the partition of India, symbolizing the Muslim majority.',
	"The flag of Israel, adopted shortly after the country's establishment in 1948, features the Star of David, an ancient Jewish symbol.",
	"The flag of Angola features a part of a cog wheel and a machete, symbolizing industrial and agricultural workers and the nation's revolutionary history.",
	'The flag of Mozambique includes an AK-47 with a bayonet attached to it, representing defense and vigilance, a reference to the countrys struggle for independence.',
	'The flag of Iraq has three stars representing the three foundational principles of the 1958 revolution: unity, freedom, and socialism.',
	"The flag of Sri Lanka was adopted in 1948 but was modified in 1951 to represent the country's minorities, following independence from British rule.",
	'The flag of Lebanon features the Cedar Tree, a symbol of holiness, eternity, and peace, which is referenced in many ancient texts including the Bible.',
	'The flag of Norway features a Nordic cross, symbolizing the countrys former union with Sweden and its history as a maritime nation.',
	"The flag of Egypt's eagle of Saladin symbolizes Arab nationalism and independence and has been used since the revolution of 1952.",
	"The flag of Ethiopia's colors inspired the Rastafarian movement, which regards Ethiopia as its spiritual homeland, stemming from the reign of Haile Selassie.",
	'The flag of Albania features a double-headed eagle, a symbol tracing back to the Byzantine Empire and representing the sovereignty of the state.',
	'The flag of the United States features 50 stars, each one representing a state, many of which have their own unique battle flags from the Civil War era.',
	'The flag of Turkey features a star and crescent which became associated with Islam and the Ottoman Empire after the fall of Constantinople.',
	'The flag of the Philippines was sewn in Hong Kong and first displayed in battle during the Philippine Revolution against Spain.',
	'The flag of Germany, adopted after World War I, represents German unity and freedom.',
	'The flag of Brazil was inspired by the celestial globe, representing the night sky over Rio de Janeiro on November 15, 1889, the day the Republic was declared.',
	'The flag of Belgium was influenced by the colors of the Brabant Revolution against the Austrian Netherlands.',
	'The flag of Cyprus, adopted in 1960, features an olive branch symbolizing peace between the Greek and Turkish communities.',
	'The flag of Australia features the Union Jack, representing its history as a British colony and its allegiance to the British Crown.',
	"The flag of Canada's maple leaf symbolizes peace and tolerance, reflecting the country's values established post-World War I.",
	"The flag of Chile was adopted after the country's victory in the War of Independence against Spain.",
	"The flag of Cambodia features the Angkor Wat, a symbol of the country's heritage and the enduring strength of its people.",
	'The flag of Kenya features a Maasai shield and spears, representing the defense of freedom, including the Mau Mau uprising against British colonial rule.',
	'The flag of Libya has been through several iterations, with the current design reflecting the 2011 revolution.',
	'The flag of Mongolia includes the Soyombo symbol, which represents freedom and independence, a significant symbol during the 1911 revolution against Qing China.',
	'The flag of Peru features colors that were chosen by General José de San Martín, inspired by a flock of flamingos.',
	"The flag of Romania's colors were chosen for their symbolism and connection to the 1848 Revolution, representing fraternity, justice, and liberty.",
	'The flag of El Salvador features five flags to represent the Federal Republic of Central America, a union of states in the early 19th century.',
}
