local FunFact = FunFact
local module = FunFact:NewModule('FactList_Food')
module.desciption = "That stuff most people sutff shove in their pie hole. We aren't going to talk about what karen does."

module.Facts = {
	'A survey showed 29% of adults say they have been splashed or scalded by hot drinks while dunking biscuits.',
	'Ortharexia Nervosa is an eating disorder where the sufferer is obsessed with eating healthy food.',
	"Ketchup was sold in the 1830's as medicine.",
	'Dry swallowing one teaspoon of sugar can commonly cure hic-ups.',
	'In Kentucky, it is illegal to carry an ice cream cone in your back pocket.',
	'The fear of cooking is known as Mageirocophobia and is a recognized phobia.',
	'The tea bag was introduced in 1908 by Thomas Sullivan of New York.',
	"The tall chef's hat is called a toque.",
	'Arachibutyrophobia is the fear of peanut butter sticking to the roof of the mouth.',
	'In South Africa, termites and ants are often roasted and eaten by the handful, like popcorn.',
	'Every time you lick a stamp, you consume 1/10 of a calorie.',
	'Pearls melt in vinegar.',
	"The '57' on the Heinz ketchup bottle represents the number of pickle types the company once had.",
	'Marmite was first introduced into the UK in 1902.',
	'The ancient Greeks chewed a gum-like substance called mastic that came from the bark of a tree.',
	'Honeybee workers must visit 2 million flowers to make one pound of honey.',
	'The fear of vegetables is called Lachanophobia.',
	'Almonds are a member of the peach family.',
	'If you boil beetroot in water, and then massage the water into your scalp each night, it works as an effective cure for dandruff.',
	'In the United States, lettuce is the second most popular fresh vegetable.',
	'Grape growing is the largest food industry in the world as there are more than 60 species and 8000 varieties of grapes.',
	'The average person eats eight pounds of grapes each year.',
	'There are more than 7,000 varieties of apples grown in the world.',
	"A cluster of bananas is formerly called a 'hand'. Along that theme, a single banana is called a 'finger'.",
	"Onion is Latin for 'large pearl'.",
	'Apples, pears, cherries and strawberries are all members of the rose family.',
	"The word vegetable has no scientific definition, so it's still acceptable to call a tomato a vegetable.",
	'In the Philippines, it is considered good luck if a coconut is cleanly split open without jagged edges.',
	'When cranberries are ripe, they bounce like a rubber ball.',
	'The highest number of grapes eaten in 3 minutes is 133. This record was set in 2001 by Mat Hand, from the UK.',
	'There are more than 10,000 varieties of tomatoes.',
	'In 2001, there were more than 300 banana-related accidents in Britain, most involving people slipping on skins.',
	'If you want to speed up the ripening of a pineapple, so that you can eat it faster, then you can do it by standing it upside down (on the leafy end).',
	'Carrots have zero fat content.',
	'Peanuts can be used to make dynamite.',
	'A watermelon is over 92% water by weight.',
	'Alliumphobia is the fear of garlic.',
	'A row of corn always has an even number.',
	'The pumpkin originated in Mexico about 9,000 years ago.',
	'Square watermelons sell for about $85.',
	'Turnips are high in fiber, Vitamin C, Calcium and Potassium.',
	'Eating a lot of beetroot turns your pee into a pink color.',
	'Biting a wooden spoon whilst chopping an onion will stop your eyes from watering.',
	'Each pineapple plant only produces just one pineapple per year.',
	'Lettuce is a member of the sunflower family.',
	'Blueberries are a good source of Vitamin C and fiber.',
	'Pumpkin flowers are edible.',
	'Peaches are the third most popular fruit grown in America.',
	'We are eating 900% more broccoli than we did 20 years ago.',
	'There are more than 600 pasta shapes produced worldwide.',
	'Geomelophagia is someone who has the urge to eat raw potatoes.',
	'9th August is officially National Rice Pudding Day.',
	'Rice can be used in beer, dog food, baby food, breakfast cereals, snacks, frozen foods and sauces!',
	'October is National Pasta Month.',
	"Canadian neurosurgeon Dr. Wilder Penfield, while operating on epilepsy patients, discovered the 'Toast Centre' of the human brain, which is wholly dedicated to detecting when toast is burning!",
	'16 billion jelly beans are made for Easter. Stacked end to end, the jelly beans would circle the globe nearly 3 times!',
	"Before 1991 Twix Bars were internationally known as 'Raider'.",
	'The Arabs invented caramel.',
	'Before Walkers owned Wotsits, they sold a rival known as Cheetos on the UK market.',
	'Pringles were first sold in America in 1968 but were not popular until the mid-1970s.',
	'Saddam Hussein liked Bounty Bars!',
	'Frank Mars invented the Snickers chocolate bar. He named it Snickers after his favorite horse.',
	"The M's in M & M's stand for 'Mars & Murrie', the co-creators of the candy.",
	'Twinkies originally had banana flavored filling, but switched to vanilla when World War 2 bought the banana trade to a halt.',
	"Cadbury's Cream Eggs first went on sale in 1971.",
	"In 2006, Shari's Berries pioneered the concept of delivering chocolate dipped fruits nationwide in freeze packs.",
	'The Kit Kat was originally made by Rowntree Limited, until 1988 when they were bought out by Nestle.',
	"Juicy Fruit and Wrigley's Spearmint gums are more than 100 years old!",
	'Hundreds and Thousands (Sprinkles, Nonpareils, Jimmies) are small round balls of brightly colored sugar used as decorations on cakes, cookies, trifles and other desserts. Their use dates back at least to the early 19th century.',
	'Gummy Bears are only 79 millimeters in length.',
	'Chocolate can kill dogs; it directly affects their heart and nervous system.',
	'Deep fried chocolate bars contain about 850 calories per bar.',
	"The world's oldest chocolates are 106 years old. A tin of chocolates from the coronation of King Edward VII from 1902.",
	'Yorkie Chocolate Bars are not for girls!',
	'Sugar is the only taste that humans are born craving.',
	'The Swiss eat the most chocolate, followed by the English.',
	'The Bourbon biscuit was introduced in 1910 originally under the name Creola.',
	'In 15th century France, chocolate could only be eaten by members of the royal court.',
	'Gorgonzola cheese dates back to the year 879!',
	'Many mass-produced ice creams have seaweed in them.',
	'Cheese products contain less than 51% cheese.',
	'Some yoghurt contain beef or pork gelatin.',
	'The weight of a Babybel is 21 grams.',
	'An average American will eat the equivalent of 28 pigs in their lifetime.',
	'National Pigs-in-a-Blanket Day is celebrated on 24th April every year.',
	'The first soup was made from hippopotamus and dates back to 6000 B.C.',
	'Baked beans are low in fat and have a lot of fiber and protein.',
	'Worcestershire sauce is made from dissolved fish.',
	'Pescetarians are vegetarians who eat fish.',
	'The largest item on any menu in the world is the roast camel.',
	'Egg yolks are one of the few foods that naturally contain Vitamin D.',
	'The average hot dog is consumed in 6 bites.',
	'Until well into the sixteenth century, bacon was a Middle English term used to refer to all pork in general.',
	'In America, anchovies always rank last on the list of favorite toppings.',
	'The average amount of meat eaten per person, per year is 78.5kg.',
	'French fries came from Belgium, but are most popular in the US.',
	'An average person will consume 12 pubic hairs in their fast food every year!',
	'KFC (Kentucky Fried Chicken) was founded by Colonel Harland Sanders in 1952.',
	'We eat 300 million portions of fish and chips in Britain each year.',
	'Chicken McNuggets contain beef additives.',
	'Chocolate was once used as currency.',
	'As early as 250 A.D., ancient civilizations of Mexico and South America, specifically The Mayans and the Aztecs, used the cocoa bean as a system of money.',
	"Baked Alaska isn't from Alaska ",
	"The actual origins are a mystery, but it's assumed it has to do with the icy center. ",
	"Arkansas' state beverage is milk",
	"Americans really loves milk. Arkansas considers cow's milk to be the official state drink, among 19 other states who also claim the beverage to be their own. ",
	"Artichokes were declared California's state vegetable under strange circumstances ",
	"The state's lieutenant governor declared the state's official vegetable, fruit, nut, and more while the state governor was away visiting China. If you get the power, we suppose you have to use it somehow. ",
	'Connecticut is known as the Nutmeg State',
	'Though not an official nickname, the state is called the Nutmeg State after colonials carved fake nutmeg out of oak and sold it as the rare and expensive spice. ',
	"Delaware's state herb is the sweet goldenrod ",
	"We figured if a state was going to declare an herb it's official one, it would be something we were familiar with. Sweet goldenrod was established as the official state herb in 1996",
	"Florida's state beverage is orange juice",
	'Everyone knows Florida is the state for oranges, but who knew they had declared oranges both their state fruit and state beverage? ',
	"Georgia loves their state crop so much, there's a monument",
	"And we're not talking peaches. Georgia's official state crop is the peanut, and the state loves it so much they erected the world's largest peanut, opened a peanut museum, and operate the world's largest peanut shelling plant. ",
	'Idaho potatoes are the official state food and state vegetable',
	'The state declared the famous Idaho potato to hold both titles. ',
	"Illinois' state snack food is popcorn ",
	"The state declared popcorn the official state snack food even though Indiana boasts producing 20% of the country's popcorn supply. ",
	'Iowa has a massive state food-focused fair ',
	'Every year the Iowa State Fair rolls around as the largest state event in Iowa and one of the oldest and largest agricultural and industrial expositions in the country. If you find yourself in Iowa early August, check out the nearly 200 food stands and 70 treats sold on a stick. ',
	"Kentucky's state soft drink is Ale-8-One",
	"The Kentucky born soda still thrives today as the state's official soft drink. You can toss it into tons of recipes, and even purchase apparel with the logo.",
}
