local FunFact = FunFact
local module = FunFact:NewModule('FactList_Movies')
module.desciption = 'Facts about movies and the film industry.'
module.displayname = 'Movies'

module.Facts = {
	'The first feature-length film was "The Story of the Kelly Gang" (1906) from Australia.',
	'The Wilhelm Scream has been used in over 400 films and TV shows.',
	'The Lion King was originally titled "King of the Jungle" despite lions not living in jungles.',
	"The carpet in The Shining is the same pattern as the carpet in Toy Story's Sid's house.",
	'The word "mafia" is never spoken in The Godfather.',
	'All of the clocks in Pulp Fiction are set to 4:20.',
	'Toy Story was the first fully computer-animated feature film.',
	'The Wizard of Oz was originally shot in black and white AND color.',
	'Sean Connery wore a toupee in every James Bond movie he appeared in.',
	'The iconic Jaws theme only uses two notes.',
	'E.T. and Poltergeist were originally going to be the same movie.',
	'During filming of The Godfather, a real horse head was used.',
	'The snow in the Wizard of Oz was made of 100% asbestos.',
	'Psycho was the first American film to show a toilet being flushed.',
	'The movie Titanic cost more to make than the actual Titanic ship.',
	'Steven Spielberg still earns 2.5% of Jurassic Park merchandise profits.',
	'The longest movie ever made is "Logistics" at 857 hours (35 days).',
	'Clint Eastwood was originally offered the role of Superman.',
	'The "I am your father" line in Star Wars was kept secret even from most of the cast.',
	"Alfred Hitchcock's Psycho was the first film to show a flushing toilet.",
	'James Cameron drew all the drawings in Titanic, including the famous nude sketch.',
	'The chariot scene in Ben-Hur took 5 weeks to film.',
	"MGM's lion has killed its trainer twice.",
	"The Exorcist set was kept refrigerated to capture the actors' breath on camera.",
	"The rain in Singin' in the Rain was mixed with milk so it would show up on camera.",
	'John Travolta turned down the lead role in Forrest Gump.',
	'Gone with the Wind was the first color film to win Best Picture.',
	'The word "squirrel" is used as a password because it\'s hard to pronounce for non-native English speakers.',
	'Shrek was originally planned to be voiced by Chris Farley before his death.',
	'The mask in Halloween was a modified William Shatner mask painted white.',
	'Fight Club and Choke were both based on books by Chuck Palahniuk.',
	"The Titanic's ending was kept secret so well that Kate Winslet didn't know until she saw the film.",
	'The Great Gatsby holds the record for most champagne used in a single movie.',
	'Rocky was written by Sylvester Stallone in just three and a half days.',
	'The entire movie of 12 Angry Men takes place in one room.',
	'Tom Hanks was not paid for Forrest Gump - he took percentage points instead and earned $65 million.',
	"The Bridge on the River Kwai's bridge was actually blown up by mistake during filming.",
	'In The Matrix, the green code is actually sushi recipes.',
	"Disney's Tangled cost $260 million, making it one of the most expensive films ever made.",
	'The Pirates of the Caribbean ride inspired the movies, not the other way around.',
	"Michael Myers' mask in Halloween cost only $2.",
	'The first movie kiss was in 1896 in "The Kiss" and lasted only 18 seconds.',
	'The Avengers (2012) was the first movie to gross over $200 million in its opening weekend.',
	'Heath Ledger improvised the hospital explosion scene in The Dark Knight.',
	"The snow in It's a Wonderful Life was made from firefighting foam.",
	'Star Wars was almost called "Adventures of Luke Starkiller, as Taken from the Journal of the Whills".',
	'Avatar held the record for highest-grossing film for nearly 10 years.',
	'The briefcase in Pulp Fiction originally contained diamonds, but was changed to a mysterious glow.',
	'Will Smith turned down the role of Neo in The Matrix.',
	'The first 3D movie was "The Power of Love" in 1922.',
	'Drew Barrymore was in E.T. at age 6 and believed the alien was real.',
	'Keanu Reeves gave his Matrix salary to the special effects crew.',
	"Back to the Future's DeLorean was originally going to be a refrigerator.",
	"The horse in The Godfather's famous bed scene had died from natural causes at a dog food factory.",
	'Samuel L. Jackson has a clause in his contracts that allows him to golf during production.',
	"Jurassic Park's velociraptors were actually based on deinonychus.",
	'The first Academy Awards ceremony lasted only 15 minutes.',
	'Indiana Jones was originally named Indiana Smith.',
	"Forrest Gump's bench scenes were filmed in Savannah, Georgia.",
	'The Shawshank Redemption was a box office failure but became one of the most beloved films ever.',
	"Christopher Nolan doesn't use a cell phone or email.",
	"The Breakfast Club's essay at the end was written by director John Hughes in one take.",
	'Jim Carrey was paid $7 million for his role in The Mask.',
	'The first movie with sound was "The Jazz Singer" in 1927.',
	'Iron Man was considered a risky bet by Marvel before it launched the MCU.',
	'The "Rosebud" sled in Citizen Kane sold for $60,500 at auction.',
	'Tom Cruise performed the cliff climbing in Mission: Impossible 2 without a stunt double.',
	'The Terminator was made with a budget of only $6.4 million.',
	'John Williams has been nominated for an Oscar 52 times.',
	'The Silence of the Lambs is one of only three films to win all five major Academy Awards.',
	'The birds in Alfred Hitchcock\'s "The Birds" were trained using food rewards.',
	'Viggo Mortensen broke two toes kicking the helmet in The Lord of the Rings: The Two Towers.',
	'The Prestige and The Illusionist were both released in 2006 and feature magicians.',
	'The famous shower scene in Psycho has 70 camera angles and 50 cuts.',
	'Harrison Ford was a carpenter before being cast in Star Wars.',
	'The shark in Jaws was nicknamed "Bruce" after Spielberg\'s lawyer.',
	'Every Pixar movie contains a reference to the Pizza Planet truck.',
	'The budget for Paranormal Activity was only $15,000.',
	'Gravity took 4.5 years to make due to its complex visual effects.',
	'The first color film was "A Visit to the Seaside" in 1908.',
	'Leonardo DiCaprio cut his hand during Django Unchained and kept acting.',
	'The voice of Boo in Monsters, Inc. was an actual toddler whose sounds were recorded.',
	'Bill Murray was only paid $9,000 for his role in Caddyshack.',
	'The famous "Here\'s Johnny!" line in The Shining was improvised by Jack Nicholson.',
	'The film "Room 237" contains dozens of fan theories about The Shining.',
	'Every Quentin Tarantino film is set in the same universe.',
	'The T-Rex roar in Jurassic Park is a combination of a baby elephant, tiger, and alligator.',
	'Citizen Kane is often called the greatest film ever made.',
	'The fastest film to reach $1 billion was Avengers: Endgame at 5 days.',
	'O.J. Simpson was considered for the role of the Terminator.',
	'The Hobbit trilogy was originally planned as two films.',
	'The sound of the T-Rex footsteps in Jurassic Park is the sound of a sequoia tree falling.',
	'Robert Downey Jr. ate his own food in Iron Man scenes because he hid snacks around the set.',
	'The original cut of Apocalypse Now was over 5 hours long.',
	'The Nightmare Before Christmas took over three years to complete.',
	"Mary Poppins was Walt Disney's last personally-produced film.",
	'The entire Lord of the Rings trilogy was filmed simultaneously.',
	'Michael Jackson wanted to play Spider-Man so badly he tried to buy Marvel.',
	"The rain scene in The Notebook wasn't in the original script.",
	'The word "dude" is said 161 times in The Big Lebowski.',
}
