local FunFact = FunFact
local module = FunFact:NewModule('FactList_Myths')
module.desciption = 'Facts about mythology, legends, and folklore from around the world.'
module.displayname = 'Myths'

module.Facts = {
	'In Greek mythology, Zeus swallowed his first wife Metis because of a prophecy.',
	'The Norse believed the rainbow was a bridge called Bifrost connecting Earth to Asgard.',
	'Dragons appear in nearly every culture\'s mythology around the world.',
	'The Kraken legend was likely inspired by giant squid sightings.',
	'In Japanese folklore, the number 4 is unlucky because it sounds like "death".',
	'Mermaids appear in folklore from Greece, Africa, Asia, and the Americas.',
	'Thor\'s hammer Mjolnir was forged by dwarves in Norse mythology.',
	'The Phoenix myth originated in ancient Egypt and Greece.',
	'Werewolf legends date back to ancient Sumeria over 4,000 years ago.',
	'The Minotaur was kept in a labyrinth designed by Daedalus.',
	'In Chinese mythology, dragons are symbols of power and good luck.',
	'Medusa was once a beautiful priestess before being cursed by Athena.',
	'The Celtic goddess Brigid became Saint Brigid after Christianity spread to Ireland.',
	'Valhalla was the Norse hall where warriors who died in battle were taken.',
	'The Egyptian god Ra traveled through the underworld each night on a boat.',
	'Unicorns were described in ancient Greek texts as real animals from India.',
	'Loki in Norse mythology could shapeshift into various animals and people.',
	'The Greek Titan Atlas was condemned to hold up the sky, not the Earth.',
	'Leprechauns were originally depicted as wearing red, not green.',
	'Anubis was the Egyptian god of mummification and the afterlife.',
	'The Wendigo is a cannibalistic spirit from Algonquian folklore.',
	'Odin sacrificed his eye for wisdom at the Well of Mimir.',
	'Fairies in original folklore were often dangerous, not cute.',
	'The Greek god Hephaestus was the only Olympian god who was ugly.',
	'Banshees in Irish mythology wail to warn of impending death.',
	'The Sphinx asked riddles and killed those who answered incorrectly.',
	'In Hindu mythology, the universe is cyclically created and destroyed.',
	'Fenrir the wolf is destined to kill Odin during Ragnarok.',
	'The Japanese Kappa is a water creature that loves cucumbers.',
	'Pegasus was born from Medusa\'s blood after she was killed by Perseus.',
	'The Rod of Asclepius (snake and staff) is the symbol of medicine.',
	'Trolls in Scandinavian folklore turn to stone in sunlight.',
	'Hercules had to complete 12 labors as punishment for a terrible crime.',
	'The Bermuda Triangle\'s legend has roots in 15th-century Columbus reports.',
	'Cerberus, the three-headed dog, guards the entrance to the Greek underworld.',
	'In Aztec mythology, the god Quetzalcoatl was a feathered serpent.',
	'The Valkyries chose who would die in battle and go to Valhalla.',
	'Pandora\'s "box" was actually a jar in the original Greek myth.',
	'King Midas turned everything he touched to gold, including his daughter.',
	'The Japanese Tanuki is a shapeshifting raccoon dog spirit.',
	'Prometheus was punished for giving fire to humans.',
	'The Loch Ness Monster legend dates back to 565 AD.',
	'Egyptian pharaohs were considered living gods on Earth.',
	'The Headless Horseman legend predates Washington Irving\'s story.',
	'In Norse mythology, the world tree Yggdrasil connects nine realms.',
	'Gorgons were three sisters, and Medusa was the only mortal one.',
	'The Greek god Dionysus was god of wine, parties, and theater.',
	'Sirens in Greek mythology were bird-women, not mermaids.',
	'The Chupacabra legend originated in Puerto Rico in the 1990s.',
	'Athena was born fully grown from Zeus\'s forehead.',
	'The Wild Hunt is a ghostly procession found in European folklore.',
	'Gilgamesh is one of the oldest written heroes, from Mesopotamia.',
	'In African mythology, Anansi the spider is a trickster god.',
	'The original Cinderella story comes from ancient China.',
	'Narcissus fell in love with his own reflection and became a flower.',
	'The Norse god Tyr sacrificed his hand to bind Fenrir.',
	'Mothman sightings preceded the Silver Bridge collapse in 1967.',
	'Kitsune are Japanese fox spirits that can have up to nine tails.',
	'The Green Man appears in architecture across medieval Europe.',
	'Achilles\' only weak spot was his heel.',
	'Bigfoot has equivalents in folklore from many cultures worldwide.',
	'The Egyptian goddess Isis reassembled her husband Osiris after he was killed.',
	'In Greek myth, the River Styx separates the living world from the dead.',
	'The Thunderbird is a powerful spirit in many Native American cultures.',
	'Selkies are seal-people from Scottish and Irish folklore.',
	'The Greek god Pan gave us the word "panic" due to the fear he caused.',
	'Robin Hood legends may be based on multiple real outlaws.',
	'The Norse believed frost giants existed before the gods.',
	'Baba Yaga is a witch who lives in a house that walks on chicken legs.',
	'Odysseus took 10 years to return home from the Trojan War.',
	'The Jersey Devil legend has been told in New Jersey since the 1700s.',
	'Hades was not evil in Greek mythology - he was just ruler of the dead.',
	'The Fountain of Youth was sought by Ponce de Leon in Florida.',
	'In Egyptian myth, hearts were weighed against a feather after death.',
	'The Fisher King guards the Holy Grail in Arthurian legend.',
	'Elves in Norse mythology were powerful beings, not small helpers.',
	'The Golem of Prague was a clay creature brought to life by a rabbi.',
	'Icarus flew too close to the sun with wax wings and fell.',
	'Changelings were fairy children left in place of stolen human babies.',
	'The Greek Fates spun, measured, and cut the threads of life.',
	'Skinwalkers are shapeshifters in Navajo legend.',
	'Poseidon created horses as a gift to win Demeter\'s love.',
	'The Monkey King Sun Wukong is a central figure in Chinese mythology.',
	'Vampires in original folklore couldn\'t enter homes without invitation.',
	'The Tower of Babel story explains why humans speak different languages.',
	'Doppelgangers in folklore are often omens of bad luck or death.',
	'The Hawaiian goddess Pele controls volcanoes.',
	'Cu Chulainn was the greatest hero in Irish mythology.',
	'In Japanese mythology, the sun goddess Amaterasu hid in a cave.',
	'The original fairy tales by the Brothers Grimm were much darker than Disney versions.',
	'Sleipnir, Odin\'s eight-legged horse, was Loki\'s offspring.',
	'The Lady of the Lake gave King Arthur his sword Excalibur.',
	'Zombies originate from Haitian Vodou folklore.',
	'The Greek hero Perseus used Medusa\'s head as a weapon after killing her.',
	'Will-o\'-the-wisps were said to lead travelers astray in swamps.',
	'The Hindu god Ganesha has an elephant head.',
	'Arachne was turned into a spider by Athena for her hubris.',
	'El Dorado was a mythical city of gold sought by Spanish conquistadors.',
	'The nine Muses in Greek mythology inspired arts and sciences.',
	'Coyote is a trickster figure in many Native American traditions.',
}
