local FunFact = FunFact
local module = FunFact:NewModule('FactList_Nachos')
module.desciption = 'Delicious nacho facts'

module.Facts = {
	'Nachos were invented in 1943 by Ignacio "Nacho" Anaya in Piedras Negras, Mexico, when he created them for a group of U.S. military wives.',
	'The inventor of nachos, Ignacio Anaya, was nicknamed "Nacho," which is why the dish is called nachos.',
	'The first nachos were called "Nachos Especiales" (special nachos) and consisted of fried tortilla chips topped with shredded cheese and jalapeño peppers.',
	'October 21st is International Day of the Nacho, celebrating the invention of this beloved snack.',
	'The largest serving of nachos ever made weighed 4,689 pounds and was created in Kansas in 2012.',
	'Nacho cheese sauce was invented in the 1970s and became a staple at sports stadiums and movie theaters.',
	'The world record for eating nachos is 97 jalapeño nachos eaten in 6 minutes.',
	'The first recorded nacho recipe in the United States appeared in a 1949 cookbook called "A Taste of Texas."',
	'Nachos were popularized in the United States by a Texas restaurateur named Frank Liberto, who developed the nacho cheese sauce dispensing machine.',
	'Super Bowl Sunday is the biggest day for nacho consumption in the United States, with over 100 million pounds of tortilla chips consumed.',
	'The original nachos restaurant, "El Nacho" in Piedras Negras, Mexico, is now a historic landmark.',
	"Nachos didn't become widely popular in the U.S. until the 1970s when they were introduced at Arlington Stadium in Texas.",
	'A bronze plaque in Piedras Negras, Mexico commemorates Ignacio Anaya as the creator of nachos.',
	'The term "loaded nachos" refers to nachos topped with multiple ingredients like ground beef, sour cream, guacamole, and salsa.',
	'Nachos are considered a Tex-Mex dish, a fusion cuisine combining Mexican and American culinary traditions.',
	'The average American eats approximately 8 pounds of tortilla chips per year, many of them in the form of nachos.',
	'Ballpark nachos typically use a processed cheese sauce because it stays melted longer than real cheese.',
	'In 2012, Ignacio Anaya was honored with a Google Doodle celebrating what would have been his 124th birthday.',
	'The most expensive nachos in the world cost $2,000 and are served at the Grand Velas Los Cabos resort, featuring gold flakes and lobster.',
	'Sheet pan nachos, also known as "nacho bar" style, became popular in the 2010s as a party food.',
	'Nachos are one of the most popular concession stand foods at sports events, second only to hot dogs.',
	'The original nacho recipe used Colby cheese, which melted better than cheddar.',
	'Dessert nachos have become popular, using cinnamon sugar tortilla chips topped with chocolate, fruit, and whipped cream.',
	'In Ireland, nachos are often served with curry sauce, creating a unique fusion dish.',
	"The nacho cheese flavor was introduced to Doritos in 1972, making it one of the brand's most popular flavors.",
	'Professional sports teams sell millions of dollars worth of nachos each season.',
	'The phrase "not your nachos" is sometimes used to mean "none of your business," a play on the pronunciation of "nacho."',
	'Nachos can be made with various types of chips including corn, flour tortilla, and even sweet potato chips.',
	'The cheese sauce used on movie theater nachos was originally developed for baseball stadiums in the 1970s.',
	'In Canada, "disco nachos" are nachos topped with gravy and cheese curds, similar to poutine.',
	"The world's most expensive nacho cheese cost $200 per ounce and was made with aged cheddar and white truffle oil.",
	"Nachos were inducted into the National Restaurant Association's Menu Hall of Fame in 2012.",
	'The average nacho platter at a restaurant contains between 1,500 and 2,500 calories.',
	'Green Bay Packers fans are among the biggest nacho consumers, eating an average of 200,000 servings per season at home games.',
	'Nachos have inspired various spin-off dishes including nacho fries, nacho burgers, and nacho pizza.',
	'The first nacho machine that could dispense both chips and cheese was patented in 1976.',
	'In some regions of Mexico, traditional nachos are still served with just cheese and jalapeños, without meat or beans.',
	'The phrase "that\'s nacho cheese" became a popular pun in the 1980s.',
	'Nachos are featured in over 75% of sports bar menus across the United States.',
	'The longest nacho chip measured 5 feet 11 inches and was created in 2011.',
	'Vegan nachos have become increasingly popular, using cashew-based cheese sauces and plant-based proteins.',
	'The nacho industry in the United States generates over $1 billion annually.',
	'Ignacio Anaya worked at the Victory Club restaurant when he invented nachos.',
	'The original nachos were cut into triangles using a butcher knife before frying.',
	'National Nacho Day in the United States is celebrated on November 6th.',
	'In 2013, a restaurant in Texas created a 5-foot-tall nacho tower containing 80 pounds of ingredients.',
	'The cheese-to-chip ratio is considered crucial for perfect nachos, with experts recommending 1:3.',
	'Breakfast nachos, topped with scrambled eggs and bacon, have become a popular brunch item.',
	'The first documented nachos in pop culture appeared in the 1977 movie "Smokey and the Bandit."',
	'Korean BBQ nachos, a fusion dish, became trendy in the 2000s, topped with bulgogi beef and kimchi.',
}
