local FunFact = FunFact
local module = FunFact:NewModule('FactList_Pizza')
module.desciption = "That stuff most people sutff shove in their pie hole. We aren't going to talk about what karen does."

module.Facts = {
	'The biggest pizza ever made was 122 feet 8 inches in diameter, baked in Norwood, South Africa in 1990.',
	"Pizza Wasn't Popular in America Until After WWII, when soldiers returning from Italy brought back a love for the dish.",
	'About 13 Percent of Americans Eat Pizza on Any Given Day, according to the Department of Agriculture.',
	"The World's Longest Pizza stretched over 1.3 miles, made in Fontana, California.",
	'The first documented pizzeria was Antica Pizzeria, opened in 1738 in Naples, Italy.',
	'Pepperoni is the most popular pizza topping in the United States.',
	'The Margherita Pizza was named after Queen Margherita of Savoy in 1889.',
	'Saturday Night is Considered the Most Popular Night to Eat Pizza in the US.',
	'In 1962, the "Hawaiian" pizza was invented in Canada by Sam Panopoulos.',
	'The Most Expensive Pizza in the World costs $12,000 and takes 72 hours to make, found in Salerno, Italy.',
	'The First Frozen Pizza Hit the Market in 1962, and it was called "Celentano Brothers."',
	'October is National Pizza Month in the United States.',
	'In Scotland, you can find "Deep-Fried Pizza" as a take-away dish.',
	'The Largest Pizza Order Ever Made was for 13,386 pizzas, ordered by the VF Corporation of Greensboro, North Carolina.',
	'An Average Pizzeria Uses Roughly 55 Pizza Boxes Per Day.',
	'In Alaska, "Reindeer Sausage" is a Common Pizza Topping.',
	'In India, Pickled Ginger, Mutton, and Tofu are Popular Pizza Toppings.',
	'The First Online Purchase was a Pizza from Pizza Hut in 1994.',
	'A Pizza Delivery to the International Space Station was Made in 2001.',
	'In Brazil, Green Peas are a Common Pizza Topping.',
	'New Yorkers Fold Their Slice to Eat it More Easily, a technique known as "The Fold Hold."',
	'The Record for Eating a 12-inch Pizza is 23.62 seconds.',
	'Pizzas are Delivered to the White House on Inauguration Day.',
	'The term "pizza" was first recorded in the 10th century in a Latin manuscript from the Southern Italian town of Gaeta.',
	"Lombardi's in New York City was the first pizzeria in the United States, established in 1905.",
	'Gennaro Lombardi, the owner of Lombardi\'s, is often called the "Patriarch of Pizza".',
	'The "Pizza Margherita" displays the colors of the Italian flag: green (basil), white (mozzarella), and red (tomato).',
	'A "Pizzaiolo" is the term for a pizza chef or pizza maker.',
	'In 2012, the world record for the "Most Varieties of Cheese on a Pizza" was set with 101 different cheese types.',
	'NASA has funded research to develop 3D printed pizza for astronauts.',
	"The first pizzeria in Italy, Antica Pizzeria Port'Alba in Naples, began baking pizzas in 1738 and is still open today.",
	'In 1987, October was officially designated as National Pizza Month in the US by Congress.',
	'The largest pizza base spun in two minutes is 33.2 inches in diameter.',
	'An Italian pizzaiolo once made a pizza containing over 100 varieties of cheese.',
	"The largest pizza commercially available is 4'6\" by 4'6\" and is sold at Big Mama's and Papa's Pizzeria in Los Angeles.",
	'The most expensive pizza listed by Guinness World Records is the Louis XIII, priced at $12,000.',
	'In 2007, a pizza was delivered to the summit of Mount Kilimanjaro, setting a world record for the highest altitude pizza delivery.',
	'The longest pizza delivery was from Cape Town, South Africa to Sydney, Australia.',
	'September 5th is National Cheese Pizza Day, while February 9th is National Pizza Day in the US.',
	'The average American eats about 46 pizza slices a year.',
	'The first documented pizzeria in North America was opened in 1905 by Gennaro Lombardi at 53 1/3 Spring Street in New York City.',
	'There is a Pizza Museum in Philadelphia where you can learn about pizza culture and history.',
	'In Japan, one of the popular pizza toppings is squid.',
	'The world record for the longest pizza is over 1.8 km (1.1 miles) long.',
	'There are pizza farms that grow all the ingredients needed for pizza in one place.',
	'In 2019, the pizza industry in the US was worth over $45 billion.',
	'The first-ever Internet purchase was a pepperoni pizza with mushrooms and extra cheese from Pizza Hut in 1994.',
	'In Ancient Greece, the Greeks covered their bread with oils, herbs, and cheese which some believe is the base of the modern pizza.',
	'During the 17th century, pizza was a dish for poor people sold in the streets of Naples.',
	'The "Associazione Verace Pizza Napoletana" (True Neapolitan Pizza Association) in Italy sets strict guidelines for what qualifies as a true Neapolitan pizza.',
	"The world's fastest pizza maker can make 14 pizza in 2 minutes and 35 seconds.",
	"Chicago's deep-dish pizza was invented at Pizzeria Uno in 1943.",
	'Pizza dough spinning has its own official sporting event in the World Pizza Championships.',
	'The first recorded pizza delivery was for King Umberto I and Queen Margherita of Italy in 1889.',
	'In Australia, a popular pizza topping is kangaroo meat.',
	'Frozen pizza was invented in 1957 by Celentano Brothers.',
	'In the U.S., over 3 billion pizzas are sold every year.',
	'The most popular pizza size in the U.S. is 14 inches in diameter.',
	'The first pizzeria in South America opened in Buenos Aires, Argentina, due to the large Italian community.',
	'The word "pizza" comes from the Latin word "picea," which indicates the blackening of the crust caused by fire.',
	'November 12th is National Pizza with Everything (Except Anchovies) Day.',
	'In Moscow, during the 1990s, pizzas were exchanged for military equipment including tanks and aircraft.',
	'In 2011, a pizza from a restaurant in Melbourne, Australia set a record with 154 varieties of cheese.',
	'The longest-running pizza delivery was from Madrid, Spain to Wellington, New Zealand.',
	'Some pizzerias in Italy offer a "Pizza Metro," where pizza is sold by the meter.',
	'A pizza was once made in Italy with 1000+ different types of cheese, setting a world record.',
	'The most popular pizza topping in Japan is Mayo Jaga (mayonnaise, potato and bacon).',
	"In 2014, the city of Düsseldorf, Germany, inaugurated the world's first pizza vending machine.",
	'Pizza is the most photographed food on Instagram.',
	'In 2005, the Canadian Space Agency delivered a pizza to astronaut Chris Hadfield while he was orbiting the Earth on the ISS.',
	'The world record for eating a 12" pizza is just 23.62 seconds.',
	'Domino\'s Pizza canceled their "30 minutes or less" delivery guarantee after facing several lawsuits.',
	'In Brazil, pizza is often eaten with ketchup or mayonnaise as a topping.',
	'In 2016, a robot-made pizza, from start to finish, was developed by a startup in Silicon Valley.',
	'The most expensive pizza commercially available costs £2,150 and is sold at Maze restaurant in London, UK.',
	'A "Cornicione" is the term for the edge or "lip" of a pizza.',
	'Pizzerias represent 17% of all restaurants in the U.S.',
	'The first pizza ordered by computer was done by the Artificial Language Laboratory at Michigan State University in 1974.',
	"The Pizza Expo, the world's largest pizza-only trade show, is held every year in Las Vegas.",
	'In 2004, the Canadian National Pizza Team was formed to compete in international pizza competitions.',
	'The most pizzas ever made in 24 hours by a team is 13,580.',
	'A typical pizza oven cooks at temperatures from 800 to 1,000 degrees Fahrenheit.',
	'In 2015, the record for the largest gluten-free pizza was set, measuring over 1261 square meters.',
	'The average pizzeria uses roughly 55 pizza boxes per day.',
	'In Cambodia, "Happy Pizza" is a pizza topped with marijuana.',
	"The longest pizza delivery was from Cape Town, South Africa to Sydney, Australia, by Domino's.",
	'A pizza was once sold with a price tag of $4,200 because it included toppings like truffles and gold.',
	'In the 1800s, pizza was a dish for poor people and sold in the streets in Naples, Italy.',
	'The word pizza was first documented in 997 AD in Gaeta, Italy.',
	'The first recorded pizza delivery in history was for Raffaele Esposito to deliver the Pizza Margherita to Queen Margherita of Savoy in 1889.',
	'In the U.S., pepperoni is the most popular topping, found on 36% of all pizzas ordered.',
	'Each year in the U.S., 252 million pounds of pepperoni are consumed.',
	'A pizza only needs to bake for about 90 seconds in an 800-degree Fahrenheit wood-fired oven.',
	'New Haven, Connecticut claims to have invented the first hamburger and lollipop, as well as its own style of pizza, known as "apizza."',
	'In 2009, a pizzeria in New York City created a "Luxury Pizza" priced at $1,000, which included six types of caviar and fresh lobster.',
	'The "Quattro Stagioni" pizza represents the four seasons with different toppings for each section of the pizza.',
	'In 2012, a pizza made in Rome broke the world record for the longest pizza ever made, stretching over 1.2 km (0.75 miles).',
	'Sweden has unique pizza toppings such as banana curry pizza and "kebab pizza" with döner kebab meat and sauce.',
}
