local FunFact = FunFact
local module = FunFact:NewModule('FactList_Space')
module.desciption = 'Facts about space, astronomy, and the cosmos.'
module.displayname = 'Space'

module.Facts = {
	'The Sun accounts for 99.86% of the mass in our solar system.',
	'A day on Venus is longer than a year on Venus.',
	'Neutron stars are so dense that a teaspoon would weigh about 6 billion tons.',
	'There are more stars in the universe than grains of sand on all of Earth\'s beaches.',
	'The footprints on the Moon will likely stay there for 100 million years.',
	'One million Earths could fit inside the Sun.',
	'Space is completely silent because there is no atmosphere for sound to travel through.',
	'The hottest planet in our solar system is Venus, not Mercury.',
	'A NASA spacesuit costs approximately $12 million.',
	'The largest known star, UY Scuti, could fit almost 5 billion Suns inside it.',
	'Saturn would float if you could find a bathtub big enough because it\'s less dense than water.',
	'A year on Mercury is just 88 Earth days.',
	'The International Space Station is the most expensive object ever built at $150 billion.',
	'Astronauts grow up to 2 inches taller in space due to the lack of gravity.',
	'The Voyager 1 spacecraft is the farthest human-made object from Earth.',
	'Jupiter\'s Great Red Spot is a storm that has been raging for over 400 years.',
	'There is a planet made of diamonds twice the size of Earth called 55 Cancri e.',
	'The Milky Way galaxy is on a collision course with the Andromeda galaxy.',
	'Light from the Sun takes about 8 minutes and 20 seconds to reach Earth.',
	'The largest volcano in our solar system is Olympus Mons on Mars.',
	'A black hole\'s gravity is so strong that not even light can escape.',
	'The Moon is slowly drifting away from Earth at about 1.5 inches per year.',
	'There is water ice on Mercury\'s poles despite surface temperatures reaching 800F.',
	'Pluto is smaller than the United States.',
	'The Sun loses 4 million tons of mass every second due to nuclear fusion.',
	'Astronauts cannot cry in space because tears don\'t fall without gravity.',
	'The largest canyon in the solar system is Valles Marineris on Mars.',
	'A day on Jupiter is only about 10 hours long.',
	'The Hubble Space Telescope can see galaxies 13.4 billion light-years away.',
	'Mars has the tallest mountain in the solar system - Olympus Mons at 72,000 feet.',
	'There are more trees on Earth than stars in the Milky Way.',
	'The first animal sent into space was fruit flies in 1947.',
	'Halley\'s Comet won\'t orbit past Earth again until 2061.',
	'The first human in space was Yuri Gagarin in 1961.',
	'Neptune\'s winds can reach speeds of 1,200 miles per hour.',
	'You could fit all the planets in our solar system between Earth and the Moon.',
	'The ISS travels at about 17,500 miles per hour.',
	'A sunset on Mars appears blue.',
	'There are rogue planets that drift through space without orbiting any star.',
	'The largest known structure in the universe is the Hercules-Corona Borealis Great Wall.',
	'One day on Pluto is equivalent to 6.4 Earth days.',
	'The temperature in space is about -455 degrees Fahrenheit.',
	'Europa, one of Jupiter\'s moons, has a subsurface ocean with more water than Earth.',
	'The Apollo astronauts\' footprints on the Moon could last for millions of years.',
	'The first woman in space was Valentina Tereshkova in 1963.',
	'Uranus rotates on its side, with its axis tilted at 98 degrees.',
	'The nearest star to Earth after the Sun is Proxima Centauri, 4.24 light-years away.',
	'Space smells like seared steak and gunpowder according to astronauts.',
	'The Sun orbits the center of the Milky Way once every 230 million years.',
	'Saturn\'s moon Titan has lakes and rivers of liquid methane.',
	'There are more than 500,000 pieces of space debris orbiting Earth.',
	'The first satellite in space was Sputnik 1 in 1957.',
	'A pulsar can spin up to 716 times per second.',
	'The Sun is 93 million miles away from Earth.',
	'The first dog in space was Laika in 1957.',
	'Mercury has no atmosphere, which means no wind or weather.',
	'The largest moon in the solar system is Ganymede, orbiting Jupiter.',
	'Astronauts on the ISS witness about 16 sunrises and sunsets every day.',
	'The core of the Sun is about 27 million degrees Fahrenheit.',
	'Venus rotates backwards compared to most other planets.',
	'The Oort Cloud extends nearly 2 light-years from the Sun.',
	'A neutron star can spin 600 times per second.',
	'The Great Attractor is pulling our galaxy toward it at 1.4 million mph.',
	'Mars has seasons like Earth because of its similar axial tilt.',
	'The first American in space was Alan Shepard in 1961.',
	'Jupiter has at least 95 known moons.',
	'The asteroid belt contains millions of asteroids but has a lot of empty space.',
	'The Kuiper Belt is home to Pluto and other dwarf planets.',
	'Light travels at 186,000 miles per second.',
	'The first successful landing on Mars was Viking 1 in 1976.',
	'Enceladus, a moon of Saturn, shoots geysers of water into space.',
	'The Milky Way is estimated to contain 100-400 billion stars.',
	'A magnetar\'s magnetic field is a trillion times stronger than Earth\'s.',
	'The Sun will eventually become a red giant and engulf Mercury and Venus.',
	'The first spacewalk was performed by Alexei Leonov in 1965.',
	'There may be a Planet Nine lurking in the outer solar system.',
	'The Crab Nebula was created by a supernova observed by Chinese astronomers in 1054.',
	'Cosmic rays constantly bombard Earth from deep space.',
	'The first image of a black hole was captured in 2019.',
	'Triton, Neptune\'s largest moon, orbits backwards.',
	'The universe is approximately 13.8 billion years old.',
	'The first Mars rover was Sojourner in 1997.',
	'Quasars are the brightest objects in the universe.',
	'The Drake Equation estimates the number of intelligent civilizations in our galaxy.',
	'Venus has more volcanoes than any other planet in our solar system.',
	'The cosmic microwave background is the afterglow of the Big Bang.',
	'Io, Jupiter\'s moon, is the most volcanically active body in the solar system.',
	'The first humans to orbit the Moon were the Apollo 8 crew in 1968.',
	'Dark matter makes up about 27% of the universe.',
	'Dark energy makes up about 68% of the universe.',
	'Only about 5% of the universe is ordinary matter.',
	'The JWST is the largest and most powerful space telescope ever built.',
	'A solar flare can release the energy equivalent of millions of nuclear bombs.',
	'The first American woman in space was Sally Ride in 1983.',
	'There are mountains on Pluto made of frozen nitrogen.',
	'The speed needed to escape Earth\'s gravity is about 25,000 mph.',
	'Betelgeuse could explode as a supernova within the next 100,000 years.',
	'The first landing on a comet was achieved by the Philae lander in 2014.',
	'Gamma-ray bursts are the most energetic events in the universe.',
	'The Cassini spacecraft orbited Saturn for 13 years before crashing into it.',
}
