local FunFact = FunFact
local module = FunFact:NewModule('FactList_Taco')
module.desciption = 'Taco facts'

module.Facts = {
	'The word "taco" originates from the Nahuatl word "tlahco," meaning "half or in the middle," referring to the way it is formed.',
	'Tacos predate the Europeans in Mexico and were discovered to be a part of the indigenous diet, as observed by the Spanish when they arrived in Mexico.',
	'The first references to the taco in any sort of archive or dictionary come from the end of the 19th century.',
	"Taco Bell, one of the world's most famous taco chains, was founded in 1962 in California by Glen Bell.",
	'The largest taco ever created was 246 feet long, made in 2011 in Mexico.',
	'Tacos were originally filled with small fish in the lake regions of the Valley of Mexico.',
	'Authentic Mexican tacos are typically served on soft corn tortillas, unlike the hard shell tacos popularized in the United States.',
	'In Mexico, the most traditional types of tacos are Tacos al Pastor, which are shawarma-style meat typically served with pineapple.',
	'National Taco Day is celebrated on October 4th in the U.S. and on March 31st in Mexico.',
	'Tacos al pastor were influenced by Lebanese immigrants to Mexico, adapting their shawarma to local tastes.',
	'The "Baja-style" fish taco is said to have originated in Ensenada, Mexico, featuring fried fish, cabbage slaw, and a creamy sauce.',
	'The world record for the most tacos eaten at once is 126 tacos in 8 minutes.',
	'Taco trucks, a form of mobile street food, originated in New York in the 1860s with food carts serving tacos to workers.',
	'The "taco de ojo" (eye taco) is a Mexican slang phrase meaning to look but not touch, often used when admiring something from a distance.',
	'A "Taqueria" is a Spanish word for a restaurant that specializes in tacos, typically seen throughout Mexico and the U.S.',
	'In many parts of Mexico, tacos are eaten without utensils, often garnished simply with onions, cilantro, and salsa.',
	'Taco Tuesday is a popular custom in many US cities, where restaurants offer tacos at a discount.',
	'The word "taqueria" was officially added to the Royal Spanish Academy\'s dictionary in 1914.',
	'Carnitas, meaning "little meats," is a type of taco filling made from braised or simmered pork in Mexican cuisine.',
	'A favorite breakfast taco in Texas is filled with eggs, cheese, and bacon or chorizo.',
	'The first documented "taco feast" was held by Hernan Cortes and his men in Coyoacan, Mexico, around the 1520s.',
	'Cricket tacos are a common street food in Oaxaca, Mexico, known for their high protein content.',
	'The "Guinness World Record" for the largest taco was set in 2003 in Mexico, with a taco that was 35.9 meters long.',
	'The fish taco, originated in Baja California, Mexico, became popular in the United States in the 1980s.',
	'Tacos de cabeza, or "head tacos," utilize all parts of the cow\'s head, including eyes, lips, and brain.',
	'Tacos al carbon are made with meat grilled over charcoal, a traditional method imparting a smoky flavor.',
	'The first U.S. taco truck was operated by Raul Martinez, who converted an old ice cream truck in 1974.',
	'Puffy tacos, a popular taco variety in Texas, are made with a leavened dough that puffs up when fried.',
	'Tacos dorados, also known as "golden tacos," are filled and then fried until crispy.',
	'In 2012, nearly 5 billion tacos were consumed in the United States alone.',
	'In Mexico City, tacos al pastor is typically served on a corn tortilla with chopped onions, cilantro, and a small slice of pineapple.',
	'Choco Tacos, a dessert item mimicking the shape of a taco, were invented in the 1980s and consist of ice cream inside a chocolate-dipped taco shell.',
	'In traditional Mexican cuisine, tacos de lengua (tongue tacos) are made from the beef tongue and are considered a delicacy.',
	'The smallest taco in the world, called "Taquito," is a miniature taco popular in Mexico, known for its small size and is typically deep-fried.',
	'Flautas, also known as "taco dorados," are made with tortillas filled with meats and cheese, then rolled and fried until crispy.',
	'Tacos de cazo, or tacos cooked in a large pot or cazo, often include offal as the main ingredient.',
	'Taco del Mar, a fast-food restaurant chain, popularized the "Mondo Burritos," but originally started with the mission-style taco.',
	'Vegetarian and vegan tacos are gaining popularity, with fillings ranging from avocado to zucchini blossoms.',
	'In 2017, a record was set in Mexico for the longest taco line, stretching over 2,500 meters in length.',
	'Taco rice, a popular dish in Okinawa, Japan, combines ground beef, cheese, and lettuce served on a bed of rice, inspired by taco fillings.',
	'Tacos de canasta, also known as "basket tacos," are steamed tacos kept warm in large baskets, a popular street food in Mexico.',
	'The "Taco Liberty Bell" was an April Fool\'s joke played by Taco Bell in 1996, claiming they had purchased the Liberty Bell to reduce the national debt.',
	"Tacos de suadero are made from a cut of beef from the cow's breast and are a popular late-night food in Mexico City.",
	'The term "walking taco" refers to a snack-sized bag of tortilla chips with taco toppings, popular at fairs and outdoor events.',
	'In 2020, a taco featuring black truffle and Kobe beef sold for $25,000 in Los Cabos, Mexico, reportedly the most expensive taco ever sold.',
	'Tacos gobernador are a type of shrimp taco that originated in Sinaloa, Mexico, typically made with cheese and grilled shrimp.',
	'In some regions of Mexico, tacos are also enjoyed with a side of consommé, a rich broth made from the meat used in the tacos.',
	'The term "hard shell taco" was first referenced in American cookbooks around the 1940s, distinguishing them from the traditional soft shell tacos.',
	'Tacos árabes, or "Arabian tacos," were created in Puebla, Mexico, and are typically made with spit-grilled pork, resembling shawarma.',
	'A popular vegetarian option, tacos de nopales are made with grilled or sautéed cactus paddles.',
	'In 2018, the city of Austin, Texas declared itself the "breakfast taco capital of the world," sparking a friendly rivalry with other cities in Texas.',
	'The first recorded instance of fish tacos dates back to the indigenous people living in the coastal areas of Mexico, who used fresh fish and corn tortillas.',
	'Zacatecas, Mexico, is known for its tacos envenenados ("poisoned tacos"), which are actually safe to eat and are filled with a spicy stew.',
	'Tacos de adobada are made from pork marinated in a red chili sauce, then cooked on a vertical rotisserie similar to tacos al pastor.',
	'The city of Querétaro in Mexico holds an annual taco fair, where vendors and chefs showcase a wide variety of tacos.',
	'Taco acorazado, or "battleship taco," is a large taco originating from Cuernavaca, Mexico, typically filled with rice and a breaded beef cutlet.',
	'In the United States, the first patent for a taco shell fryer was filed in 1950, revolutionizing how hard shell tacos are made.',
	'Tacos are celebrated worldwide, with various countries putting their unique twist on the traditional form, including Korean tacos, Indian tacos, and more.',
	'Tacos sudados, also known as "sweaty tacos," are a type of taco where the tortillas are steamed until soft and filled with meat, resulting in a moist texture.',
	'In 2021, a group of chefs in Mexico City set a new record for the largest serving of tacos with thousands of tacos prepared in a single event.',
	'Tacos al guisado are a type of taco filled with stewed or braised meats, often featuring a variety of Mexican sauces and salsas.',
	"In many regions of Mexico, it's common to sprinkle lime juice and add radish slices as a garnish for tacos.",
	'Taco trucks, or "loncheras," have been serving tacos in the U.S. since the 1960s, and have since become a staple in urban street food culture.',
	'The "Double Decker Taco" was introduced by Taco Bell in the 1990s, featuring a soft tortilla glued to a hard shell with a layer of beans.',
	'Some of the earliest tacos documented were called tacos de minero, or "miner\'s tacos," consumed by silver miners in Mexico during the 18th century.',
	"In Mexico City, it's common to find blue corn tortillas, which are made from a special type of corn and offer a nuttier flavor and higher protein content.",
	'The city of Los Angeles is often credited with popularizing the Korean-Mexican taco fusion, featuring Korean-style beef, chicken, or pork with Mexican toppings.',
	'A taco tour is a popular culinary activity in many Mexican cities, allowing food lovers to sample various types of tacos from street vendors and restaurants.',
	'Durango, Mexico, is known for its tacos callejeros, or "street tacos," typically smaller in size and eaten as a snack throughout the day.',
	'In coastal regions of Mexico, tacos de mariscos (seafood tacos) are prevalent, with fillings such as shrimp, fish, octopus, and even sea snail.',
	'Tacos de cazuela are made from slow-cooked stews or casseroles and are known for their rich and hearty flavors.',
	'The "taco emoji" was added to the Unicode Standard in 2015 due to popular demand from taco lovers worldwide.',
	'A variation of taco in Northern Mexico is the taco de trompo, where the meat is cooked on a vertical spit and often served with a slice of pineapple.',
	'Some gourmet restaurants have created upscale versions of tacos, using ingredients like lobster, truffle, and wagyu beef.',
	"During certain festivals in Mexico, it's common to see tacos filled with exotic meats such as iguana, rattlesnake, or insects like chapulines (grasshoppers).",
	'The term "taco" in the mining industry referred to little charges used to excavate ore, which resembled the shape of the traditional Mexican taco.',
	'Some of the oldest traditional tacos are made with small fish or shrimp, reflecting the coastal regions of Mexico where they originated.',
	'Tacos de asador are typically made with meats such as chorizo, tripas, or carne asada, grilled over an open flame.',
	"In Mexico, it's common to have tacos de canasta as a breakfast, which are soft and warm from being steamed in a basket.",
	'The smallest version of a taco is called a taquito or flauta, which is a small rolled-up taco, typically fried.',
	'A type of taco called "tacos de buche" features pork stomach as the main filling, popular in certain regions of Mexico.',
	'Taco competitions and festivals are held around the world, celebrating the best of taco making and innovation.',
	'Tacos de barbacoa, a traditional Mexican dish, are made from lamb or goat meat that has been slow-cooked over an open fire or in a hole dug in the ground.',
	'In the U.S., hard shell tacos became popular in the mid-20th century when they were mass-produced by companies like Taco Bell.',
	'A taco salad is a Tex-Mex dish that features many of the ingredients of a taco, served inside a fried tortilla bowl.',
	'Tacos de lengua, made with beef tongue, are considered a delicacy and are slow-cooked until tender.',
	'Migas tacos, a Tex-Mex breakfast dish, include scrambled eggs mixed with strips of tortilla, often served with a variety of salsas.',
	"In Mexico, it's not uncommon to find tacos filled with chicharrón, or fried pork belly, often served with salsa verde.",
	'The "triple taqueria" or "trio taco" is a popular serving that includes three different types of tacos on the same plate.',
	'Tacos de cabrito, made from young goat meat, are a specialty in the northern states of Mexico, particularly Nuevo León.',
	'Tacos go global with various international twists, such as Indian curry tacos, Greek gyro-style tacos, or Italian-inspired tacos with pesto and mozzarella.',
	'In 2017, a luxury hotel in Mexico offered a $25,000 taco featuring Kobe beef, Almas Beluga caviar, and black truffle brie cheese.',
	'Veggie tacos often use ingredients like mushrooms, beans, cactus, and potatoes to provide a hearty and flavorful experience without meat.',
	'Some of the most adventurous taco fillings include exotic meats like alligator, shark, or ostrich, particularly in specialty or gourmet restaurants.',
	'Taco al pastor, which means "shepherd\'s style," was influenced by Lebanese immigrants to Mexico, adapting their shawarma-style cooking to local tastes.',
	'Taco art, including murals and paintings, celebrates the taco culture and can be found in various cities known for their love of tacos.',
	"A taco cleanse is a humorous take on dieting where participants eat only tacos for a certain period; it's a real book and a nod to taco lovers everywhere.",
	'The first taco truck in Los Angeles was operated by Raul Martinez, who converted an old ice cream truck into a mobile taco vehicle in 1974.',
	'Tacos have inspired numerous fast food chains, books, festivals, and even academic studies examining their cultural impact.',
}
