local FunFact = FunFact
local module = FunFact:NewModule('FactList_Tech')
module.desciption = 'Tech facts'

module.Facts = {
	'The first electronic computer ENIAC weighed more than 27 tons and took up 1800 square feet.',
	'The first computer mouse was made in 1964 by Doug Engelbart and it was made out of wood.',
	'Approximately 90% of the world’s currency exists only on computers and not in physical form.',
	'The original name of Windows was Interface Manager.',
	'The first 1GB hard disk drive was announced in 1980, which weighed about 550 pounds and had a price tag of $40,000.',
	'The first domain name ever registered was Symbolics.com on March 15, 1985.',
	'CAPTCHA stands for "Completely Automated Public Turing test to tell Computers and Humans Apart."',
	'The QWERTY keyboard layout was designed to slow down typing speed to prevent jamming on mechanical typewriters.',
	'Konrad Zuse, a German engineer, created the first programmable computer in 1941 called the Z3.',
	'The first known computer programmer was Ada Lovelace, who wrote an algorithm for Charles Babbage’s Analytical Engine in the mid-1800s.',
	'There are over 7000 programming languages in existence today.',
	'The first successful high-level programming language was Fortran, developed in the 1950s by IBM.',
	'As of 2021, the largest solid-state drive (SSD) has a capacity of 100TB.',
	'The first computer virus was created in 1971, called the Creeper system, which was an experimental self-replicating program.',
	'The first ever Vlog was created by Adam Kontras, launching a video blog to inform his family and friends of his cross-country move to Los Angeles.',
	'Ninety-two percent of the world’s currency is digital, meaning most of the money in the world exists only on computers.',
	'The first website was about information on the World Wide Web project and was published on August 6, 1991, by Tim Berners-Lee.',
	'The game "Pong" was the first arcade video game to become wildly popular and is considered the father of video gaming.',
	'In 1956, IBM created the first hard drive, and it was the size of two refrigerators with a storage of 3.75MB.',
	'The term "bug" in computing, referring to an error or flaw in the system, is attributed to a moth that was found trapped in a computer by Grace Hopper.',
	'Email predates the World Wide Web; the first email was sent in 1971, while the web was invented in 1989.',
	'The first ever banner ad on the Internet appeared in 1994 and it read "Have you ever clicked your mouse right here? You will."',
	'The famous "Duck Hunt" game for the NES console used a light-sensing technology in the gun; the screen would flash a block of white when you pulled the trigger, which the gun would detect.',
	'The average computer user blinks seven times a minute, the normal rate is twenty times per minute.',
	'The group of 12 engineers who developed the IBM PC were called "The Dirty Dozen."',
	'MIT has created a "smart" diaper embedded with a moisture sensor that can alert a caregiver when it\'s wet.',
	"In the 1980s, an IBM computer wasn't considered 100 percent compatible unless it could run Microsoft Flight Simulator.",
	'The first alarm clock could only ring at 4 am, invented by Levi Hutchins in 1787, for his own use.',
	'Typing "about:blank" into your browser can bring up a blank page; some people use it to focus or as a quick way to clear their screen.',
	'One of the earliest computer games, "Spacewar!", was developed in 1962 and could be played on the tiny screens of early computers.',
	'The first emoticon is credited to computer scientist Scott Fahlman in 1982, who suggested using :-) to denote jokes on an online bulletin board.',
	'There’s a competition for Microsoft Excel spreadsheets where participants showcase incredibly intricate designs and complex formulas.',
	'The first Apple logo featured Sir Isaac Newton sitting under an apple tree, it was designed by Ron Wayne, co-founder of Apple.',
	"In 1999, PayPal was voted as one of the top ten worst business ideas. As of now, it's one of the leading online payment services.",
	'The original Nintendo Game Boy could run for approximately 30 hours on just two AA batteries.',
	'The wireless technology Bluetooth is named after a 10th-century king, Harald Bluetooth, who united Denmark and Norway; the symbol is a combination of their runes.',
	'Google rents goats to mow the lawns of their mountain view HQ, as a low-emission alternative to lawn mowers.',
	'The first photo ever uploaded to the Internet was posted by Tim Berners-Lee in 1992, of the comedy band "Les Horribles Cernettes."',
	'The Apollo 11 mission to the moon used computers with less processing power than a modern-day cell phone.',
	'In the early days of mobile phones, Nokia phones were so well known for their durability that they\'ve been jokingly referred to as "the handheld tanks."',
	'The first camera phone was sold in 2000 in Japan, a Sharp J-SH04. A user could take pictures and send them along with texts.',
	'The name "Wi-Fi" doesn\'t stand for anything. It is not short for "Wireless Fidelity", as commonly believed; it was a brand name created by a marketing firm.',
	'The average 21st-century person has more computing power in their pocket than NASA had when they landed a man on the moon in 1969.',
	'The first computer virus was called "Creeper" and was detected on ARPANET in the early 1970s, displaying the message "I\'m the creeper, catch me if you can!"',
	'Google was originally called "Backrub", named for its analysis of the web\'s "back links."',
	'The first known instance of "spam" was a telegraph message in 1864.',
	'The first YouTube video was uploaded on April 23, 2005, and is titled "Me at the zoo." It shows co-founder Jawed Karim at the San Diego Zoo.',
	'There are over 6,000 new computer viruses released every month.',
	"In 1936, the first programmable computer, the Z1, was created by Konrad Zuse in his parents' living room.",
	'The first gigabyte-sized disk drive was made in 1980, weighed 550 pounds, and cost $40,000.',
	'If you tried to count to a trillion and said one number every second non-stop, it would take over 31,000 years.',
	'The first banner ad on the Internet appeared in 1994 on HotWired.com, now known as Wired.com.',
	'The "@" symbol was used in email addresses before it became standard in email protocols. Ray Tomlinson is credited with choosing it in 1971.',
	'The term "surfing" the internet was coined by librarian Jean Armour Polly in 1992.',
	'CDs (Compact Discs) were designed to contain 74 minutes of music because that is the length of Beethoven’s Ninth Symphony.',
	'The inventor of the modern world wide web, Tim Berners-Lee, was knighted by Queen Elizabeth.',
	'Mosaic was the first popular web browser launched in 1993, leading the way for modern browsers.',
	'The first 1TB hard drive was announced in 2007, which is less than a decade after the first 1GB hard drive.',
	'More than 80% of the emails sent daily are spam.',
	'The first "actual" computer bug was a dead moth which was stuck in a Harvard Mark II computer in 1947.',
	'The first known calculation device was the abacus, used in ancient times for basic arithmetic operations.',
	'The term "computer" originally referred to humans who performed numerical calculations, often with the aid of a mechanical calculating device.',
	'The game Tetris was created by Russian software engineer Alexey Pajitnov in 1984; it became the first game from the USSR to be popular in the US.',
	'The first commercial home video game console was the Magnavox Odyssey, released in 1972.',
	"Sony's PlayStation 2 is the best-selling game console of all time, with over 155 million units sold worldwide.",
	'The first 1TB USB flash drive was announced in 2013.',
	'Virtual Reality (VR) technology has been in development since the 1960s, with the first VR head-mounted display being invented in 1968.',
	'The first ever "Easter egg" in a video game was a hidden message in the game Adventure for Atari 2600, created by Warren Robinett in 1979.',
	'The highest-selling computer of all time is the Commodore 64, introduced in 1982.',
	'The first mobile phone with Internet connectivity was the Nokia 9000 Communicator, launched in Finland in 1996.',
	'The first patent for a system that recognized human handwriting was granted in 1914.',
	"The Intel 4004, released in 1971, was the world's first microprocessor.",
	'The original IBM PC\'s code name was "Acorn."',
	'In 1990, Tim Berners-Lee coined the phrase "World Wide Web" in a paper about his idea for a new information management system.',
	'The first known "hack" occurred in 1903 when magician Nevil Maskelyne disrupted John Ambrose Fleming\'s public demonstration of Marconi\'s purportedly secure wireless telegraphy technology.',
	'The first ASCII emoticons, :-) and :-(, were invented by Scott E. Fahlman in 1982 to distinguish serious posts from jokes in online communication.',
	'The first smartphone, called Simon, was released by IBM in 1994 and combined a mobile phone with features of a PDA.',
	'The original Space Invaders game was so popular that it caused a temporary shortage of 100-yen coins in Japan.',
	'The deep web is estimated to be 500 times larger than the surface web, which is accessible through standard web browsers.',
	'Pixar\'s first film, "Toy Story," was the first entirely computer-animated feature film.',
	'Google estimates that the internet is about 5 million terabytes of data, and they have indexed only 0.04% of it all.',
	'The first known case of "ransomware" was the AIDS Trojan in 1989, which demanded users send $189 to a post office box in Panama to unlock their files.',
	'In 2015, the United Nations declared Internet access a basic human right.',
	'The first DDoS attack occurred in 2000, when a 15-year-old, known as "Mafiaboy," took down major websites including CNN, Yahoo, and eBay.',
	'The first Apple computer, Apple I, was built in Steve Jobs garage.',
	'The first GPS satellite was launched in 1978, beginning the network that would become the Global Positioning System.',
	'The first digital camera was invented in 1975 by an engineer at Eastman Kodak. It weighed 8 pounds and took 0.01-megapixel photos.',
	'The word "robot" comes from the Czech word "robota," meaning "forced labor," and was first used to describe fabricated workers in a 1920 play.',
	'The first recorded use of the word "software" was in a 1958 article by John W. Tukey in the American Mathematical Monthly.',
	'The longest time between a computer bug being introduced and fixed is 25 years in the case of a bug in the MIM-104 Patriot missile system.',
}
