local FunFact = FunFact
local module = FunFact:NewModule('FactList_Ukraine')
module.desciption = 'Ukraine Facts'

module.Facts = {
	"Ukraine's history is intertwined with Russia's history. The first Russian state, the Kievan Rus (9th-13th centuries AD), headed by the Rurik dynasty, was centered in Kiev, the capital of modern Ukraine.",
	'Ukraine\'s name comes from a word meaning “borderland."',
	"One of Ukraine's national dishes is salo, cured pig fat. It is traditionally served cold with garlic, onion, and pickle.",
	'Ukrainians wear their wedding rings on the right hand rather than the left.',
	'Pornography is illegal in Ukraine, except for "medical purposes."',
	'The national drink of Ukraine is horilka, an alcoholic beverage that is often served with chili pepper. The name means "burning water."',
	'A stretch of railroad track winding through a green forest between the Ukrainian towns of Klevan and Orzhiv has been nicknamed "The Tunnel of Love" because of its almost magical beauty. The track was used to secretly move supplies during the Cold War.',
	'Ukraine was chosen as the location for the Yalta Conference, the famous meeting between Churchill, Roosevelt, and Stalin to discuss European boundaries after WWII.',
	'The Ukrainian language is a dialect of Russian, and is spoken in many parts of the country.',
	'Lviv, Ukraine, is home to 1,500 cafes, the most per capita of any city in the world.',
	'After the capital city of Kiev withstood the Nazis in 1941, the Soviet Union declared the entire city to have “hero status.”',
	'Common languages spoken in Ukraine include Ukrainian, Russian, Romanian, Polish, and Hungarian.',
	"Ukrainian citizen Hetman Pylyp Orlyk authored one of the world's first modern constitutions. Orlyk's 1710 document was intended to create a separation of powers within the government.",
	"Kiev, Ukraine, boasts the third-busiest McDonald's in the world.",
	'Cossacks were a group of independent communities inhabiting Southern Russian and Ukraine, famed for their horsemanship and battle prowess.',
	'Ukraine ranks sixth in alcohol consumption internationally.',
	'The largest airplane ever was built in Kiev, Ukraine. The Antonov An-225 Mriya has a wingspan of 88.4 meters and weighs 640,000 kg. It was built during the Soviet era, and only one was built.',
	'Russia uses pipelines that pass through Ukraine to provide Europe with gas.',
	'The Asgarda are a group of Ukrainian women who train in martial arts in the Carpathian Mountains. Their goal is to empower women to win the hearts of warrior men.',
	'Native Ukrainians rarely smile in public.',
	'The longest musical instrument in the world is a wooden horn called a trembita, and it is played by Polish and Ukrainian highlanders.',
	'In 2004, Ukrainians gathered for a peaceful mass protest known as the “Orange Revolution.” The protest succeeded in forcing the government to overturn the results of a rigged election.',
	'In 2014, Russian President Vladimir Putin invaded the Crimean Peninsula in Ukraine and held a “referendum” that annexed the peninsula into the Russian Federation. The Ukrainian government and the United Nations condemned the referendum as a violation of international law.',
	"The blue and yellow of Ukraine's flag represent the sky over fields of grain.",
	'Taras Kulakov, the YouTube sensation known as “Crazy Russian Hacker,” was born in Ukraine. While living there, he was a member of the Ukrainian Olympic swimming team.',
	'A common misconception is that the name of the country is "The Ukraine," but it is just "Ukraine." In 1993, the Ukrainian government formally requested that the country be called simply Ukraine.',
	'Crimea, the southeast region of Ukraine, is populated almost entirely by Russian-speaking people, most of whom identify themselves as ethnic Russian.[',
	'In April of 1986, the Chernobyl nuclear power plant near Pripyat, Ukraine, suffered a catastrophic meltdown. The United Nations called the disaster the “greatest environmental catastrophe in the history of humanity.”',
	'The area around the site of the Chernobyl nuclear disaster is home to some five million Ukrainians, even though it is still contaminated 30 years later.',
	'The amount of radiation released in the Chernobyl explosion was 400 times higher than that created by the bomb dropped on Hiroshima during WWII, and radioactive rain reached as far away as Ireland.',
	"During the rule of USSR leader Joseph Stalin, some of the indigenous Tartars living in Ukraine's Crimean region attempted to collaborate with the Nazis. Stalin responded by deporting large numbers of them.",
	'Life expectancy rates between Ukrainian men and women have a ten-year difference. The expectancy rate for men is only 66 years, partially due to the high rates of alcoholism among Ukrainian men.',
	"Ukraine's population has been steadily declining over the past three decades. In 2016, for every child born there were 1.5 deaths. The high mortality rate is attributed to poor quality of life and limited access to health care.",
	"Ukraine is the birthplace of the Jewish Hasidic movement. The Ba'al Shem Tov, Hasidism's founder, was born in western Ukraine and traveled around the area to share his teachings.",
	'For much of the 20th century, the Ukrainian Greek Catholic Church was deeply persecuted by the Soviet government. Many of the clergy went into hiding and the UGCC became the largest underground church in the history of Christianity.',
	'There are only 86.3 men for every 100 women in Ukraine. This is the sixth-lowest men-to-women ratio in the world, with the average ratio being 101.8 men for every 100 women.',
	'In 2013, student protesters in Ukraine sparked an uprising that resulted in bloodshed but ultimately overthrew the government. Known as the Revolution of Honor, it is also sometimes called “Euromaidan."',
	'Around 3 million ethnic Ukrainians live in the Russian Federation; the highest concentration of these live in Western Siberia, as a result of the many deportations of Ukrainians to the Gulag under the Soviet Union.',
	"Just one week after invading Ukraine's capital city of Kiev, the Nazi Germans took an estimated 34,000 Jews, almost the entire Jewish population in Kiev, to the Valley of Bbyn Iar and massacred them.",
	'During the Soviet era, the “kulaks,” a term for landowning peasants, were declared enemies of the state. In 1930, the Soviet government ordered the “liquidation” of kulaks; in a three-month period known as the dekulakization of Ukraine, around a quarter million Ukrainians were either killed or exiled to Siberia.',
	'The tradition of painting eggs in celebration of Easter first began in Ukraine. The first Easter eggs were colored using wax and dye.',
	"In 1933, the Soviet government refused to respond to a grain famine that occurred across Ukraine, which resulted in the death of 15% of Ukraine's population, approximately 4.8 million people.",
	'During the grain famine of the 1930s, some 2,000 Ukrainians were arrested for cannibalism.',
	'The Crimea became an official part of modern Ukraine in 1954, when Soviet leader Kruschev transferred the area from Russia to the Ukrainian Republic as a symbol of their “eternal friendship.”',
	'Ukraine has one of the highest levels of religious freedom and diversity in all of Europe.',
	'Roughly one out of every five Ukrainians died during WWII, meaning 7 million.',
	"Twenty-two percent of Ukrainian workers' pay is deducted in the form of a “salary fee” that goes toward the pensions of retired Ukrainians.",
	"Ukraine became officially Christian under the rule of the Kievan Rus' Grand Prince Volodymyr, who was seeking a state religion that would unite his people.",
	"Ukraine is famous for the fertile soil that is spread across much of the country, the “chernozen” or black earth. The soil and climate of Ukraine have made agriculture Ukraine's traditional occupation.",
	'Writers Nikolai Gogol and Joseph Conrad were both born in Ukraine.',
	"Ukraine obtained its independence peacefully, as a result of the collapse of the Soviet Union. Decades later, Ukraine maintained that record with the “Orange Revolution,” a peaceful protest that succeeded in forcing out corrupt leaders in Ukraine's national government.",
	"Ukraine's national anthem is titled “Ukraine Has Not Perished Yet.”",
	'The first gas lamp was invented in Lviv, Ukraine',
	'Ukrainians celebrate "Kupala Night," a summer holiday. One of this holiday\'s traditions involves young couples jumping over a fire. Legend holds that if the boy and girl can maintain their hand-hold, their love will last forever.',
	"After the dissolution of the Soviet Union, Ukraine's economy was in turmoil, resulting in much of Ukraine operating on the barter system.",
	"Ukraine was the world's first state to give up its nuclear arsenal. Their last remaining Soviet-era nuclear warheads were removed and dismantled in 1996.",
	'Ukraine has declared actor Steven Seagal a national security risk and banned him from the country.',
}
