local FunFact = FunFact
local module = FunFact:NewModule('FactList_USA')
module.desciption = 'USA, USA, USA!'

module.Facts = {
	'The United States of America is also referred to as "the States", "the United States", "the U.S.", "the USA", and "America".',
	'In 1783, the United States became the first country to gain independence from a European power.',
	'Did you know that the GPS is operated and maintained by the U.S. Air Force?',
	'The first constitution of the United States was adopted in 178',
	'The current U.S. flag was designed by a high school student - Robert G. Heft.',
	'There are 13 stripes on the American National flag, representing the original thirteen colonies? And there were thirteen stars arranged in a circle. However, today, there are 50 stars for 50 states. ',
	"The U.S. is the world's largest economy by nominal GDP and the world's second-largest economy by PPP. It is also the third most populated country in the world after China and India.",
	'Did you know that Rhode Island witnessed the beginning of the American Revolution? It was here that the first successful water-powered cotton-spinning factory went into operation in the 1790s.',
	"Did you know that the United States has the world's largest coal reserves? However, note that China is the world's biggest consumer and producer of coal.",
	'The phrase "United States of America" was first published anonymously in the Virginia Gazette newspaper in Williamsburg, Virginia, on April 6, 177',
	'Did you know that more than one-third of adults in the United States are obese? Obesity costs Americans $147 billion each year. Colorado has the lowest obesity rates.',
	'The United States experiences the highest rate of tornadoes of any country in the world. On an average, the country deals with more than 1000 tornadoes every year.',
	'Alaska has the longest coastline of any state while Florida has the second longest.',
	"Did you know that gold was discovered at Sutter's Mill near Sacramento, California in 1948? Interestingly, by 1850 nearly 300,000 immigrants had arrived to seek their fortune.",
	"The United States of America has the world's largest air force. It was founded on September 18, 194 The USAF with more than 5,369 military aircraft is the most technologically advanced air force in the world.",
	'Michael Phelps, a retired swimmer, from the United States is the most decorated and the most successful Olympian of all times. He has won 28 medals. Phelps won eight gold medals at 2008 Beijing Games.',
	'Mount Rushmore Monument in the United States shows the heads of the four former presidents of the United States (George Washington, Thomas Jefferson, Theodore Roosevelt and Abraham Lincoln.)',
	'The United States (9,833,517 sq km) is more than twice the size of the European Union (4,475,757 sq km).',
	'The first United States Census was taken in 179 The census takes place every ten years and counts all people living in the U.S.',
	'Spanish is the second most common language spoken in the U.S. However, the U.S. does not have any official language.',
	'Lasting from 1929 to 1939, The Great Depression was the worst economic downturn in the history of America.',
	'In 1800 the U.S. population was approximately 5,309,000 and by 1850 it was 23,191,86',
	'The U.S. was formed by thirteen colonies of Great Britain after defeating Great Britain in the American Revolutionary War. On July 4, 1776, the Declaration of Independence was issued.',
	"In 2008, Barack Obama became the first black president of the United States. In 2012, he was re-elected as the country's president. Obama was succeeded by Donald Trump.",
	'Did you know that Los Angeles ranks as the city with worst traffic in the United States?',
	'The country has a large population. However, due to the fact that it also has an extensive area under its territory, the population density of America is relatively low.',
	'Death Valley is the lowest point in the continent and Mt. McKinley is the highest point in North America.',
	"The U.S. is the world's largest consumer of cocaine which is allegedly shipped from Columbia.",
	'George Washington was the first president of the United States.',
	'The horizontal width of the U.S. is 2860 miles and the vertical length of the country is 1582 miles. Hawaii is the widest U.S. state from east to west.',
	'Did you know that the Everglades National Park is the only ecosystem in the world where alligators and crocodiles co-exist side by side?',
	'Did you know that the U.S. Patent Act was passed in Philadelphia in 1790?',
	'Interestingly, Abraham Lincoln is the only U.S. president to own a patent and a saloon.',
	'Did you know that before 1776, the United States was not a single country.',
	'Four of the forty-five presidents of the United States have been assassinated in office.',
	'The United States is the first country to have developed nuclear weapon and the only country to have used them in combat.',
	'The United States and Russia both claim to have landed on the moon for the first time in history in 196',
	'Did you know that the U.S. purchased Alaska from Russia for just US$2 million in 1867?',
	'After Christianity and Judaism, Islam is the third largest religion in number in the U.S.',
	'Three U.S. presidents died on 4th of July. Thomas Jefferson and John Adam died on July 4, 1826, while John Monroe died on July 4, 183',
	'The only point shared by four states (Utah, Colorado, Arizona, and New Mexico) in the U.S. is the Four Corners Monument.',
	'Did you know that Nelson Mandela was on U.S. terror watch list until 2008?',
	'According to Title 3 of the US Code, the U.S. president earns a salary of $400,000 a year.',
	'The first oil drilling started near Titusville, Pennsylvania, in 185',
	'In 2001, the first self contained artificial heart was successfully implanted into a man with end heart failure at the Jewish Hospital of the University of Louisville, Kentucky, U.S.',
	'Did you know that Yellowstone (Area: 8,991 km²) was the first national park in the U.S.? It was established in 187 The National Park Service was established in 191',
	"The United States is one of the 17 megadiverse countries (megadiverse refers to a country where the majority of Earth's species and a high number of endemic species are found) of the world.",
	'The U.S. also shares maritime borders with Russia, Cuba, and the Bahamas.',
	'The first moving assembly line for the mass production of an entire automobile was installed in America by the legendary businessman and industrialist Henry Ford on December 01, 191',
	'Did you know that more than 3 million people including 58,000 Americans were killed in the Vietnam War? The war happened due to the conflict between North Vietnam and South Vietnam.',
	'Apple Computer launched its Macintosh computer in 198 The company is today valued at more than $1 Trillion, becoming the second publicly traded company to reach the mark.',
	'The United States is the largest producer of nuclear power, while France has the largest share of electricity generated by nuclear power.',
	'The U.S. has 99 operating commercial nuclear reactors at 61 nuclear power plants in 30 states. On an average, these nuclear reactors are 37 years old.',
	'According to Centers for Disease Control and Prevention, one in every four deaths in the United States is due to heart attack. Every year in America about 735,000 people have a heart attack.',
	'id you know that the foreign motor vehicle manufacturing companies are manufacturing more cars and trucks in the United States than that of all of the U.S. automobile manufacturing companies combined?',
	'he United States is at the fourth spot among the countries with most number of internet users. China leads the tally with a huge margin, followed by European Union (2nd) and India (3rd).',
	'he U.S. is one of the most ethnically diverse and multicultural nations.',
	"t 34%, the U.S. holds the world's largest share of wealth.",
	'mazingly, 100 acres of pizza are served in the U.S. every day.',
	'he influence of early French and Spanish settlers is still present in the culture and food of the state.',
	'The nickname of the state "the Pelican State" comes from the many pelicans that used to inhabit the state\'s gulf coast. (check the table at the end of the article for state symbols and nicknames)',
	"Louisiana is among the country's leading oil and gas producing states.",
	'The official flag of Louisiana was adopted in 1912, one hundred years after Louisiana became a state.',
	'The Mississippi River borders and runs through the state.',
	'The state of Louisiana has been governed under 10 different flags since 154',
	'In 1823, the first natural gas field was discovered in Louisiana. It was found at a depth of 400 feet.',
	'Louisiana, because of the fertility of its land, was once one of the richest regions in America. Indigo, sugar, and cotton helped make the statesmen some of the richest Americans.',
	'Between 1682 and 1763 Louisiana was a colony of the kingdom of France.',
	'In November 1762, France handed over Louisiana and the Isle of Orleans to Spain.',
	"Louisiana was named by René-Robert Cavelier in mid-1600's to honor King Louis XIV, King of France from 1643 to 171",
	'Did you know that the original Louisiana territory is now divided into 13 states?',
	'Louisiana does not have an official language. English, French, Spanish, and Vietnamese are the languages that are spoken in Louisiana.',
	'Louisiana is one of the wettest states in the U.S. Hawaii overall is the rainiest state in the US.',
	'Because of the presence of the Mississippi River in Louisiana, Baton Rouge has become an important inland port.',
	'Louisiana leads other U.S. states in the production of crayfish and shrimp.',
	'Louisiana also made important contributions in the United States space exploration program. The state facilitated the production of the C-5 boosters used in the Apollo moon-landing program.',
	'The Louisiana state license plates had the following nickname and phrases appear on them, beginning with: the "Bayou State", "World\'s Fair Plate" and the "Sportsman\'s Paradise Plate."',
	'List of the capitals of Louisiana: New Orleans from 1812-1830; Donaldsville from 1830-1831; New Orleans from 1831-1849; Baton Rouge from 1849-1862; New Orleans from 1862-1882; Baton Rouge since 188',
	'The geographic center of Louisiana is located in Avoyelles Parish, 3 miles SE of Marksville. The state is about 380 miles long and 130 miles wide.',
	'Interestingly, the shape of the state resembles the shape of the capital letter "L" or a boot.',
	'Native American tribes such as the Natchez, Bayougoula, and Chitamacha were the first inhabitants of what is now Louisiana.',
	'The state is also a major producer of soybeans and corn.',
	'Driskill Mountain - 535 feet (163 m) above sea level is the highest point in the state. And New Orleans - 8 feet (5 m) below sea level is the lowest point in Louisiana.',
	'The territory of Louisiana can be divided into three types of regions: lowlands, terrace, and hills.',
	'Louisiana is the birthplace of American Jazz.',
	'After Alabama, Mississippi, and Tennessee; Louisiana is the fourth most religious state in the U.S.',
	'After New Orleans, Baton Rouge, the capital of Louisiana, is the second largest city in the state.',
	'The unemployment rate in Louisiana in August 2018 was 5% as compared to that of 1% of Alabama. In 2017, the GDP per capita for Louisiana was $52,602 as compared to that of Alabama, which was $43,37',
	'The first documented opera performed was staged at the Théâtre de la Rue St. Pierre in New Orleans, Louisiana on May 22, 179',
	'In 1959, Breaux Bridge, a city in the St. Martin Parish, was designated as the "Crawfish Capital of the World." This was done to honor the region which was known for its crawfish farming and cooking.',
	'The Louisiana black bear was designated the official state mammal of Louisiana in 199',
	'In 1861, during the Civil War, Louisiana left the Union. It rejoined the United States in 186',
	'The state\'s name derived from a Native American word that means "the land of many waters." The pronunciation is similar to the state\'s name.',
	'Idaho is sometimes referred to as the Gem State. One can find nearly 72 types of precious stones in the state.',
	"The state grows nearly one/third of America's potatoes. It is likely that the people living outside the state eat more of these starchy vegetables than the people in Idaho.",
	'Idaho produces other crops besides potatoes. The state is actually known as the Lentil Capital of the World. It is also known for having one of the largest hops farms in the United States.',
	"This state is known for having a canyon with an interesting name. The canyon is called Hells Canyon, and it's 7,900 feet deep. Keep in mind that this is deeper than the Grand Canyon.",
	'There are only a few places in the world where a bounty of star garnets can be found. One is in India and the other happens to be in Idaho.',
	'Women should be pretty proud of Idaho as it is the only state seal in the United States that was designed by a woman. The woman was Emma Edwards Green, and her design was chosen in 189',
	'It might sound a little strange, but it is against the law for a man to give his beloved a box of sweets that weighs more than 50 pounds.',
	'People really love to smile in Pocatello, Idaho. This obsession with smiles went so far that it became a law. Yes, it is illegal not to smile in public in this little region of the state.',
	'It is illegal for a person to fish while they are riding the back of a camel. Take that camel-riding fisherman.',
	'A person cannot sweep dirt from his or her house into the street. This is a law in Eagle, Idaho where cleanliness is definitely valued by the people in the city.',
	"Idaho's State Penitentiary is known as a haunted location. Talk about a double-whammy for those who might commit a crime.",
	"Heaven's Gate Lookout, in Idaho, is a location where you can see Washington, Montana, and even Oregon.",
	'This state is home to Atomic City, which was booming when the National Reactor Testing Station was active in the 70s. It is a desolate area with around 29 people now.',
	'There is a ski resort in McCall, Idaho that is home to the Brundage Bra Tree. The name is known throughout Idaho because it is where many women throw their bras as they ride a chairlift.',
	"One 1800's tale says there is a strange creature in Bear Lake, Idaho. It is known as the Bear Lake Monster, and this story has scared some kids in the state.",
	'This region is home to the highest navigable river in the world. The river is called St. Joe River, and it flows from an elevation of nearly 7,000 feet.',
	'This state offers the longest gondola ride in the world, so strap in and enjoy nature from above. The gondola is in the Silver Mountain Resort in Kellogg.',
	'Idaho actually holds a strange little Guinness World Record for a maze. Yes, the state is known for the longest straw bale maze, which is in Rupert.',
	'Someone paid $600,000 for a bull from Idaho. This was the most expensive bull ever sold. The cost was high because the Hereford bull weighed 1,410, and its lineage was impeccable.',
	"The Lake Coeur d'Alene boardwalk is 3,300 feet long and is known as the longest boardwalk in the world. This is definitely for all those who love to walk by the beach.",
	"Dog lovers should be interested in Idaho because it is home to the only dog-shaped B&B in the world. For those who want to visit the dog lover's paradise, it is in Cottonwood, ID.",
	'There is a small town in Idaho that has the longest main street in the United States. It is located in the City of Island Park.',
	"The Coeur d'Alene Resort is home to the only man-made 14th hole island. It definitely gives golfers a new experience.",
	"A gargantuan tree can be found at The Elk River. It is called the Idaho Champion Western Red Cedar Tree. It has an 18-feet diameter and it's over 170 feet tall.",
	"Idaho City can thank gold for its success. Yes, the city's economy boomed because of gold mining back in the 1860s.",
	"Idaho definitely stepped up to the plate when it came to structured sand dunes. Bruneau Dunes State Park is home to the country's tallest structure that stands 470 feet high.",
	'Idaho is home to the Niagara of the West. Yes, those who want to experience something like Niagara Falls could check out Shoshone Falls with its 212-foot drop.',
	'Those interested in birds of prey will be happy to know that Idaho has an awesome wildlife preserve, which is known for its dense population of falcons, eagles, and hawks.',
	"If you are interested in old churches, you may want to visit the Rathdrum. This city holds the state's oldest brick church called the Saint Stanislaus Church.",
	"North America has a lot of ski resorts, but it seems that Idaho beat other states to the punch. The first ski destination in the United States is Idaho's State Valley.",
	"The state's fruit is the Huckleberry, which makes sense because Huckleberry tea is good for starch digestion. Potatoes, the most popular vegetable in the state, are full of starch.",
	'The state\'s motto is "Esto Perpetua," which means "this is forever."',
	'13 is a very special number for this state. It is special because it is the 13th largest state (in terms of land area) in America.',
	'Idaho might not like the idea of private land. This is evident because a whopping 63 percent of the state is considered public land.',
	'Idaho may be known for potatoes, but it should be known for its trout, too. It is estimated that 85 percent of all the commercial trout sold in America comes from Hagerman Valley.',
	'Evil Knievel tried to jump over the Twin Falls in 197 He failed, but those interested in seeing the failed jump can check out the Twin Falls.',
	'The word "potato" was first used in the state\'s license plate back in 1928, and the state has not looked back since.',
	'One of the most celebrated winter celebrations called the Winter Carnival in McCall began in 192 It actually started because the locals were bored.',
	'There are about 4,522,506 acres of wild land in Idaho. Yes, this means there are no roads here.',
	'This region is home to the Treefort Music Fest, which is held in Boise. It is perhaps one of the most successful modern country music festivals in America.',
	'Arizona joined the union as the 48th state and hence it is the last of the contiguous states to do so.',
	"Arizona attained statehood on 14th February which coincides with Valentine's Day.",
	'Arizona, Utah, Nevada, New Mexico and California were a part of Mexico in some point in history. Arizona became a part of the U.S. after the country won the American-Mexican war in 184',
	'Arizona is famous the world over for the Grand Canyon, which is over a mile deep, 227 miles long and up to 18 miles wide.',
	'More than 50% of the state lies at an elevation of more than 4,000 feet above sea level.',
	'Humphreys Peak at 12,633 feet is the highest point in Arizona.',
	'The other popular nickname of the state: The Grand Canyon State.',
	'Phoenix, Arizona is the hottest city in the U.S.',
	'The largest Native American Reservation - the Navajo Nation — is found in Arizona. It reserves an area of 17,544,500 acres.',
	'The Cotton State also has the largest aperture solar telescope located at the Kitts Peak National Observatory.',
	'Arizona (except the Navajo Nation) and Hawaii do not observe Daylight Saving Time.',
	'Arizona also has the deepest dam in the world - the Parker Dam. The dam is 320 feet high of which 235 feet are below the riverbed.',
	'The state is home to the two largest man-made lakes in the United States - Lake Mead (largest) and Lake Powell (second largest).',
	'Pluto was discovered by Clyde Tombaugh at Lowell Observatory at Flagstaff on February 18, 193',
	'The amount of copper in the state Capitol Building Arizona is equivalent to 8 million pennies.',
	'The state, among all other states, has the highest percentage of land set aside and designated as Indian land.',
	'Cutting down a cactus in Arizona is a punishable offense and the maximum term in jail for the act could be 25 years. The saguaro cactus which is prevalent in Arizona takes a long time to grow.',
	'Copper was discovered in Arizona is 185',
	'The Grand Canyon National Park in Arizona sees 5 million visitors every year.',
	'Because of the ability to view stars away from city lights and pollution, Tuscan, Arizona is called the Astronomy Capital of the World.',
	"The Gila monster lives In Arizona desert. Gila monsters are the largest lizards native to the United States. They get their name from Arizona's Gila River basin, where they were first discovered.",
	'Arizona is the first of the three states with official state neckwear: the bola tie. The other two states that have the same official neckwear are New Mexico and Texas.',
	'The Spanish were the first European visitors who arrived in Colorado in the 1500s.',
	'The state was named after the Colorado River. In Spanish, Colorado means "colored red."',
	'Did you know that the name "cheeseburger" was trademarked by Louis Ballast of Humpty Dumpty Drive-In in Denver in 1935?',
	'According to the Colorado Department of Transportation, the Eisenhower Tunnel in Colorado is the highest vehicular tunnel in the world.',
	'The state is nicknamed the "Centennial State" because it joined the Union after a century of the United States Declaration of Independence.',
	'The capital city of Colorado is Denver, which also happens to be its most populous city. Denver is also known as the "Mile High City" because it sits at 5,280 feet above sea level—exactly one mile.',
	'Colorado is one of the three states in the U.S. which has its boundaries solely defined by lines of latitudes and longitudes. The other two states are Utah and Wyoming. For more clarity, see the map.',
	"It is the only U.S. state that lies entirely above 1000 meters' elevation. Thus, it is also the nation's highest state.",
	'The Summit of Mount Elbert (14,440 feet) in Lake County is the highest point in Colorado. It is also the highest summit of the Rocky Mountains.',
	"Almost 70% of the state's population resides in the eastern edge of the Rocky Mountains.",
	'Silver was discovered in Leadville in 187 The discovery marked the beginning of Silver Boom in the state.',
	"It is interesting to learn that Colorado entered statehood in 1876, exactly after 100 years of the nation's independence (1776).",
	'Colorado, women were granted the right to vote in 189',
	'The state also has the highest low point of any state in the U.S. The point (3,317 feet) is where the Arikaree River flows out of Yuma County, Colorado into the Cheyenne County, Kansas.',
	'Water that falls west of the Continental Divide flows to the Pacific Ocean while that which falls to the east heads to the Atlantic Ocean.',
	'The Colorado River with its origin in the mountains of Colorado and Wyoming provides water and hydroelectric power to at least 35 million people in the United States and Mexico.',
	'The gold rush happened in Colorado between 1858 - 5 The gold was first discovered in Colorado in 1858 in present day Englewood.',
	'After the formation of the territory of Colorado in 1861, William Gilpin was named the first governor of the state.',
	'More than a third of the land of Colorado is owned by the government of the United States. The government controls mining, grazing, and logging in this area.',
	'Colorado is also home to the United States Air Force Academy.',
	'Colorado Springs is the largest city in Colorado by area. The city is 1 mile above sea level and is situated at the base of one of the most famous American mountains, Pikes Peak.',
	"Blue Mesa Reservoir is Colorado's largest lake located entirely within the state. The reservoir has a surface area of 9180 acres.",
	'Colorado has stricter vehicle emission regulations than many other states in the U.S.',
	'Colorado was offered to host the Winter Olympics but its residents turned down the offer due to the lack of infrastructure, and some environmental concerns.',
	'The largest flat-topped mountain in the world - the Grand Mesa - is located in western Colorado. It has an area of 500 miles.',
	'By total land area (33,531 acres), the Denver International Airport is the largest airport in the United States. The airport also has the longest commercial runway in the United States.',
	'The only point in the United States where the boundaries of four states (Colorado, Utah, Arizona, and New Mexico) meet is termed as the Four Corners.',
	"Colorado's Mount Evans Scenic Byway is the highest paved road in North America.",
	'The first people arrived in New York around 10,000 B.C.',
	"Albany, the state's capital, was the site of the first European settlement in New York. Albany became the capital of the state in 179",
	'On April 30, 1789, George Washington was sworn in as the president of the United States at Federal Hall in New York City, New York.',
	'Niagara Falls, one of the most famous waterfalls in the world is located on the border of Ontario, Canada, and New York, United States.',
	'The Hudson River is named after the sailor Henry Hudson, who sailed into the state in 160',
	'Adirondack National park in New York is larger than any other national park in the U.S. (outside of Alaska). The park covers an area of 28 million acres.',
	'The United Nations is headquartered in New York City.',
	'New York State has had five constitutions. They were adopted in 1777, 1821, 1846, 1894 and 193',
	'New York Stock Exchange in New York City is the largest stock exchange in the world by Dollar volume.',
	'Canada is an important economic partner of the state.',
	'The United States got engaged in a military conflict with the British Empire between June 18, 1812, to February 18, 181 The New York - Canadian border was the central front of the war.',
	'Toilet paper was invented by Joseph Gayetty of New York City.',
	'The first American chess tournament was held in New York in 184',
	'Taughannock Falls is the tallest single-drop waterfall in the state of New York.',
	'The New York State Canal System consists of four canals - the Erie Canal, the Oswego Canal, the Cayuga-Seneca Canal, and the Champlain Canal.',
	'Manhattan, New York City, is home to the largest concentration of Chinese in Western Hemisphere. Here, 150,000 Chinese residents live in a 2 square mile plot of land.',
	'Hyde Hall Bridge is the oldest documented, covered bridge in New York State and the U.S. It was built in 1825 and is one of 29 historic covered bridges in New York State.',
	'The Metropolitan Museum of Art is the largest art museum in the United States and also one of the most visited art museum in the world.',
	'Fiorello La Guardia, acclaimed as one of the greatest mayors in American history, was born in New York City, New York. He was the 99th mayor of the city. LaGuardia Airport is named after him.',
	'New York is the largest north east state in both area and population.',
	'The Empire State Building measuring 1,454 feet from the base to antenna is a concrete example of human potential and engineering marvel.',
	'Almost all of the state north of the New York City is referred to as "Upstate New York" by the local residents.',
	'New York is the only state that borders both the Atlantic and the Great Lakes.',
	'Did you know that more than 4,000 farms have been lost to real estate development in the state since the 1980s?',
	'New York stands second only to Vermont for maple syrup production.',
	'Albany International Airport (ALB), established in 1928, is the oldest municipal airport in the US.',
	'After Washington, New York produces most apples in the country, followed by Michigan, Pennsylvania, California, Virginia, North Carolina, Oregon, Ohio and Idaho.',
	'Michigan is the only state in the U.S which consists of two peninsulas - the Lower (mainly an industrial area) and Upper Peninsulas (sparsely populated but mineral-rich).',
	'Michigan has an estimated 65,000 inland lakes and ponds. This puts any person in the state within a distance of six miles from a natural water source.',
	"Michigan has one of the world's longest suspension bridges - the Mackinac Bridge. It is five miles long and connects the Upper Peninsula to the other parts of the state.",
	"Michigan also has the nation's longest freshwater coastline (3,288 miles), and second-longest coastline of any U.S. state, after Alaska.",
	'The name of the state is derived from the word michi-gama (a Chippewa word), meaning "large lake."',
	'Michigan has its border with four (Superior, Huron, Michigan, and Erie) of the five Great Lakes (Superior, Michigan, Huron, Erie, and Ontario).',
	'Agriculture, manufacturing, and tourism are the major revenue generating industries of the state.',
	'The completion of the first railroad in Michigan took place in 1836 and the first air passenger service was flagged off in the state in 192',
	'Michigan is also known as "Motor City" because it is a hub for car manufacturing since the early 1900s.',
	"Mount Arvon, the state's highest point lies in the Upper Peninsula. More than 40% of the state is covered in water, which is more than any other state.",
	"The state is also home to 360 bird species including the rare Kirtland's warbler.",
	"The state is also home to the world's largest cement manufacturing plant. The Huron Portland Cement Company started producing cement in Alpena in 190",
	'Grand Rapids, the second largest city in Michigan after Lancing, was rated as one of the 20 best livable cities in the U.S.',
	'The state is also the birthplace of "Motown Records", which is one of the most successful soul music companies.',
	'With over 150, Michigan has the most lighthouses of any U.S. state.',
	'In 1846, Michigan became the first English speaking government to abolish the death penalty for all ordinary crimes.',
	'Michigan and Oregon are the only two states in the U.S. that offer 10 cents back for recycling a can.',
	'Traverse City, a city in Michigan, is known as "the cherry capital of the world."',
	"Michigan also has the world's largest limestone quarry located near Rogers City. It is operated by Michigan Limestone and Chemical Company.",
	'Michigan is the 16th largest chemical producing state in the U.S., generating $5 billion in annual payroll. Every light car produced in the U.S. contains more than $3,500 of chemical products.',
	'Apples are the largest and most valuable fruit crop in Michigan. The state has 13 million apple trees. Michigan is the third largest apple producing state in the U.S.',
	'The Detroit Institute of Arts (DIA) is regarded as among the top six museums in the United States. The museum has over 100 galleries. It is also amongst the most visited art museums in the world.',
	"Michigan has the world's largest weather vane. It is 48 feet tall with an arrow 26 feet long.",
	"Harriet Quimby, born in Arcadia, Michigan was the first woman to gain a pilot's license in the United States. In 1912, she became the first woman to fly across the English Channel.",
	'Comparatively, Michigan has more surface area than Illinois (one of its bordering states) but has less population.',
	'The name of the state originated from the name of the river "Ohio". The word "Ohio" in Seneca language means "the Great River."',
	'The average depth of the Ohio River is 24 feet. The deepest point, however, is 134 feet. That is in Louisville, KY.',
	"Ohio's flag is the only non-rectangular U.S. state flag. See the list of all U.S. state flags here…",
	"On August 05, 1914, the world's first electric signal was put in the street in Cleveland, Ohio.",
	'Thomas Edison, the legendary inventor, and businessman was born in Milan, Ohio.',
	"The nickname \"Buckeye State\" comes from the buckeye tree, which grew abundantly on the state's plains and hills. The tree's seeds resemble a buck's eye and hence the name of the tree.",
	'Majority of the population of Ohio is of white European ancestry.',
	'After Pennsylvania, Ohio has the second largest concentration of Amish living in the United State. After Lancaster County, Pennsylvania, Holmes County is the second largest Amish community in the world.',
	'With 35% of the adult population of Ohio suffering from Obesity in 2016, Ohio was ranked at the 19th spot by Adult Obesity Rate by State, 201',
	"Vinto is Ohio's smallest county by population.",
	'DeHart Hubbard from Cincinnati is the first African American athlete to win a gold medal in an individual event in the Olympics. In 1924, in Paris, he won the medal for the long jump.',
	'The Shape of the state resembles that of a heart. The slogan "The Heart of It All" was widely used to promote professional, educational and recreational opportunities in the state.',
	'The highest point in Ohio is Campbell Hill near Bellefontaine (it rises 1,549 feet above sea level) and the lowest point in the state is at the Ohio River near Cincinnati, 455 feet above sea level.',
	'Because of the movement of glaciers in the state thousands of years ago, the state is blessed with some of the most fertile agricultural land in the U.S.',
	"Ohio has nearly 75000 farms and more than 14 million acres. Farming being Ohio's number one industry contributes more than $100 billion to the state's economy.",
	'The fire in a coal mine set by its workers in 1884 near New Straitsville, southeast of Columbus, is still burning. The workers had a dispute with the mining company regarding their wages.',
	"The world's largest annual gathering of twins is organized in Twinsburg, Ohio. Find more details here.",
	'The Cincinnati Reds were the first professional baseball team.',
	'Columbus is the home of Wendy\'s. The very first Wendy\'s was located on the corner of 5th and Broad in downtown Columbus in 196 Dave Thomas named the restaurant after his daughter, Melinda "Wendy" Thomas.',
	"In 1862, after graduating from the Oberlin College (Lorain County, Ohio), Mary Jane Patterson, became the first African-American woman to gain a bachelor's degree.",
	'Did you know that the Great Serpent Mound in rural, southwestern Ohio is the largest serpent effigy in the world? It measures approximately 1,300 feet in length and ranges from one to three feet in height.',
	'Florida is a peninsula, meaning it is almost completely surrounded by water. Just two states border Florida, they are Georgia and Alabama.',
	'The Florida Keys, a group of about 1,700 tiny islands, is a famous tourist attraction of the state.',
	"The Walt Disney World Resort is in Florida. It is the planet's most visited and biggest recreational resort. It was established in 1971 and is about the same size as San Francisco, California.",
	"NASA's first communication satellite—Echo 1-was launched from Cape Canaveral, Florida on August 12, 196 It was a metalized balloon satellite acting as a passive reflector of microwave signals.",
	"The U.S. state of Florida is also home to the world's most dangerous tree - the Manchineel tree. All parts of the tree contain strong toxins. Mere contact with the sap from this tree can cause blisterson the skin.",
	'The most powerful rocket currently in service is the Falcon Heavy built by SpaceX. With its three booster cores and 27 engines, the rocket creates 13 million pounds-force of thrust at lift-off at sea level.',
	'Before the arrival of the Europeans in Florida, native American tribes have been living in the region for several thousand years.',
	'Between 1763 and 1783, Florida was ruled by the British. Formally, Florida became a part of the U.S. in 182',
	'It has the second longest coastline of all the contiguous state and it is also the only state that borders both the Gulf of Mexico and the Atlantic Ocean. Only Alaska has a longer coastline.',
	'The state also has the lowest high point (Britton Hill, at 345 feet above mean sea level) of any state.',
	'Florida was named Florida after the first contact to the land was made by a Spanish explorer Juan Ponce de Leon on April 2, 151 The explorer named the region, La Florida ("land of flowers").',
	'Central Florida is known as the lightning capital of the United States because the region experiences more lightning strikes than anywhere else in the country.',
	'The state also leads other states in the U.S. in tornadoes per area.',
	'June 1 to November 30 is the hurricane season in Florida and it is the most hurricane-prone state in the U.S. Hurricanes in the past have cost the state billions in damages.',
	'Florida has the highest percentage of people over 6',
	'There is no personal income tax in Florida.',
	'Florida is famous for the highest auto insurance fraud in the nation amounting to 1 billion in 2011',
	'Florida has the largest collection of Art Deco and Streamline Moderne buildings in both the United States and the entire world.',
	"Cuba is just 100 miles away from the southernmost tips of Florida's peninsula.",
	'Florida is ranked among the states with fastest-growing immigration population. The reason is the rapid growth in the tourism sector in the state due to the climate and the scenery of the Sunshine State.',
	'St. Augustine is the oldest continuously settled city in the United States. It is situated on a peninsula between two saltwater rivers. It was founded in 156',
	'Florida became the 27th state of the U.S. union in 184',
	'Florida is mostly flat, less than 100 feet above sea level.',
	"Lake Okeechobee is the largest freshwater lake in Florida. It is also the third largest freshwater lake (after Lake Michigan and Alaska's Iliamna Lake) located completely within the United States.",
	'Everglades National Park in Florida is the only place in the world which is home to both the American crocodile and the American alligator. It is a UNESCO World Heritage Site.',
	'Florida is the largest producer of citrus fruits in the United States. And the majority of the harvest of citrus fruits goes into juice making.',
	"Florida is the world's leading producer of grapefruit. Florida ranks second only to Brazil in global juice production.",
	'Castillo de San Marcos (a symbol of former Spanish power, a national monument now), built in 1672-95 in St. Augustine, Florida is the oldest masonry fort standing in the United States.',
	"The world's first scheduled passenger airline service operated between St. Petersburg and Tampa, Florida. The first flight on this route took place on January 1, 191",
	"Located near Tallahassee, Florida, the Wakulla Springs is the world's largest and deepest freshwater spring.",
	'Florida has more golf courses than any other U.S. state. The number exceeds 1,25',
	'There is only one state embassy in Washington and that is Florida House.',
	'Rip currents kill more people in Florida during an average year than hurricanes, tornadoes, and lightning combined.',
	'Florida has more toll roads and bridges than any other state in the Union.',
	"St Johns River, Florida's largest river is one of only a few major rivers that flow from south to north.",
	"The state also has the world's largest occupied wooden structure - The Belleview Biltmore Resort and Spa.",
	'Jacksonville, Florida is the largest city in the conterminous United States.',
	'Mechanical refrigeration was invented in Florida in 1851 by Dr. John Gorrie.',
	'In Florida, it is illegal to confine a pregnant pig to a cage.',
	'According to a law in Florida, it is mandatory for all doors to open outward in public buildings.',
	'Florida and California each produce fresh market tomatoes on 30,000-40,000 acres every year, which is equal to two-thirds of U.S. tomato acreage. Florida is the second largest tomato producing state.',
	'California is the home to the Silicon Valley (a region known the world over for high technology, innovation, and venture capital.)',
	'The first motion picture theater was opened in Los Angeles on April 02, 190',
	'California is the leading agricultural production house in the U.S. It also produces walnuts, pistachios, and almonds in the largest quantity in the U.S.',
	"The world's oldest male bodybuilder Jim Arrington is from Venice, California. He was born in 1932 and has been bodybuilding for the past 70 years.",
	'In 1949, the income from agriculture in the state was around $3 million. However, after some forty-five years in 1995, the same income grew to a whopping sum of $6 billion.',
	"Gold was discovered in California in 1848 at Sutter's Mill by James W. Marshall.",
	'Between 1st April 1940 and 1st July 1947, California gained 3,000,000 new residents through migration. This number is the largest of any kind of migration that ever took place in any of the U.S. states.',
	'Almost 5 million tourists were visiting California every year by the late 1990s and the travel and tourism industry generated approximately $75 billion annually.',
	'California is also the birthplace of semiconductor and the Internet, which brought digital revolution in the world. The first of the three astronomical observatories was also constructed in California.',
	'Did you know that an activist named Julia Butterfly Hill ascended a thousand-year-old redwood tree in California in December 1997 and remained there for a period of next two years until her demands were met?',
	"Pauline Potter from Sacramento, California is the world's heaviest woman alive. She weighed more than 600 lbs at the time of setting this world record.",
	'Arnold Schwarzenegger became the governor of California on October 07, 200',
	'California is divided into two regions, Upper California (Alta California) and Lower California (Baja California).',
	"The northern part of California is home to the iconic Golden Gate Bridge, the hills of San Francisco, and the state's capital Sacramento.",
	'In 1579, Sir Francis Drake visited California and took possession of the country in the name of Queen Elizabeth. He called the land New Albion.',
	'California is also home to the "giant sequoia" arguably the largest living organism on earth and the world\'s most massive tree. The estimated life-span of the tree is between 1800-2700 years.',
	'The Mojave Desert, at more than 25,000 square miles (65,000 square km), occupies one-sixth of the land area of California.',
	'Juan Rodriguez Cabrillo and his crew on September 28, 1542, were the first Europeans to enter California.',
	"The state produces a whopping 80% of the world's almonds. The state is also the nation's top producer of lemons, apricots, avocados, dates, figs, grapes, kiwi etc.",
	'After the gold rush, California was nicknamed the "Golden State."',
	'More than 6500 types of plants thrive in California.',
	'California has 41 mountains exceeding 10,000 m in height. It is the only state in the U.S. with an extensive seacoast, high mountains, and deserts.',
	'Central Valley in California is its single most productive region and one of the most productive in the world.',
	"California's Death Valley is North America's hottest desert and driest place. It is the lowest point in the western hemisphere.",
	'The largest surfboard measuring 183 m in length, 37 m in width and 41 m in thickness, was ridden by 66 people on Huntington Beach, California on 20 June 201',
	'Mount Whitney in California is the highest point in the U.S., outside of Alaska.',
	'California is also the powerhouse of one of the biggest film industry in the world - Hollywood. It is estimated that more films are shot in California than in any other state.',
	'The Grizzly bear is one of the states most notable symbol. It is found on both the state flag and seal. It was designated the official state animal in 195',
	'California has 6 of the top 10 most polluted U.S. cities. Majority of the pollution caused in the state is because of the high number of cars and trucks in the region.',
	'There is a Volkswagen car graveyard in California. The automotive giant had to buy back its vehicles worth billions of dollars after the emission scandal it faced.',
	'In March 2018, a California Judge ruled that coffee companies must provide a cancer warning because of the presence of a cancer-causing chemical produced in the roasting process.',
	'On April 18, 1906, an earthquake hit California which resulted in the death of nearly 3000 people and a loss of over $500 million in property damages.',
	'The state is also home to the world\'s tallest tree - Redwood. These trees can reach a height of over 300 feet. Particularly, a tree in the group named "Hyperion" is the tallest known living tree of allat 377 feet.',
	'About one-half of the states land is federally owned.',
	'Clear Lake is the largest natural lake wholly within the state. It has a surface area of 68 square miles.',
	'California is the most biologically diverse state in the U.S. It has more than 40,000 plant and animal species.',
	'The California grizzly bear (state animal) is now extinct.',
	'The California Indians were the original inhabitants of the state and are now in a limited number left in the region.',
	'California is referred to as the "Land of Milk and Honey". It is also known as the "El Dorado State", the "Grape State" and the "Golden State".',
	'California has two of the top ten most populous cities - Los Angeles and San Diego.',
	'Death Valley (at 4 million acres) in California is the largest U.S. National Park outside of Alaska.',
	'Interestingly, more Turkeys are raised in California than in any other state in the U.S.',
	'The California Gray Whale was designated as the State Marine Mammal in 197 It measures 40 to 50 feet in length and weighs between 30 to 40 tons.',
	'California is the only state in the U.S. to host summer (1932, 1984) and winter (1960) Olympics.',
	"The first McDonald's fast food restaurant was opened in San Bernardino, California in 194",
	"San Francisco Bay is one of the world's largest landlocked harbors and the Port of Oakland is one of the largest cargo ports in the United States.",
	'Furnace Creek in Death Valley is where the hottest temperature on Earth was recorded - 131 degree Fahrenheit (on July 10, 1913).',
	'The name Montana has a Spanish origin. The earliest Spanish settlers named the state "montaña" and it means mountain in Spanish. Montana is one of the nine mountainous states located in the western United States.',
	'The motto of Montana is "oro y plata" and this means "gold and silver" in Spanish. This motto is taken from the gold and silver deposits in the state. Gold was first discovered in Montana in 185',
	'Butte, Montana is called the "richest hill on planet earth". This is because of the rich mining history of this city.',
	'Montana has a very low population density. Of the state\'s 56 counties, 46 counties have average populations of just 6 people or less per square mile. This is why these counties are considered "frontiercounties".',
	'Montana has a large population of grizzly bears. This is probably why the grizzly bear is the state animal of Montana. An estimated 1800 grizzly bears are thought to be alive today.',
	'Montana has huge deposits of natural and mineral resources. Some of these resources are zinc, copper, silver, lead, oil, manganese, gold, timber and zinc.',
	'The largest city in Montana is Billings and the capital city is Helena. Billings is the only city in Montana to have a population of more than 100,000 people while approximately 75,000 people live in Helena.',
	'Montana has two popular nicknames. It is called the "Big Sky Country" and it is also called "The Treasure State".',
	'Montana is the 41st state to be formed in the U.S. preceded by South Dakota and succeeded by Washington. It was incorporated into the union on November 8, 188',
	'Montana is bordered by four American states; Wyoming, Idaho, South Dakota, and North Dakota. Montana also has a large international border with Canada.',
	'Montana has two important revenue-generating industries. They are mining and agriculture.',
	'Montana is the first state in the United States to elect a woman to Congress. Montana native, Jeanette Rankin was elected to Congress in 1916 and re-elected in 194',
	'Approximately 10,000 white pelicans migrate from the Gulf of Mexico to Medicine Lake, Montana every spring. These birds are striking because they have wingspans of about nine feet.',
	'There are more cattle than human beings in Montana. This is not surprising because the state is an important center of livestock farming.',
	'The largest snowflake ever observed was seen in Fort Keogh, Montana. This snowflake had an incredible diameter of 15 inches.',
	"One of the largest steer in world history rests in the O'Fallon Museum in Montana. This steer was about six feet tall and weighed an impressive 3,980 pounds.",
	'The Lewis and Clark expedition stopped at Travelers Rest in Lolo, Montana. This is the only site that has physical proof of the presence of these explorers.',
	'The city of Loma in Montana has the world record for the greatest temperature change in 24 hours. The temperature changed a whopping 103 degrees Fahrenheit moving from -54 degrees Fahrenheit to 49 degrees Fahrenheit.',
	'Montana has a unique feature called a triple divide. This triple divide allows water to flow into the Atlantic Ocean, The Hudson Bay (when considered an Arctic tributary) and the Pacific Ocean.',
	'In 1888, there were more millionaires per capita in Helena, Montana than any other city on earth. Most of these millionaires made their money from gold.',
	'Jordan, Montana is one of the remotest county seats in the United States. The nearest airport is 175 miles away while the nearest bus line is 85 miles away.',
	'Part of the Yellowstone National Park is located in Montana. The park experiences 1000-3000 earthquakes annually and is also home to supervolcanoes.',
	'Montana is large enough to contain six American states. You can fit the states of Delaware, Pennsylvania, New York, Maryland, Virginia and the District of Columbia into Montana.',
	'The Great Falls on the Missouri River is actually in Montana. It is the biggest waterfall on this river.',
	'Montana has a huge population of wild buffalo. You can see many of these animals at the National Bison Range close to Missoula.',
	"Montana has many lakes. In fact, the Glacier National Park is host to 250 lakes and many of them are within Montana's boundaries.",
	'Montana has the largest variety of mammals in the United States. Some of these animals are elk, bison (the largest land mammal in North America), grizzly bears and buffaloes.',
	'The tallest point in Montana is the Granite Peak. It stands at a height of 12,807 feet. It is the tenth highest point in the U.S.',
	'Montana has the largest population of golden eagles in the United States. You can see more eagles on a single day here than anywhere else in the United States.',
	'Montana is home to approximately 8,000 moose. This animal was once considered extinct but it is alive in well in Montana.',
	"Montana has one of the world's largest collections of dinosaur fossils. The Museum of the Rockies alone has 13 T-Rex specimens.",
	'Montana is home to one of the largest earth-filled dam in the world. This dam is the Fort Peck Dam located in northeast Montana.',
	'Montana has the largest County Park in the United States. This park is the Beaver Creek Park located in Hill County, Montana.',
	'The Yellowstone River runs through parts of Montana. This river is definitely the longest un-dammed river in the lower 48 states.',
	'Montana has a large population of native Americans. This state has at least eight federally recognized Native American tribes.',
	'Bannack is the first territorial capital of Montana. It is preserved as a ghost town today.',
	'The legendary Native American chief Sitting Bull has a town named after his daughter. The town of Ekalaka in Montana is named after the daughter of this famous chief.',
	'The smokestack in Anaconda, Montana is one of the tallest brick structures in the world. It stands 585 feet high.',
	'Only one gem from North America is included in the Crown Jewels of England. This is the Montana Yogo Sapphire.',
	"Montana is the home of the world's First International Peace Park. This park is a combination of Alberta's Waterton Lakes National Park in Canada and the Glacier National Park in Montana.",
	'Montana also has two popular slogans associated with its name - the "land of the shining mountains" and the "last best place." Montana has more than a 100 mountain ranges in its western half.',
	'In the area, it is slightly larger than Japan. It is also the largest landlocked U.S. state.',
	'The Clark Fork discharges the greatest volume of water of any river exiting the state.',
	'There are more than 3000 named lakes and reservoirs in Montana. These include the Flathead Lake, which is the largest natural freshwater lake in the U.S.',
	'Fork Peak Reservoir of Missouri River is the largest reservoir in the state.',
	'July 2007 was the hottest month ever recorded in Montana.',
	'The Desert Land Act of 1877, allowed settlement of Arid Lands and allocated 640 acres to settlers for a fee of $25 per acre and a promise to irrigate the land.',
	'For World War I, Montana contributed one of the highest numbers of soldier per capita of any state. It was higher than 25% of any other state on a per capita basis.',
	'Did you know that during World War II, almost 30 Japanese balloons landed in Montana? However, no damage to life or property resulted from these balloons.',
	'Montana is also home to the largest ICBM field in the U.S. covering 23,500 miles.',
	"Interestingly, Montana has given its three electoral votes to Republicans ever since the early 1950s with the exception of Lyndon Johnson's in 1964 and Bill Clinton in 199",
	'Fur trader Henri de Tonty, the Father of Arkansas, founded the first European Settlement on the Arkansas River.',
	'Arkansas is also the only state in North America where you can find a diamond field.',
	'iamonds State Park is the only in the world that allows the public to keep what they find. Interestingly, a 13-year-old girl from Missouri found a 93-carat diamond in Crater of Diamonds State Park.',
	'Arkansas has experienced only one major earthquake (the New Madrid earthquake of 1811-1812).',
	'The Caddo, Osage, and Quapaw are the three native tribes that lived in the Arkansas region.',
	'Except for Hawaii and Louisiana, Arkansas is the smallest state west of the Mississippi River. The Mississippi River is the second-longest river in the United States.',
	'Mount Magazine at 2,753 feet is the highest point in the state. It is situated in the Arkansas River valley.',
	'Bill Clinton was the governor of Arkansas before becoming the president of the U.S. He served two terms as the governor of the state.',
	'About half of Arkansas is covered under forest.',
	'The state is also home to some 300 native species of birds including bald eagles, blue jays, flycatchers and more.',
	'Arkansas does not have any federally recognized lands or tribes which existed within the state.',
	'Did you know that the first WalMart was opened in 1962 by Sam Walton in Rogers, Arkansas? It is interesting to note here that Walmart employes a staggering 3 million associates around the world.',
	'Rice, soybeans, and wheat are some of the important crops from the region.',
	'The poultry industry is one of the largest private employers in the state.',
	'Arkansas imports a lot of coal from Wyoming and thus uses it for producing energy to meet the demand of its inhabitants. The state also generates its own nuclear and hydroelectric power for the purpose.',
	'Tyson Foods, Inc., was one of the most important manufacturing firms in Arkansas. In some years, the company became one of the largest poultry and meat processing firm in the world.',
	'The first Arkansas State Highway Commission was appointed in 191',
	'In 1957, for the first time in the history of the state, nine African Americans were inducted into Little Rock Central High School. The school previously allowed only white students to attend.',
	'Despite the immense resources, Arkansas is one of the poorest states in the union. However, it is also one of the most generous states.',
	'Did you know that from 1874 to 1967, every Arkansas governor was a member of the Democratic Party?',
	'Did you know that Arkansas was ranked number 8th on the list of the states with most underprivileged children?',
	'Meteorites (the oldest known objects on the planet) weighing a couple of pounds or more fall within Arkansas about every year or two.',
	'The land of the Hot Springs National Park was set aside by the federal government for its use as an area for recreation. This was the first time this was done (way before the concept of a national parkexisted).',
	'Did you know that Little Rock (the state\'s capital) derives its name from a small rock formation on the south bank of the Arkansas River called the "Little Rock".',
	'Symbolizing the becoming of Arkansas as the 25th state of the union, Arkansas state flag has 25 stars.',
	'The state changed its nickname from "Land of Opportunity" to "The Natural State" in 199 This was done to promote tourism in the state."',
	'Did you know that Arkansas was part of the land acquired in the Louisiana Purchase?',
	'Arkansas was nicknamed "The Natural State" because it is famous for its natural scenic beauty, clear lakes and streams, and abundant wildlife.',
	'McClellan-Ker Arkansas River Navigation System (approximately 440 miles long) links Oklahoma and Arkansas to the Mississippi River. The project was completed in 197',
	'Arkansas sees long, hot summers and mild winters.',
	'At 1,460 miles long, the Arkansas River is the longest tributary in the Mississippi-Missouri River system.',
	'The eastern border of Arkansas is marked by Missouri, Tennessee, Mississippi, and the Mississippi River.',
	'The state has had several different nicknames in the past including: "The Wonder State", "The Bear State", and "The Toothpick State".',
	'The Mockingbird, the state bird of Arkansas, is also the state bird of other states including Texas, Florida, Tennessee, and Mississippi.',
	'Arkansas has over 600,000 acres of lakes and 9,700 miles of streams and rivers.',
	'Arkansas Post was the first territorial capital of Arkansas Territory from 1819 until 1821 when Little Rock was made the capital of the state.',
	'The University of Arkansas was founded in 187 The University had a gathering of eight students and three faculty members during the first year.',
	'In 1932, Arkansas elected the first women to serve a full term as a United States Senator. Her name was Hattie Caraway. She served for 14 years in the U.S. Senate.',
	"Mammoth Spring, with nine million gallons of water flowing hourly, is one of the world's largest springs.",
	'According to the Encyclopedia of Arkansas History & Culture, the highest temperature ever recorded happened on Aug. 10, 1936, with a whopping 120 degrees in Ozark.',
	'The state is named after the Connecticut River, which bisects the state and is a major river in the U.S. The Connecticut River flows through the center of the state, south to the Long Island Sound.',
	'Arriving in 1614, the first settlers in the state were the Dutchmen. The Dutch were fur traders who built a fort near present-day Hartford.',
	"On August 22, 1902, Theodore Roosevelt became the first U.S. president to ride in an automobile while in office. He stopped in Hartford's Pope Park and spoke to a gathering of about 10,000 workers.",
	'Bear Mountain in Salisbury in the northwest corner of the state is the highest peak in the state.',
	'In 1901, the first law regulating the speed of a motor vehicle was imposed in Connecticut. Initially, the law restricted the drivers not to exceed 12 mph.',
	'Connecticut is home of Samuel Colt, the inventor of the revolver. Connecticut was a leading manufacturer of guns and other arms.',
	'Did you know why Connecticut became known as the Provision State? It is due to the fact that during the revolutionary war, Connecticut sent many supplies and cannon to the Continental Army.',
	'Connecticut is nicknamed the "Constitution State" because "The Fundamental Orders of Connecticut" first adopted in 1639, served as a model for the U.S. Constitution.',
	'The Scoville Memorial Library in Connecticut is the oldest public library in the U.S. It was established in 1771 by a local man named Richard Smith.',
	'Hartford, the state\'s capital is called the "Insurance Capital of the World". In 1898, the first car insurance in America was issued at Hartford.',
	'In 1937, Connecticut became the first state to issue permanent license plates to cars.',
	'Connecticut has the highest personal income per capita (more than $70,000) in the country. However, the national average is $50,39',
	'In the area, only Delaware and Rhode Island are smaller than Connecticut.',
	'Between 1701 and 1874, the state had two capitals, New Haven and Hartford.',
	'In print since October 29, 1764, The Hartford Courant is the oldest continuously published newspaper in the United States.',
	'Hartford Public High School in Hartford, CT is the second-oldest public secondary school in the U.S. It was founded in 163',
	'New Haven, CT is the birthplace of George W. Bush, the only U.S. president born in the state.',
	'Edwin Land was born in Connecticut. This genius is credited with patenting 535 inventions, more than anyone except Thomas Edison (1,097 American patents).',
	'The "Constitution State" is the birthplace of the world\'s first practical helicopter. Designed by Vought Sikorsky, the VS-300 took flight at Stratford, Connecticut on September 14, 193',
	'Connecticut and Rhode Island have no county government. All county governments in Connecticut were abolished on October 1, 196',
	'In 1844, the first use of anesthesia was made in Connecticut by Horace Wells (Nitrous Oxide was used for the purpose).',
	'Noah Webster, the author of the first American English dictionary was born in West Hartford, Connecticut on 16th October 175',
	'Connecticut is one of the 48 contiguous states of the U.S.',
	'Lollipops were invented by George Smith of New Haven, Connecticut in 190 He had this idea of putting candy on a stick so that it is easier to consume. Lollipops were originally soft rather than hard.',
	"Did you know when and where the first hamburger in the United States was made? Learn that Louis' Lunch in New Haven, Connecticut is the first and the oldest still operating hamburger serving restaurantin the U.S.",
	'Yale University is located in New Haven, CT. Established in 1701, Yale University is the third-oldest institution of higher education in the United States.',
	'The first public tree planting program in America was conducted in New Haven, CT. The city was given the nickname "The Elm City" because the trees planted in the program were elms.',
	"Bridgeport is Connecticut's largest city followed by New Haven and Hartford.",
	"ESPN, the world's first sports cable channel was launched in Bristol, Connecticut in 197 With this fact also learn that Stamford, Connecticut is where the headquarters of World Wrestling Entertainment,Inc. is located.",
	'Lyme disease (spread by ticks in Northern Hemisphere) was first identified in 1975 in Old Lyme, Connecticut.',
	"John Haynes was Connecticut's first governor.",
	'Connecticut is one of the most densely populated states of the U.S.',
	'The first fully operational steel mill in America opened in Simsbury, Connecticut, in 172',
	'Mark Twain, an American writer, humorist, entrepreneur, publisher, and lecturer, wrote his famous adventure of Huckleberry Finn while in Hartford, Connecticut.',
	'Human settlement has been recorded in the region for at least 12,000 years ago.',
	'Did you know that between December 16, 1811, and late April 1812, over two-thousand earthquakes tremors occurred on the Mississippi River valley?',
	'Missouri was once an important hub for transportation and commerce in early America.',
	'The state is sometimes called "the Mother of the West."',
	'Did you know that a mail delivery system called the "Pony Express" existed between April 1860 and October 1861? The system used nearly 200 relief stations across what is now Missouri and California.',
	'Missouri has the largest beer producing plant in the country as it houses the maker of Budweiser beer-the Anheuser-Busch.',
	'Father Jacques Marquette and Louis Jolliet were the first Europeans to set foot on the land in 1673 while traveling down the Mississippi River.',
	'The "Missouri Gazette", the first newspaper in Missouri, was founded in Missouri in 1808 by Joseph Charles.',
	"Mark Twain, a world's renowned influential writer, was born in Missouri in 183",
	'In 1849, a cholera epidemic struck St. Louis, killing over 4,000 people.',
	'In 1911, a lightning strike on Missouri State Capitol that resulted in a fire destroyed the building completely.',
	'Missouri is named after the Missouri River, which was named after the indigenous Missouri Indians. The Missouri River is the longest river in the USA.',
	'Missouri is a landlocked state and borders eight states. Both Missouri and Tennessee have borders with the most number of states (8 states) in the U.S.',
	'The Mississippi and the Missouri River are the two longest rivers of the state.',
	'Missouri is one of the leading producers of transportation equipment.',
	'The University of Missouri is the first college in the world to grant a journalism degree. It opened on September 14, 190',
	'Missouri is a leading lead-producing state. The deposit of the metal fostered the first European settlement in the state in about 175',
	'The first parachute jump from a plane was also made at Jefferson Barracks, St. Louis on March 1, 191',
	'Union Station - the second-largest working train station in the U.S. behind the Grand Central terminal is in Kansas City, Missouri. It was built in 191',
	'The American Jazz Museum - the first museum solely dedicated to Jazz music is also located in Kansas City, Missouri.',
	'Big Springs, Missouri is one of the largest springs in the U.S. and the world. The spring has an average flow of 470 cubic feet (13,000 L) of water per second.',
	'Missouri is also known as the Cave State. It has more than 6,000 caves.',
	"Kansas City and St. Louis are home to more than half of the state's population.",
	'In 1673, French explorers Jacques Marquette and Louis Jolliet arrived in the region. They were exploring the Mississippi River in search of a route to the Pacific Ocean.',
	'Most of the area of the state was once covered with prairie grass, which earned the state its nickname - "The Prairie State."',
	'Barack Obama, a former U.S. president was elected while he was living in Illinois. Ronald Reagan is the only U.S. president born in Illinois.',
	'The word "Illinois" comes from the French version of an Indian word which means "men" or "warriors."',
	"Chicago's O'Hare International Airport, located in Illinois, is one of the world's busiest airports. It was ranked at the 6th spot in 2017 for the most number of passenger arrivals and departures.",
	'In 2016, Illinois was 6th among the top ten agricultural producing states in terms of cash receipts. California (1st), Iowa (2nd), Nebraska (3rd), Texas (4th) and Minnesota (5th).',
	'Illinois is considered a swing state because of its political stance.',
	"Chicago (a national railroad hub), one of the country's most prominent cities, lies in the state of Illinois.",
	"Charles Mound is Illinois' highest point. It is 1,235 feet (376 meters) above sea level.",
	"About three-fourths of the state's area is covered under farms. The rich black soil in the state helps in producing a lot of corn and soybean.",
	'Illinois has eleven (11) nuclear power reactors, more than any other state.',
	'The last episode of the award-winning "The Oprah Winfrey Show" was aired in Chicago. The show was the longest-running talk show (September 8, 1986, to May 25, 2011) in television history.',
	'Several nicknames of Illinois include "The Land of Lincoln" (also the Official State Slogan of Illinois), "The Prairie State", "The Corn State", "The Garden of the West", "The Sucker State and Egypt".',
	'Interestingly, the state quarter also has an image of resolute Lincoln with a book in his hand. (See the table at the end of the article.)',
	'The tallest man in the world was born in Alton, Illinois, on 22 February 191 When last measured on 27 June 1940, he was found to be 72 m (8 ft 11 in) tall.',
	'By population, Chicago, Illinois is the third largest city in the U.S.',
	'The Home Insurance Building in Chicago, which rose to 10 stories is the first metal-frame sky scrapper in the world. It was designed by engineer William LeBaron Jenney and was completed in 188',
	'Illinois is also considered to be one of the most politically corrupt states in the U.S. Six governors of the state have been charged with crimes and four of these were sent to prison.',
	"Boeing, the world's largest commercial aerospace company, is headquartered in Chicago, Illinois.",
	"Almost 33% of the population of the state have a bachelor's degree or higher.",
	"On April 15, 1955, the first McDonald's franchise in Des Plaines, Illinois, was opened.",
	'Among 50 U.S. states and District of Columbia, at 32%, Illinois has the second highest property tax rate. The highest property tax rate is in New Jersey (40%) while the lowest is in Hawaii at 27%.',
	'Illinois has the third highest total of Interstate routes and mileage. According to the Illinois Department of Transportation, "Illinois is at the heart of the country\'s interstate highway system."',
	'In 1814, The Kaskaskia Illinois Herald was the first newspaper that was printed in Illinois.',
	'In 1922, the first radio station broadcast was made in Illinois from Tuscola.',
	'Three rivers form the part of the boundary of Illinois - the Mississippi River, the Ohio River, and the Wabash River.',
	"After Wyoming and Kentucky, Illinois is the country's third-largest bituminous coal producer. It has one-fifth of the nations demonstrated coal reserves.",
	"Illinois generates 12% of the nation's nuclear power.",
	'The "Chicago Fire" also called the "Great Chicago Fire" started in Patrick and Catherine O\'Leary\'s barn on October 8, 1871, and killed between 200 and 300 people.',
	'Abraham Lincoln worked as a postmaster in New Salem, Illinois. He was appointed On May 7, 1833, and was the only U.S. President who had served as a postmaster.',
	'Morton, Illinois is dubbed as "the Pumpkin capital of the world".',
	"The Lincoln Park Zoo (founded in 1886) is one of the free zoos in the U.S. and among the nation's oldest public zoos.",
	'The term "Jazz" was coined in Chicago in 1914 by Benny Goodman and Gene Krupa.',
	"The Nabisco Factory in Chicago is the world's largest bakery, an 18,000,000 square feet production facility.",
	"The Chicago River is dyed green on St. Patrick's Day.",
	'Illinois had two different state capitals before Springfield - Kaskaskia (1809 to 1819) and Vandalia (1819 to 1839).',
	'Peoria is the oldest European settlement in Illinois.',
	'The first controlled atomic chain reaction took place on a squash court at the University of Chicago in 1942 under the direction of physicist Enrico Fermi.',
	'On Feb. 1, 1865, Illinois became the first state to ratify the 13th Amendment of the Constitution, which officially ended slavery and involuntary servitude.',
	'During the American Revolution, the Liberty Bell was moved from Philadelphia to Allentown. It was returned after the British evacuated Philadelphia.',
	'Benjamin Franklin and Bill Cosby are the famous Pennsylvanians.',
	'Pennsylvania is almost rectangular in shape.',
	"Before the establishment of Washington D.C. as the permanent capital of the United States of America; Philadelphia, Pennsylvania was the nation's capital between 1790 and 1800s.",
	"Did you know that on September 27, 1777, Lancaster served as the country's capital for just one day?",
	'The first computer in the world-The Electronic Numerical Integrator and Computer-was invented at the University of Pennsylvania in 194',
	'The first Zoo in the United States of America was opened in Philadelphia, Pennsylvania on July 1, 187',
	'And the first public library was founded by Benjamin Franklin in 1731 in Philadelphia.',
	'Philadelphia is also the place where the first American Flag was sewn in 1777 by Betsy Ross.',
	"In 1883, the City Hotel in Pennsylvania was the first building to be lit with Thomas Edison's three-wire system.",
	"The license plates on automobiles registered in Pennsylvania also have the state's official website's URL (www.pa.gov) on it. It is the first state of the 50 states to do so.",
	'The state also has the oldest gas station in America. It is situated in Altoona and is operational since 190',
	'Mount Davis (3,213 ft or 979 m) is the highest point in Pennsylvania.',
	'In Pennsylvania, Beef is the third most produced food by value.',
	'According to the USDA, National Agricultural Statistics Service, PA Office, between 2011 and 2012, there were 63,200 farms in Pennsylvania covering an area of 7,750,000 acres.',
	'Pennsylvania has more than 200 covered bridges, the most that any state has in the country.',
	'Developed by Dr. Jonas Salk, on February 1954, children of Arsenal Elementary School in Pittsburgh, Pennsylvania, received the first injections of the new polio vaccine.',
	'The Carnegie Museum of Natural History in Pittsburgh, PA, is home to the first complete Tyrannosaurus Rex skeleton ever found.',
	'Andrew Carnegie, the steel magnate, co-founded his first steel company near Pittsburgh, Pennsylvania. He sold his company for $480 million and later gave away more than $350 million in philanthropy.',
	'Philadelphia, the state\'s largest city is known as "the city of Brotherly Love" because of the religious tolerance of William Penn, the state\'s founder.',
	'Pennsylvania was nicknamed "The Keystone State" because of its geographical location among the thirteen original colonies.',
	'President Lincoln delivered his famous speech, "The Gettysburg Address", in Gettysburg, PA.',
	"The world's largest unboxing happened in Pennsylvania when a 3 year old kid was invited by Volvo Trucks to unbox their new model Volvo VNL.",
	'Pennsylvania has the highest concentration of Amish (known for simple living, plain dress, and reluctance to adopt many conveniences of modern technology) in the U.S.',
	'If you are looking for some fun and magic, visit the Ringing Rock Park in Bucks County. Here you can make the rocks ring by striking them with a hammer.',
	'Before the settlement of the Europeans in Texas, the land was home to Indians of Texas (Native American Tribes).',
	'The Texas State Fair is the largest in the U.S. It is estimated that almost 5 million people attended the fair in 201',
	'Lee Harvey Oswald, the assassin of John F. Kennedy (the 35th President of the United States, shot dead on 22 November 1963) was arrested in Texas Theater in Texas.',
	"The Texas State Capitol Building is taller than the nation's Capitol building and is the sixth tallest state capitol.",
	'Texas has the second highest number of professional sports teams. The only state that beats Texas in this regards is California.',
	'The highest national speed limit is observed in Texas on a stretch between San Antonia and Austin. Here it is allowed to drive up to 85 miles per hour.',
	'The Texas Rangers is the oldest statewide law enforcement agency in the U.S. It was established in 182',
	'Texas (695,662 km²) is about twice the size of Germany (357,376 km²).',
	'There are more than 5 million undocumented immigrants in Texas.',
	"In 1827, Seven Eleven opened its first chain in Dallas, Texas. It is also the first convenience store in the U.S. The chain was known as Tote'm Stores until it was renamed in 194",
	'Frozen Margarita was invented in Texas by Mariano Martinez in 1971',
	'Two doctors namely Frank Gerow and Thomas Cronin are credited with the invention of breast implants. In 1962, the first of these implants were done on Timmie Jean Lindsay.',
	'The Highland Park Village in Texas is the first planned shopping center in the U.S. It was constructed in 193',
	'Texas is the second most populous (after California) and second largest state in the U.S., after Alaska.',
	'The name Texas has originated from the word taysha, which means "friends" in the Caddo language.',
	"Less than 10% of Texas' land area is desert.",
	'Texas in the earlier times was ruled by several nations including Spain, France, and Mexico.',
	'Texas is the 28th state to join in the U.S. union.',
	"Prior to World War II: cattle and bison, cotton, timber, and oil were the four industries that shaped the state's economy.",
	'It is also a hot spot for the second largest group of fortune 500 companies in the U.S.',
	'The Rio Grande is the largest river in Texas.',
	'Rocks as old as 1600 million years have been recognized in Texas.',
	'Texas has the largest state capitol building and the highest speed limit of any state',
	'Austin, Texas was named after Stephen Austin, who established the state\'s first American colony. Texas is named after the Indian word "Tejas" meaning "friends" or "allies".',
	'The state\'s nickname the "Lone Star State" comes from the fact that it was once an independent country with its own single star flag.',
	'Texas is the largest of the 48 contiguous states of the U.S., and the second largest overall, behind Alaska.',
	'Texas is the leading producer of oil, natural gas, and sulfur in the country.',
	'Two of the United States presidents were born in Texas. Lyndon Johnson and Dwight Eisenhower.',
	'rom north to south the state extends approximately 1600 kilometers and the same distance from east to west.',
	'Texas is generally divided into East and West. The eastern part of the state is known for cotton while the western part of the state is characterized by cattle ranching.',
	"The Astrodome is the world's first multi-purpose, domed sports stadium, located in Houston, Texas. It was opened on April 9, 196",
	'Spanish explorer Alonso Alvarez de Pineda was the first European to visit Texas in 191',
	'Between 1836 and 1845, Texas was an independent nation. It is the only state to enter the United States by treaty instead of territorial annexation.',
	'Six flags have flown over Texas (Spanish, French, Mexican, Republic of Texas, Confederate, and United States).',
	'George W. Bush, the ex-president of the United States of America (between 2001 and 2009), was the governor of Texas for two terms.',
	'Texas has more species of birds than any other state, which includes screech owls and hummingbirds.',
	'Texas has more cattle than any other state in the country.',
	"Texas also has one of the world's largest wind-power-producing farms.",
	'There were nearly 297,000 oils well in Texas as of February 201',
}
