local FunFact = FunFact
local module = FunFact:NewModule('FactList_VideoGames')
module.desciption = 'Video Games facts'

module.Facts = {
	'The first commercially successful video game was "Pong," created by Atari in 1972 as a simple table tennis simulation.',
	'Nintendo was originally founded as a playing card company in 1889, long before they entered the video game market.',
	'The best-selling video game of all time is "Minecraft," with over 200 million copies sold across all platforms.',
	'The longest video game marathon on a single game is 35 hours and was achieved by Carrie Swidecki in 2019, playing Just Dance.',
	'The most critically acclaimed game of all time is "The Legend of Zelda: Ocarina of Time," which has a Metacritic score of 99/100.',
	'The first game with a hidden "Easter egg" was "Adventure" for the Atari 2600. The secret room displaying the creators name, Warren Robinett, was hidden in the game.',
	'The character Mario from Nintendo\'s Mario series was originally known as Jumpman in the 1981 game "Donkey Kong."',
	'The highest-grossing entertainment release is not a movie but a video game: "Grand Theft Auto V," which earned $1 billion in its first three days.',
	'The term "gamer" was first used in 1985.',
	'The first gaming console to use CDs was the Amiga CD32, released in 1993.',
	'The longest-running MMORPG is "Ultima Online," launched in 1997 and still active today.',
	'The largest in-game world is "No Mans Sky," with over 18 quintillion procedurally generated planets.',
	'In "Pac-Man," the highest possible score is 3,333,360 points, and it was first achieved by Billy Mitchell in 1999.',
	'The first video game to feature speech synthesis was "Berzerk" in 1980.',
	'The original name of "Sonic the Hedgehog" before being finalized was "Mr. Needlemouse."',
	'The popular sandbox game "Minecraft" was originally called "Cave Game" during its early development stages.',
	'The Konami Code (up, up, down, down, left, right, left, right, B, A) is one of the most famous cheat codes and was first used in the game "Gradius" in 1986.',
	'The first female video game character to gain widespread popularity was Ms. Pac-Man, introduced in 1982.',
	'The game "Tetris" was created by Russian software engineer Alexey Pajitnov and has sold more than 170 million copies.',
	'The largest LAN party ever held had 22,810 participants and took place at DreamHack in Jonkoping, Sweden, in 2013.',
	'The first game to feature a save function was "The Legend of Zelda" for the NES, released in 1986.',
	'PlayStation 2 is the best-selling console of all time, with over 155 million units sold worldwide.',
	'The first-ever strategy video game was "Spacewar!" developed in 1962 at MIT.',
	'The "Final Fantasy" series got its name because it was supposed to be Square’s last game, as the company was facing bankruptcy.',
	'In "World of Warcraft," the total amount of playtime for all players combined is over 6 million years.',
	'The original character design for "Lara Croft" in Tomb Raider featured a braid, but it was removed due to technical limitations.',
	'The game "Doom" from 1993 is considered to have popularized the first-person shooter genre.',
	'In "Super Mario Bros.," the bushes and clouds are just recolored versions of each other to save memory.',
	'The Sims" is the best-selling PC game franchise of all time.',
	'The fastest completion of "Super Mario Bros." is 4 minutes and 55 seconds.',
	'The first game to feature stealth gameplay was "005" in 1981.',
	'The creator of "Pokemon," Satoshi Tajiri, was inspired by his childhood interest in collecting creatures.',
	'The highest score ever achieved in "Donkey Kong" is 1,247,700 points.',
	'The first virtual reality headset was created in 1968 and was so heavy it had to be suspended from the ceiling.',
	'The term "MMORPG" (Massively Multiplayer Online Role-Playing Game) was coined by Richard Garriott, the creator of "Ultima Online."',
	'The longest single game of "Football Manager" lasted 154 seasons, spanning over 173 days of total game time.',
	'The most expensive video game ever developed is "Grand Theft Auto V," with a total cost of $265 million.',
	'In the game "Portal," the cake is a lie.',
	'The game "Angry Birds" was Rovio’s 52nd attempt at creating a successful game.',
	'The voice actor for Mario, Charles Martinet, also voices Luigi, Wario, and Waluigi.',
	'The infamous "Blue Screen of Death" in Windows has its own color code - #0000FF.',
	'Blizzard Entertainment originally started as a small company called Silicon & Synapse.',
	'The first eSports tournament was held in 1972 at Stanford University for the game "Spacewar."',
	'The game "League of Legends" once recorded 8 million concurrent players worldwide.',
	'The character "Link" from "The Legend of Zelda" series was named after the link between the past and the future.',
	'In 1993, SEGA released "Sega Channel," a game streaming service through cable television.',
	'The co-founder of Atari, Nolan Bushnell, also founded the Chuck E. Cheese’s Pizza Time Theatre chain.',
	'The highest grossing single arcade game of all time is "Pac-Man."',
	'The oldest known cheat code was used in the game "Manic Miner" for the ZX Spectrum in 1983.',
	'The first game to be played in space was "Starcraft," taken aboard the Space Shuttle Discovery in 1999.',
	'The game "Half-Life 2" was the first to require online activation via Steam in 2004, marking a significant change in digital game distribution.',
	'The longest video game title is "Supercalifragilisticexpialidocious: The Video Game," based on the popular song from the Disney film "Mary Poppins."',
	'The first 3D game was "3D Monster Maze," released in 1981 for the Sinclair ZX81.',
	'The character of Master Chief from the "Halo" series was never shown without his helmet in the original trilogy to help players immerse themselves as the character.',
	'The "Guitar Hero" series was inspired by a Japanese game called "GuitarFreaks."',
	'In the game "Deus Ex," the Twin Towers are missing from the New York City skyline. The developers explained it as a terrorist attack, but it was actually due to memory limitations.',
	'The largest collection of video games is owned by Antonio Monteiro, who owns more than 20,000 games.',
	'The most expensive virtual item ever sold was a "Club Neverdie" in the game "Entropia Universe," sold for $635,000.',
	'The game "Bioshock" was inspired by the works of Ayn Rand, particularly her philosophy of Objectivism.',
	'The game "Eve Online" features one of the largest virtual universes, with over 5000 solar systems and tens of thousands of players sharing the same space.',
	'The first game to feature blood and gore was "Splatterhouse," released in 1988.',
	'The character "Kirby" was named after John Kirby, the lawyer who defended Nintendo in a lawsuit against Universal Studios over "Donkey Kong."',
	'The game "Mass Effect" was the first video game to have a fully integrated orchestral score.',
	'The most critically panned game of all time is "Big Rigs: Over the Road Racing," which received almost universally negative reviews.',
	'The game "Borderlands 2" has a gun called "Conference Call" that is known for its unique shooting pattern resembling a conference call.',
	'The puzzle game "Tetris" has been used in various scientific studies, including research on treating PTSD.',
	'The game "Mortal Kombat" prompted the creation of the Entertainment Software Rating Board (ESRB) due to its violent content.',
	'The longest-running sports video game series is "Madden NFL," first released in 1988 and updated annually.',
	'In "The Elder Scrolls V: Skyrim," the dragon shouts were created by reversing the word "Dragon" in various languages.',
	'The game "World of Goo" was created by just two people, showcasing the potential for independent game development.',
	'The first game to feature a cooperative multiplayer mode was "Spacewar!" in 1962.',
	'The character "Pac-Man" was designed to look like a pizza missing a slice, according to its creator.',
	'The first game known to have a licensed soundtrack was "Tony Hawks Pro Skater 2."',
	'The game "Silent Hill" used fog extensively to mask the limitations of the PlayStation’s hardware.',
	'The game "Shadow of the Colossus" is often cited as an example of video games as an art form due to its minimalist design and storytelling.',
	'In the game "Metal Gear Solid 3," you can defeat a boss by not playing the game for a week, or by changing the system clock forward.',
	'The game "Portal" was a student project called "Narbacular Drop" before Valve hired the team and developed it into the full game.',
	'The highest-grossing game of all time is "Space Invaders," earning over $13 billion since its release in 1978.',
	'The first female protagonist in a video game was Samus Aran from "Metroid," released in 1986.',
	'The first game to be played in outer space was "Starcraft," which was taken aboard the Space Shuttle Discovery in 1999.',
	'The game "Crysis" (2007) was so graphically advanced that it became a benchmark for testing high-end computer performance for years.',
	'In "Super Mario 64," Mario can lose his cap, and if you finish the game without it, hell be capless in the final cutscene.',
	'The first console to offer online connectivity was the Sega Dreamcast in 1999.',
	'The "Animal Crossing" series was originally developed for the Nintendo 64 in Japan before it moved to the GameCube.',
	'The creators of "Pokemon," Game Freak, started as a self-published video game magazine.',
	'The "Fallout" series was originally set to use the GURPS system for its RPG mechanics, but due to licensing issues, they created the SPECIAL system instead.',
	'The original concept for "The Legend of Zelda" involved a microchip that players would move between past and future versions of the game world.',
	'The arcade game "Dragons Lair" (1983) was one of the first to use laserdisc technology, offering superior graphics compared to its contemporaries.',
	'In "Diablo II," players can find the chat gem, whose purpose has been the subject of much speculation but is essentially a fun, mysterious feature with no real use.',
	'The Konami Code was used in many games and could unlock anything from extra lives to secret characters or levels.',
	'The voice actor for the iconic villain Sephiroth from "Final Fantasy VII" is also the singer of the band NSYNC, Lance Bass, in the English version of Kingdom Hearts.',
	'The game "Assassins Creed" was initially conceived as a spin-off of the "Prince of Persia" series.',
	'In "Batman: Arkham Asylum," the developers included a secret room outlining plans for its sequel, "Batman: Arkham City," which remained undiscovered for several months.',
	'The fastest-selling PC game until 2020 was "Diablo III," selling over 3.5 million copies in the first 24 hours.',
	'The game "Donkey Kong" was originally meant to be a "Popeye" game, but due to licensing issues, the characters were changed to Mario, Donkey Kong, and Pauline.',
	'The infamous "Red Ring of Death" on Xbox 360 consoles cost Microsoft more than $1 billion in extended warranties and repairs.',
	'In "The Witcher 3: Wild Hunt," there are over 36 different ending variations depending on the players choices throughout the game.',
	'The game "Minecraft" was developed in just six days before its public release in 2009.',
	'The "Mass Effect" trilogy has over 40,000 lines of dialogue, more than most feature films.',
	'The highest score in the original "Pac-Man" game is 3,333,360 points, achieved by completing all 256 levels with a perfect score without dying once.',
	'The first game to feature a double jump was "Dragon Buster" in 1985.',
	'In the game "Hitman: Blood Money," you can cause a character to slip on a banana peel, an homage to classic slapstick comedy.',
	'The original design for "Sonic the Hedgehog" included fangs and a human girlfriend named Madonna, but these were removed to make the character more kid-friendly.',
	'The game "Age of Empires" was originally titled "Dawn of Man" and focused more heavily on building a civilization from the Stone Age onwards.',
	'The longest game title is "Peter Jacksons King Kong: The Official Game of the Movie," which is 50 characters long including spaces.',
	'In "World of Warcraft," theres a character named Haris Pilton, a parody of Paris Hilton, who sells expensive bags.',
	'The PlayStation 2s startup screen changes depending on the number and length of games played; the towers represent save files, and their height reflects playtime.',
	'The action-adventure game "Shadow of the Colossus" has no towns, dungeons, or even other characters to interact with, focusing solely on the colossi battles.',
	'The creator of the "Game Boy," Gunpei Yokoi, also invented the D-pad (directional pad) found on nearly all modern game controllers.',
	'The first game to receive the rating "Mature" from the ESRB was "Mortal Kombat" due to its violent content and realistic graphics.',
	'The popular game "Fortnite" was originally launched as a cooperative survival game before the addition of its battle royale mode.',
	'In "Super Mario Bros.," the bushes and clouds use the same sprite, just colored differently, to save memory.',
	'The game "Silent Hill" uses fog to cover the limitations of the PlayStations hardware, creating an eerie atmosphere.',
	'The first game to feature an adjustable difficulty setting was "Space Invaders Part II" in 1979.',
	'Nintendo’s iconic character, Mario, has appeared in over 200 games.',
	'The PlayStation 1 was originally conceived as a CD-ROM add-on for the Nintendo SNES.',
	'In "Metal Gear Solid 3: Snake Eater," players can defeat a boss by saving the game during the battle and waiting a week, or by setting the system clock forward, simulating the boss dying of old age.',
	'The first game to be banned in the U.S. was "Death Race" in 1976 due to its violent content.',
	'The original "Resident Evil" game was initially conceived as a remake of an earlier Capcom game called "Sweet Home."',
	'The game "Portal 2" has an interactive credits sequence allowing players to "shoot" the names with the portal gun.',
	'The oldest commercial graphical adventure game is "Mystery House" released by On-Line Systems in 1980.',
	'The first known Easter egg in a video game was found in "Adventure" for Atari 2600, where the designer hid his name.',
	'In "The Sims" series, the gibberish language that the characters speak is called "Simlish."',
	'The highest-grossing arcade game of all time is "Pac-Man," released in 1980.',
	'The game "Zork," one of the earliest text-based adventure games, was developed in the late 1970s at MIT.',
	'The character of Cloud Strife in "Final Fantasy VII" was originally envisioned as a detective with a slicked-back hair design.',
	'The original "Doom" game from 1993 has been ported to run on a variety of devices including calculators, printers, and even ATMs.',
	'In "Assassins Creed II," all the assassination targets are based on real historical figures who died in the same year the game takes place.',
	'The first console to have a modem for online play was the Sega Genesis with the Sega Channel service.',
	'The arcade game "Gauntlet" (1985) was one of the first games to feature voice synthesis, with the game offering voice prompts such as "Wizard needs food badly."',
	'The game "Civilization" was almost single-handedly created by Sid Meier, and the box originally stated, "Sid Meiers Civilization" to emphasize its creator-led development.',
	'The character "Sonic the Hedgehog" was designed as Sega’s mascot to compete with Nintendo’s Mario.',
	'The longest videogame marathon is 572 hours and was achieved by Carrie Swidecki on July 11-17, 2015, playing "Just Dance."',
	'In "Pokémon Red and Green," the creature Rhydon was the first Pokémon ever created by the game’s designers.',
	'The first color arcade game was "Galaxy Game," a version of "Spacewar!," released in 1971.',
	'The first game to allow music from a CD to be played in-game was "Monster Rancher" on the PlayStation.',
	'The game "League of Legends" was inspired by a custom map for "Warcraft III" called "Defense of the Ancients."',
	'The character Link from "The Legend of Zelda" is left-handed in most games, but hes right-handed in the Wii version of "Twilight Princess" to match the majority of players dominant hand.',
	'The first game to feature a track editor was "Excitebike" for the Nintendo Entertainment System in 1984.',
	'The term "sandbox game" refers to games that allow players to explore and interact with a virtual world freely, with the first known use of the term being in 1984.',
	'In "Grand Theft Auto: San Andreas," there are hidden dialogues that can be triggered under specific circumstances, adding depth to the characters and world.',
	'The largest gaming tournament prize pool was over $34 million for "The International 2019" Dota 2 championship.',
	'In "Mario Kart 64," the character Toad’s voice was provided by the game’s composer, Kenta Nagata.',
	'The first game to feature a female protagonist was "Ms. Pac-Man" in 1981.',
	'The game "Baldur’s Gate" (1998) is credited with reviving the computer RPG genre in the late 90s.',
	'The first recorded instance of a game demo was for the game "Spacewar!" in 1962 on the PDP-1 computer at MIT.',
	'The game "Quake" was one of the first games to support full 3D graphics and is often credited with popularizing the genre.',
	'In "Super Mario Galaxy," the water droplets on the screen were rendered using a technique called metaballs, which was advanced for its time.',
	'The most expensive video game ever made, including marketing costs, is "Call of Duty: Modern Warfare 2," which had a budget of around $250 million.',
	'The term "moba" (Multiplayer Online Battle Arena) was popularized by the game "League of Legends," despite the genre existing before its release.',
	'The game "Minecraft" features a rare mob called Enderman, which is inspired by the internet meme "Slender Man."',
	'In "Halo 3," if you zoom in on a certain spot on the Halo ring, you can hear a phone ringing.',
	'The first known use of a microphone in a game was in "Seaman" for the Sega Dreamcast, where players could talk to a virtual pet.',
	'The game "Elder Scrolls II: Daggerfall" has one of the largest game worlds ever created, with a size of about 62,394 square miles.',
	'The infamous "No Russian" mission in "Call of Duty: Modern Warfare 2" allows players to skip it due to its graphic content.',
	'In the game "Batman: Arkham City," Calendar Man will acknowledge if you visit him on certain holidays with unique dialogue.',
	'The PlayStation 1s startup sound was composed by Takafumi Fujisawa and is meant to convey a sense of reliability and entertainment.',
	'The game "Manhunt" is one of the most banned games worldwide due to its graphic violence.',
	'The game "Psychonauts" has a hidden room that wasnt discovered until years after the games release.',
	'The original concept for "Pikmin" involved a game where you control a group of Mario-like characters.',
	'The first multiplayer game played in space was "StarCraft," played by astronauts on the International Space Station.',
	'In "The Legend of Zelda: Wind Waker," the character’s facial expressions are influenced by traditional Japanese Kabuki theater.',
	'The voice actor for the "God of War" series Kratos, Christopher Judge, also played Tealc in the TV series "Stargate SG-1."',
	'The game "Witcher 3: Wild Hunt" contains over 450,000 words of dialogue, more than some novels.',
	'The game "L.A. Noire" was the first video game to be shown at the Tribeca Film Festival.',
	'The original "Street Fighter" game had a special pressure-sensitive arcade button to determine the strength of the players punch.',
	'The "Luigi’s Mansion" game was originally developed as a 3D game for the Nintendo GameCube.',
	'In "Red Dead Redemption," the horse testicles shrink in cold weather as a detail to realism.',
	'The creator of the "Super Smash Bros." series, Masahiro Sakurai, performs most of the character voice effects himself.',
	'The game "Journey" became the fastest-selling game on the PlayStation Store shortly after release.',
	'In "Destiny," the infamous loot cave was an area where players could shoot into a cave for endless enemy spawns and was later patched due to its exploitation.',
	'The game "SimCity" was originally developed as a feature in "Raid on Bungeling Bay" to create cities for bombing, but the creator found building cities more fun.',
	'The arcade game "Pole Position" was one of the first games to feature real-life track, the Fuji Speedway in Japan, as its circuit.',
	'The game "Plants vs. Zombies" was initially called "Lawn of the Dead," a pun on the movie "Dawn of the Dead."',
	'In "World of Warcraft," a glitch in the early game led to a virtual plague called the "Corrupted Blood incident," studied by epidemiologists for its implications on understanding real pandemics.',
	'The game "Borderlands 2" has a character named Michael Mamaril, who was added to honor a fan of the series who passed away.',
	'The game "Dragon Age: Inquisition" has a total playtime of over 200 hours to complete everything.',
	'In "Final Fantasy IX," there is a hidden treasure chest that wasnt discovered until 13 years after the games release.',
	'The game "Team Fortress 2" has a hat economy, with some virtual hats being sold for thousands of dollars.',
	'In "Super Mario Galaxy 2," theres a planet shaped like Yoshi’s head, a nod to the beloved character.',
	'The game "Counter-Strike" started as a mod for "Half-Life" before becoming a successful standalone game.',
	'In "Portal," the cake recipe recited by GLaDOS includes an ingredient from a can of "compressed air."',
	'The game "Duke Nukem Forever" holds the record for the longest development time for a video game, taking 15 years.',
	'In "Final Fantasy VII," the city of Midgar is inspired by New York City.',
	'The game "Far Cry 2" includes a realistic fire propagation system, allowing fires to spread across grass and trees.',
	'In "Skyrim," you can find a reference to "The Lord of the Rings" with a ring found on a skeletal arm in a pool, similar to Gollums obsession with the ring.',
	'The game "Spore" allows players to create and evolve their lifeform, with over 500 million creations made by players.',
	'In "Mass Effect 2," you can find a planet that references the movie "Pitch Black" with a description of a dangerous creature lurking in the dark.',
	'The game "GoldenEye 007" for the Nintendo 64 was one of the first games to feature a zoomable sniper rifle.',
	'In "The Last of Us," the games fungus-based infection is inspired by the real-world Cordyceps fungus, which takes over insects.',
}
