local FunFact = FunFact
local module = FunFact:NewModule('FactList_WoW')
module.desciption = 'Facts about this game called World of Warcraft'

module.Facts = {
	-- Real-world WoW facts (celebrities, news, culture)
	'Colleen Lachowicz during her run for state Senate in Maine came under political attack for having played WoW and therefore being out-of-touch with reality and living in a "fantasy world." Colleen ending up winning the Senate seat.',
	'The United States Air Force Pararescue (PJs) use the sound bite of "Leeroy Jenkins" from WoW to notify themselves of an upcoming medevac mission.',
	'When Uwe Boll tried to obtain filming rights for a WoW movie Blizzard said "We will not sell the movie rights, not to you…especially not to you."',
	"'Red Shirt Guy' who stumped a panel of WoW devs during a Q&A at BlizzCon, 2010, after asking about an inconsistency in the lore. Later, an NPC was introduced into the game who wore a bright red shirt and was named Wildhammer Fact Checker.",
	'Ben Schulz (more infamously known as Leeroy Jenkins) had a written role in the script for the Warcraft movie. Pvt Jenkins was to break rank "with a zealous battlecry" and be immediately cut down by orcs. The part was ultimately cut from the movie.',
	'The author of "The Martian" was also a computer programmer for Warcraft 2',
	"Trey Parker hated the episode 'Make Love, Not Warcraft' so much, he tried getting the executive producer to pull the show from airing. The episode is regarded as one of the best in the series.",
	'Robert Hohman quit his job to play WoW full-time for a year before going on to co-found and run Glassdoor.',
	'Chinese prisoners are forced to farm WoW gold - there are thought to be 100,000 full-time gold farmers in the country.',
	'By 2012 the players of WoW had collectively spent about 6 million years worth of time playing the game, about as much time as humanity has spent evolving as a species',
	"A 'virtual virus' was released into WoW that infected players and spread throughout the whole universe. The behaviour of the online players was so lifelike that the incident was studied by scientist to prepare for a real life Pandemic.",
	'A 12-yr old Norwegian boy managed to survive a moose attack using tactics learned from playing WoW',
	'A boy in China committed suicide by jumping off of a 24-storey building after a 36-hour video game marathon. His suicide note told about his addiction to Warcraft III and his intent to join his fellow players in heaven.',
	'The director of Moon, Warcraft and the recently released Muted is the only son of the legendary singer David Bowie',
	'Greg Street who earned a PhD in marine science, he latter became the lead designer of WoW.',
	"The director of 'Warcraft' is David Bowie's son.",
	'Collectively speaking, humans have spent longer playing WoW than they have existed, as a species separate from chimpanzees (5.93 million years).',
	'Robin Williams was a self-described hardcore gamer and enjoyed playing Warcraft. After his death, Blizzard created an NPC in WoW to commemorate him.',
	'Daler Mehndi, the pop singer that inspired the WoW Draenei dance, has been accused of human trafficking.',
	'in 2005 Corrupted Blood caused players to catch a disease from nearby infected, which spread so rapidly that the "major towns and cities were abandoned, leaving urban areas filled to the brim with corpses, and the city streets white with the bones of the dead.',
	'The CDC uses the "Corrupted Blood" incident in WoW as a study aid on bioterrorism.',
	'Duncan Jones, Warcraft director and son of David Bowie, graduated from College of Wooster in Ohio.',
	"Warcraft-based song called 'Loktar Ogar' by revered black metal band 'Rotting Christ' - all lyrics are actual orcish.",
	"Henry Cavill didn't answer a call from Zack Snyder, who was calling to let him know he got the part for Man of Steel, because he was too busy playing WoW.",
	-- In-game developer secrets and lore facts
	"The Karazhan Crypts contain unused developer test rooms like 'The Upside-down Sinners', filled with hanging corpses underwater.",
	'In alpha builds, the Emerald Dream was an accessible zone, complete with green fog and untextured terrain stretching for miles.',
	"An unused boss named 'Abyssal Maw' was intended for Cataclysm's Vashj'ir raid but was cut due to time constraints.",
	"GM Island includes a mailbox and used to contain traces of unique NPCs named 'Ari' (a gnome) and 'Tuskfyre' (a troll). These characters are not found elsewhere in the game and were part of a short story used in Blizzard's recruitment materials.",
	"Developers had internal item IDs like 'TEST SWORD' with absurd stats used for QA combat testing.",
	"During early WotLK PTR, players could enter Azjol-Nerub's full raid wing before it was cut entirely from the game.",
	'The Death Knight starting zone originally included an event where Arthas personally executed the player if they failed.',
	"During Vanilla, you could use the 'Living Action Potion' to immune yourself from crowd control and flag in neutral zones.",
	'The TBC raid Sunwell Plateau reused crypt architecture from the original Karazhan subzones, never explained in lore.',
	"Unreleased Naga hero units in Warcraft III had placeholder voicelines that would later inspire Vashj's personality.",
	"Developers used an internal command '.cheat god' to test boss mechanics without dying in the early raid builds.",
	"There's an unfinished zone called 'Thal'Dranath' in Legion that was cut and replaced by the Broken Shore.",
	'The original design of Ulduar had over 20 bosses, but several were cut due to raid size constraints.',
	'Early builds of Classic WoW had tauren with tails and a more hunched-over animation rig.',
	"The 'High Elf' race was internally tested for player use during Vanilla but never made it to launch.",
	"Kel'Thuzad in Naxx 40 had an undocumented ability where he would Mind Control the highest-healing priest.",
	"The unused 'Crypt Lord' dungeon boss in Wailing Caverns had a full loot table before being removed last minute.",
	"In TBC, players could briefly access the unfinished 'Isle of Quel'Danas' via levitate and wall-jumping.",
	'Ashbringer was once obtainable via a hidden event in an internal test, but never released publicly.',
	'The Zandalar tribe originally had their own capital in northern Stranglethorn before being moved in Cata.',
	"Darnassus had an unreachable 'cut zone' above the world tree that housed dev-only NPCs labeled 'Sentinel Test'.",
	'Unused Demon Hunter voice lines existed in the Burning Crusade data files, years before Legion was conceived.',
	'The original Molten Core trash mobs dropped rare crafting recipes, later removed for balance.',
	'At one point, Blizzard tested a Diablo-style loot drop system in Karazhan during internal builds.',
	'Players could once glitch through the Caverns of Time entrance to see a prototype of Old Hillsbrad.',
	"There's a massive, hidden pit underneath Stormwind labeled 'Test Pit' in early game geometry files.",
	"NPC pathing was calculated using a now-defunct system called the 'Waypoint Mesh Grid' which left odd traces.",
	'The Wrathgate cinematic was originally planned to be interactive before being turned into a passive scene.',
	"A version of Onyxia's Lair existed in pre-release Kalimdor as a standalone cave without dragon textures.",
	"The Spell 'Rain of Chaos' from WC3 was once a test ability in early Warlock builds with Infernal spawns.",
	"Developers used an internal boss-testing zone with all raid models called 'RaidTestingGround_01'.",
	'The original Icecrown raid layout included a massive outdoor area removed due to memory constraints.',
	"During MoP alpha, the 'Timeless Isle' was codenamed 'TestIsland_RespawnCrazy' internally.",
	'Naxxramas was moved from Eastern Plaguelands to Northrend because the dev team felt it was underused.',
	"Early Pandaria maps contained an island named 'Dragon Isle' far to the south - likely a Dragonflight predecessor.",
	"In early alpha, Night Elves had a different mount: a glowing purple deer named 'Elarion'.",
	'Boss scripts were originally handled by LUA files in the server engine before being migrated to C++ events.',
	"The Northrend zone 'Crystalsong Forest' was meant to be a daily quest hub, but was abandoned due to lag.",
	"Cho'gall was originally planned as a boss in Black Temple, not Bastion of Twilight.",
	"The old 'Eye of Azshara' map name was used internally years before it appeared in Legion.",
	"Tirisfal Glades once had a placeholder raid portal titled 'Crypt Raid Entrance' during Vanilla.",
	'In Classic Beta, Dire Maul was temporarily accessible via teleport NPCs in Ironforge.',
	'The Mount Hyjal raid area existed since Classic but was fully instanced only in Burning Crusade.',
	"The internal testing zone 'DeveloperIsland_A' has every mount and flight path crammed onto one island.",
	'In Cataclysm alpha, Gilneas City had fully walkable interiors later removed due to performance issues.',
	"Blizzard devs used in-game characters like 'Pat Nagle' to sneak test features live on servers.",
	"The 'Nerubian Underground' from WotLK had concept art and terrain files, but was never finished.",
	'A bug in Classic allowed players to kite Kazzak into Stormwind, causing hours-long server wipes.',
	"A secret cave in southern Tanaris was labeled 'Test_Hydra_Hall' in early map files.",
	"The original 'Shadowmourne' questline required PvP kills in Icecrown - removed due to griefing.",
	'Early concepts for the Undead starting zone involved being buried and digging your way out.',
	"The unfinished zone 'Dragon Isles' appeared as a minimap overlay in Classic builds.",
	"Dreadlords had a cut racial called 'Shadow Control' that let them possess weak humanoids.",
	'The Cloak of Shadows spell was copied from an internal rogue-only PvP trinket.',
	'In alpha, Sargeras had a placeholder model: a reskinned fire elemental 5x larger than a raid boss.',
	"Developers once tested an underwater raid in Vashj'ir called 'Nerub'ar Palace'.",
	'The Dark Portal originally used a swirling cloud skybox, not the Outland backdrop.',
	"Stormwind Keep once housed a raid portal called 'Chamber of the Guardian'.",
	'A cut questline had players assassinate a corrupted version of Bolvar Fordragon in an alternate future.',
	"Devs considered a pre-Cataclysm event called 'The Shattering Hour' involving time-travel raids.",
	"A rogue-only poison called 'Nerubian Venom' appeared briefly in Wrath pre-patch builds.",
	'The Hyjal Summit raid was originally 10-man and had dynamic enemy paths depending on faction.',
	"There is an unused racial called 'Berserking Troll Frenzy' that increased size and doubled damage.",
	'Blizzard tested flying underwater mounts in 2007, including one modeled after a stingray.',
	'Worgen were originally a Horde race in design documents before lore shifted their origin.',
	"A beta quest in Storm Peaks involved recovering Yogg-Saron's severed tendrils - removed due to ESRB.",
	'The Scholomance headmaster once had an ability that deleted a random item from your inventory.',
	'In early BC, Fel Reavers would target stealthed players by noise radius, not sight.',
	"In internal testing, 'Frostmourne' was a weapon players could loot in ICC test builds.",
	"Naxxramas had an alternate version called 'Naxx_Revenant' with different color schemes.",
	'The Caverns of Time hub was initially placed in Tanaris Sky Temple before being moved underground.',
	'At one point, dual-wielding legendaries would trigger server warnings due to proc stacking.',
	'Ghostlands once had a phased version where Arthas would appear briefly and vanish.',
	'The original Honor Hold was a Horde zone - repurposed before launch.',
	'The Auction House system was first prototyped using chat channels before becoming an NPC interaction.',
	'In the early UI, druids had separate spellbooks for each shapeshift form.',
	"The Goblin racial 'Rocket Jump' caused instant death when used indoors during early beta.",
	"Elwynn Forest had a cut subzone called 'Forestwatch' that connected to Blackrock Mountain.",
	"Beta testers could use the command '/beta mount' to spawn any mount during feedback.",
	"Ghostcrawler had an in-game character named 'Crabby' who offered developer Q&A during Cataclysm PTR.",
	"There's a hidden, inaccessible Scarlet Crusade basement under Tirisfal Monastery with unused props.",
	'A bug once let hunters tame a GM-only spectral wolf with debug tags still attached.',
	'Developers once considered a talent tree rework where every spec had access to a fourth tree.',
	'The ICC gunship battle originally allowed players to pilot the ship manually like a vehicle.',
	"There was a fifth elemental plane called 'The Skywall Nexus' - later split into Throne of the Four Winds.",
	"A forgotten NPC called 'Stan the Test Cow' existed in the Barrens for aggro testing.",
	"Deathwing's back originally used a destructible spine mechanic players had to damage in real-time.",
	"The cut 'Azshara Crater' battleground used terrain from Warcraft III's multiplayer map editor.",
	"The WoW alpha had a UI bar labeled 'Hunger', removed before beta.",
	'In internal stress tests, developers spawned 500 Illidans in Orgrimmar just to crash it.',
	'Karazhan originally had five raid wings, including one based in the upside-down version of itself.',
	"In WotLK alpha, shamans had a spell called 'Earthsplitter' that opened fissures in terrain.",
	'Icecrown Glacier was going to be a separate leveling zone, but was absorbed into the final Icecrown.',
	'Titan architecture in Uldum was originally blue-silver instead of bronze due to texture testing.',
	'Devs almost made Archaeology a full profession with raid loot, scrapped late in development.',
	"In internal builds, test realms were called 'Blackhole Servers' and had different gravity values.",
	"A model called 'dragon_aspect_corrupted' exists unused since Vanilla, predating Cataclysm.",
	'Early quest designers used spreadsheets to script entire chains before XML systems were built.',
	"The spell 'Touch of Death' was originally a priest finisher before being given to monks.",
	'In the Wrath alpha, DKs had a summon spell that brought back any player who had died nearby.',
	"The unfinished zone 'Farahlon' in Draenor was originally meant to house max-level garrison content and a raid, but was scrapped and replaced with Tanaan Jungle.",
	"In a 2005 dev client, the unused racial 'Arcane Resistance Aura' was listed for High Elves - it was removed when they were cut from the Alliance race pool.",
	"The zone 'Kul Tiras' existed as a blank continent space in Vanilla's ocean map, containing a small hut and a testing ground for water mechanics.",
	"Developers originally tested 'Titan's Grip' by allowing warriors to dual-wield two Sulfuras maces, causing massive imbalance in internal PvP tests.",
	'The Wrath-era Orgrimmar map included an inaccessible tunnel system under the Drag that connected to a developer-only scripting cave.',
	"A prototype version of Northrend included a volcano zone called 'Frostfire Chasm', replaced by Borean Tundra in final maps.",
	"The Shadowlands beta featured an unreleased dungeon named 'Nerubian Lair' with assets later used in Zereth Mortis.",
	'In the TBC alpha client, Shattrath had destructible bridges and walls for planned PvP sieges.',
	"Blizzard's internal GM client had a mode called 'World Fly Mode' which allowed noclip through terrain with collision toggles.",
	"A hidden command '/script ExecRaidPhase()' was used in dev testing to simulate scripted raid transitions like Kael'thas' phases.",
	'In the original alpha, druids could permanently transform into bosses using debug shapeshift forms.',
	'The Emerald Nightmare raid was originally a single-zone world boss event in a pre-Legion expansion prototype.',
	"The 'infinite bag' item used by Blizzard GMs was called 'Bag of Holding' and ignored slot restrictions.",
	'Stratholme once featured a day/night cycle with different mobs spawning depending on server time.',
	"A voice file named 'Illidan_AlternatePhase2' exists, referencing a scrapped version of the Black Temple fight.",
	"The Oribos arena had a cut effect where the Arbiter's eye would spectate players mid-combat.",
	"Developers had an internal 'sandbox realm' where flying was enabled everywhere, including dungeons.",
	'Blackrock Depths was once intended to scale to level 70, as a test of dynamic dungeon tuning.',
	'In early PTR builds, the Ashran zone had environmental hazards like lava traps and collapsible bridges.',
	"A file named 'Event_LichKingAwakens.avi' was used internally as the ICC cinematic before the in-game version.",
	"The spell 'Mass Resurrection' was initially an engineer-only gadget with a 2-hour cooldown.",
	"There's an invisible vendor in Stormwind Keep named 'Merchant_Test' only visible to GM accounts.",
	'The rogue legendary questline in Legion originally required PvP kills inside enemy capital cities.',
	"On the WoW Classic demo at BlizzCon 2018, the 'Hearthstone to GM Island' toy was accidentally enabled.",
	'Thunder Bluff once had a working zeppelin route to the Wetlands, which was cut due to pathing issues.',
	'The Darnassian sabers used to have a glide animation when falling from cliffs.',
	"In testing, raid bosses like Kil'jaeden used the model of Archimonde as a placeholder.",
	"The datamined NPC 'Jenkins_DragonTest' has a 100% crit chance and fire breath tagged for damage testing.",
	"A developer-only guild called '<Internal Affairs>' was used on alpha realms for loot distribution testing.",
	"The raid journal code was originally written as an addon called 'BossBible' before being absorbed into core UI.",
	"The lost zone 'Tel'Abim' was concepted as a tropical expansion with bananas as a trade good.",
	'Early Hellfire Peninsula had player-accessible flying dragons before flying was fully implemented.',
	'A bug in 2006 allowed players to mind control raid bosses and use their spells for a brief moment.',
	'Stormwind originally had a working sewer system you could enter - later blocked off with gates.',
	"Developers placed a hidden NPC under Karazhan called 'Watcher_Bone' with a full event script and no spawns.",
	'A test goblin rocket mount exploded upon dismount and was removed for causing player grief.',
	"The dungeon 'Court of Stars' once had a phase where the entire upper balcony collapsed mid-fight.",
	"Mages were once tested with a spell called 'Arcane Overload' that caused random explosions on every cast.",
	'A mechanic in early Grim Batol made the entire dungeon flood with lava on a timer.',
	'The legendary cloak from Pandaria was originally a necklace but was changed due to animation issues.',
	"Developers planned a 'Caverns of Time' raid where players stopped the First War from being reversed.",
	"There was once a secret arena bracket called 'DevHell_6v6' where Blizzard staff tested class balance.",
	'In Cataclysm alpha, the Elemental Plane of Air had a dungeon boss that spoke in reversed Common.',
	"A mob named 'Training_Dummy_Boss' had more health than Deathwing for raid DPS testing.",
	"The internal event handler 'EVT_BOSS_WIPE_TEAM' was used to simulate group wipes on dev realms.",
	'The original Arathi Basin had an additional node near the lumber mill, cut due to symmetry problems.',
	"There's a deprecated item called 'Amulet of Unmaking' that crashes the game if equipped.",
	"The Firelands raid had an unused zone called 'Sulfuron Maze' that was a jumping puzzle.",
	'During Wrath development, Northrend was divided into three separate continents for loading reasons.',
	'Several Pandaren animations were initially shared with male dwarves during early motion testing.',
	'The original version of Azshara had a floating palace suspended by arcane pylons before being removed.',
	'Blizzard tested destructible buildings in Alterac Valley during Vanilla, but scrapped the feature due to lag.',
	"A Pandaria boss named 'Yu'lon's Wrath' was cut from the Temple of the Jade Serpent for being too difficult on normal.",
	"The dev zone 'Ahn'kahet_Debug' had test levers that simulated old god whispers for audio balancing.",
	'The original Beta for Burning Crusade had no Outland minimap, leading players to navigate by sun position.',
	"Blizzard's item team used spreadsheet macros to simulate trinket proc effectiveness during the Wrath cycle.",
	"Test NPC 'Frank the Butcher' in the Shadowmoon Valley alpha had every legendary equipped for damage modeling.",
	"There's a debug string in old builds that reads 'ERROR: You pulled C'Thun too early. Prepare to die.', unused in live.",
	"Internal patch notes listed Kael'thas as 'Kaelthas_V2_ShitFix' after bugs in his Tempest Keep encounter.",
	"Blizzard used a tool called 'PathSniffer' to debug NPC walk routes in zones like Zangarmarsh and Storm Peaks.",
	"The abandoned Arathi Basin revamp map 'Silvershard Stream' was shelved in favor of Silvershard Mines in MoP.",
	"An early boss in Blackrock Foundry called 'Iron Warden X57' was cut due to mechanical overlap with Flamebender Ka'graz.",
	'The Darnassus bank originally doubled as a portal room during internal alpha testing for alliance travel nodes.',
	"A Night Elf-exclusive racial called 'Wisp Form: Blink' was tested for ghost travel but removed due to battleground exploits.",
	"One of the first global debugs in WoW's alpha was caused by a sheeped enemy falling through the terrain into the void.",
	'Blizzard tested dynamic wind physics in Howling Fjord for the cliffs, scrapped for performance reasons.',
	"The quest scripting team had an internal command to 'hot-reload' .qst files live in dungeons - often causing crashes.",
	"An early Icecrown instance named 'Vault of Bone' was scrapped for thematic similarity with Pit of Saron.",
	"Sapphiron was originally designed to cast 'Deep Freeze' - removed to avoid PvP confusion with mage talents.",
	"During Cata testing, players were once teleported to a dev-only void zone labeled 'Bug_Room_WorgenForm' after phasing errors.",
	"An unused paladin glyph called 'Glyph of Judged Silence' suppressed enemy emote sounds during judgment hits.",
	"In the Legion alpha, players could temporarily ride Ysera during Val'sharah's finale before the scene was reworked.",
	"The PTR once allowed entry to a test raid zone named 'Raid_OldGod_Storm' using .go commands.",
	"The first model of Thrall in Cataclysm had no eyebrows and used a placeholder 'orc_superhero' skeleton.",
	'Developers once misconfigured the NPC faction of Varimathras, causing him to be friendly to the Alliance in an early build.',
	"Tol Barad's internal name is 'PVP_IsleV2', a legacy from when it reused Wintergrasp assets.",
	"In early BFA test builds, N'zoth spoke actual reversed audio from C'Thun's old whispers before being replaced.",
	"The 'Runes of Command' system for DKs was tested in Legion but abandoned due to UI complexity.",
	"GM test zones used dev-created mounts like 'Flying Anvil' and 'Burning Sheep' for collision testing.",
	"A failed ICC encounter called 'Deathwhisper 2' involved killing ghost reflections of each raid member.",
	'One version of the Caverns of Time included a working timeline randomizer that phased players to alternate histories.',
	'The Twin Emperors in AQ40 originally used a mechanic that swapped their HP pools constantly - too complex at the time.',
	"A daily quest hub for Cataclysm's Twilight Highlands named 'Gor'shak's Stand' was cut and remains in the terrain.",
	'During Warlords alpha, engineers could build a garrison-only blimp mount that acted as a mailbox.',
	"Blizzard devs created a 10-minute debug raid called 'StressTest_UlduarMobs' where all mobs shared a single HP bar.",
	"Zandalar once had a hidden cave titled 'AztecTemple_DebugRoom' with unfinished snake totems.",
	"The Legion prepatch included a deactivated mechanic called 'Fel Rift Instability' which randomized spawn timers.",
	'A warrior artifact skin was originally locked behind a quest involving dueling 100 players at once - removed after feedback.',
	"A rare mob named 'The Blinking Horror' was intended for Uldum but removed before any sightings occurred.",
	"In the earliest server tools, devs toggled global weather effects using '/run WeatherStormAllOn()'.",
	"The Tirisfal map file contains a zone named 'Lordaeron_Fall_Event', unused but tagged for event phasing.",
	"The internal dev map of the Broken Isles had a giant floating text label saying 'PROTOTYPE ONLY – NOT ZONE FINAL'.",
	"A spell called 'Mass Knock' existed briefly in WotLK beta, sending all nearby units flying with no fall damage.",
	"A lost mechanic in Black Temple's Supremus fight included collapsing ground zones similar to Deathwing's spine.",
	'The Goblin starting zone originally included a kart racing minigame scrapped due to server desync issues.',
	"During early MoP testing, the entire Vale of Eternal Blossoms had no textures and was dubbed 'Goldless Crater'.",
	'A Wailing Caverns prototype once allowed for underwater combat against giant eel bosses.',
	"An early version of the spell 'Chain Heal' bounced to enemies if no allies were in range.",
	"Dev-only NPC 'Scripty Jim' could be summoned to force quest state changes on testers mid-instance.",
	"Early versions of the WoW client referred to the logout button as 'ExitExistence()' in the codebase.",
	"The 'Spell_BloodExplosion' effect was used during internal alpha testing to simulate arterial spray.",
	'In early WoW builds, players could wield fishing poles in both hands as dual-wielded weapons.',
	'The early Wailing Caverns had an unfinished underground lake room intended for an unknown sea boss.',
	'Blizzard once tested a battleground where Horde and Alliance both defended NPC kings from waves of AI attackers.',
	'During Cata development, Deepholm had a scrapped event where Therazane fought Ragnaros in a duel of elementals.',
	"A goblin engineer prototype once allowed players to craft 'Exploding Parachutes' that failed 50% of the time.",
	'A test-only version of Ashenvale was used to benchmark DirectX 8 vs DirectX 9 lighting systems.',
	'Blizzard once experimented with per-player raid mechanics that were invisible to others during the Mists beta.',
	"A mysterious build artifact called 'VOID_FireLord' used the Ragnaros skeleton but had unique attack animations.",
	"In Pandaria internal builds, the Celestials were designed as weekly 'teacher' bosses instead of raid content.",
	'The first model of the Lich King had no legs and hovered using a flat circular base, like old RTS ghosts.',
	"Unused NPCs in Scholomance alpha were named after famous horror writers like 'Professor Barker' and 'Lecter'.",
	"Dev map 'DwarfZone_D' was a vertical-only combat test for fall damage scaling before Alterac Valley was finalized.",
	'The login screen for Wrath had a hidden trigger zone that forced a crash on Macs with unsupported GPU drivers.',
	"A debug spell called 'You Done Goofed' auto-killed any player who taunted Illidan too early in test builds.",
	'Blizzard tested a mind-control tower mechanic in early Silvermoon that let you force vendor NPCs to follow you.',
	'During stress tests, the devs spawned 100 Doomguards in Goldshire with passive AI just to monitor pathing.',
	"The Drakkari zone had a building titled 'Zul'drak_ChillChapel' that was removed due to ESRB concerns.",
	"Old Scholomance code references a 'necromancer experiment' involving polymorphing the player into a book.",
	'The TBC zone of Netherstorm originally included time-travel rifts that showed players versions of future Outland.',
	"There's a scrapped encounter for Karazhan's library that had a cursed book fly around burning the raid.",
	'A Zandalari war priest model was rigged to transform into a dinosaur mid-fight - later used in BFA.',
	"A spell named 'Mass Hex' turned an entire raid into critters but caused fatal fall glitches and was removed.",
	"Blizzard once planned a Warlock tanking specialization called 'Abyss Knight' before Demonology was finalized.",
	"The internal name of Thrall's Cata model is 'GreenJesus_HD', a leftover joke by the art team.",
	"Test zone 'Kalimdor_SkyDark' was created to simulate total solar eclipses and server clock syncing.",
	"The 'Plague Cauldron' model used in Eastern Plaguelands was rigged to explode but never implemented.",
	"An early version of the Brawler's Guild had a round where you fought two GMs disguised as ogres.",
	"One developer once renamed all raptor mounts in a test patch to 'Clever Girl' as a Jurassic Park tribute.",
	"The concept of Artifact Knowledge in Legion was inspired by a canceled feature called 'Tome of Mastery' in Cata.",
	"A placeholder sound file labeled 'Voljin_DeathYell_TEMP' was accidentally used live for 2 days on PTR.",
	'Worgen player models originally used Forsaken skeletons and had a lurching run cycle.',
	'Blizzard considered implementing elemental weaknesses in Wrath but dropped it for PvP balance.',
	"The 'Tidecaller' elite naga in Azshara had a chance to drop a necklace that whispered C'Thun quotes - cut pre-release.",
	'Alpha-level Stormwind had griffon roosts atop the Cathedral for city-wide fast travel.',
	"Early Temple of Ahn'Qiraj had a cursed amulet that randomly disconnected players who wore it.",
	"The Ghostlands intro was once narrated by a datamined voice labeled 'BansheeQueen_Overseer.voc'.",
	'The Coliseum event in Icecrown was first conceived as a rotating PvP + PvE hybrid with faction-changing gear.',
	"A Wrath quest named 'Bury the Hatchet' auto-disbanded your guild as a bug when completed.",
	"The Gilneas city map contains an area labeled 'PhantomCourt_Debug' that's entirely empty geometry.",
	'PTR builds during Legion accidentally spawned world bosses with Mythic+ affixes like Explosive.',
	"Vashj'ir originally included a giant Kraken that acted as an underwater taxi service - removed for motion sickness.",
	'A bug during early alpha allowed Druids to skin corpses while shapeshifted into flight form.',
	"Players once found a debug floating hammer in The Barrens labeled 'Testing Artifact of Yeet'.",
	"The Pit of Saron had a scrapped NPC named 'Stalactite Steve' who dropped rocks on players at random.",
	"The first version of Garr's fight in Molten Core summoned lava worms that consumed raid loot if not killed fast.",
	"An abandoned MoP island zone named 'Stormvein Hold' is referenced in leaked internal terrain maps.",
	"The internal feedback tracker once flagged a hunter bug titled 'Pet vanished into non-Euclidean geometry'.",
	"Classic beta builds had an emote command '/scare' that played a banshee scream animation for undead.",
	"Blizzard's internal map viewer app was codenamed 'WaffleCone' and could load flying path mesh overlays.",
	"During early WoW stress tests, 'Lagbeasts' were spawned to simulate server overload behavior using AI pathing.",
	"The unused profession 'Runecrafting' appears in old internal tools as a scrapped inscription-based crafting system.",
	"In the Ghostlands alpha, Forsaken NPCs had placeholder names like 'Uncle Rotty' and 'Dead Aunt May'.",
	"A debug mount called 'GM_Horse_Rocket' could reach untextured zones instantly with infinite air jumps.",
	"Karazhan had an unfinished boss named 'Mirror Master' who created evil versions of the entire raid.",
	"During alpha, water elementals used a model named 'BlueSlushie' in test zones.",
	"Patch 2.1 internal notes once listed a fix as 'Removed Deathwing's accidental chat bubble in Black Temple'.",
	"Test zone 'EMERALD_DREAM_NORTH' had terrain that constantly shifted shape under player feet.",
	"Wrath's alpha had a placeholder title 'Lord of the Lich', which appeared in early installer UIs.",
	'The early design of Tol Barad included a naval siege mechanic that allowed players to bombard the keep.',
	'The Cataclysm beta had a scrapped world event where every capital city suffered elemental invasions simultaneously.',
	"Kalimdor had a mystery subzone labeled 'Gnoll_Warren_ShardEvent', used only in AI testing builds.",
	'Blackrock Depths originally allowed you to challenge Emperor Thaurissan by equipping a specific crown.',
	'The first version of Warsong Gulch was designed for 40 players per side and had mount-based flag runs.',
	"The Silvermoon area 'Dead Scar' used to spawn ghostly soldiers in phased battles no longer active.",
	"Shadowmoon Valley had a scrapped event where Illidan's voice could be heard giving orders in the skybox.",
	"Unused dev strings reference a Demonology Warlock cooldown called 'Hellfire Metamorph', never implemented.",
	"An engineering item called 'Gnome Soul Extractor' existed briefly in Alpha but was removed for being too dark.",
	"A cut Zul'Farrak event let trolls ride giant hyenas into the pyramid before being axed for pathing bugs.",
	"An alternate raid zone 'Throne of Magtheridon' was listed in the original BC map IDs but never existed in-game.",
	"During Cataclysm's reveal, dev builds used placeholder NPCs named 'Quest_Giver_ThrallClone_01'.",
	"A hidden tunnel beneath Ironforge leads to a dev-only skybox portal called 'Dwarven Heaven'.",
	'A bug in TBC beta caused Netherdrake mounts to explode when dismounted mid-air at max altitude.',
	"Dev-only mobs called 'Hunger Elementals' exist in the files with a passive aura named 'Gnawing Void'.",
	"'Chrono Lord Deja Vu' was a prototype Infinite Dragonflight boss for an unused Caverns of Time instance.",
	'The Nexus in Northrend originally had an extra floor where Malygos was worshipped by blue dragon cultists.',
	'Developers considered letting goblins build mini-turrets in battlegrounds during Cata alpha.',
	"A Pandaren city called 'Bamboo Hold' was scrapped in early MoP terrain builds before the Wandering Isle concept.",
	"The dev spell 'Force_Cleanse_Everything' once accidentally removed tier bonuses from equipped sets.",
	"A Death Knight ability called 'Unholy Fury' turned your ghoul into a siege weapon in Wrath alpha.",
	"The Wrath cinematic had an unreleased version with a different music track titled 'Rise of the Cold'.",
	"Black Temple's original map layout was 40% larger and included a raid section called 'Shadow Gaol'.",
	"During BFA alpha, players could briefly see a debug creature called 'Talanji's Ghost Horse' in Nazmir.",
	"In old test builds, devs inserted personalized boss death yells like 'For Jeff, the intern!'",
	"The 'Netherworld Backpack' model was designed to carry souls for a scrapped Shadowlands mechanic in WoD.",
	'Unused early Night Elf male voice lines included grunts modeled after basketball players.',
	"The map 'Outland_West_Sea_Collision' was a testing zone for player-ship physics in pre-TBC prototypes.",
	'Frostmourne Cavern was once accessible by blinking through the instance wall in early ICC PTRs.',
	'A MoP cinematic test had Chen Stormstout trip over his own keg and start a tavern brawl instead of a duel.',
	"Dev raid encounter logs sometimes contain headers like 'TRY_NOT_TO_CRASH_THIS_TIME, team'.",
	'A Pandaria-era bug caused Brewmaster monks to generate threat through dance emotes.',
	"Unused mounts include a 'Cursed Hippogryph' with fire FX that blinded testers in dark zones.",
	"The WoW Dev Map Editor was codenamed 'SnackMachine' internally during the Classic era.",
	"Test item 'Relic of Rude Awakening' gave players a 10% chance to shout at themselves on logout.",
	"Stormwind's moat once had test mobs labeled 'Angry Fish', used for early AI terrain detection.",
	'A Karazhan mirror used in testing allowed players to fight themselves using class templates.',
	'The ICC spire had a top floor intended to host a second Lich King phase involving dragons - scrapped.',
	"WoW's earliest closed alpha used placeholder portals named 'Level_99_Boss_Test_X'.",
	'The Maw of Madness was once part of the original Shadowmoon Valley before being isolated to Legion.',
	'Blizzard considered giving Demon Hunters the ability to see old god whispers while idle, but removed it for creep factor.',
	'The Corrupted Blood incident was once studied by real epidemiologists due to its similarity to uncontrolled outbreaks.',
	"A dev-only racial called 'Goblin Paranoia' once triggered a fear effect if surrounded by more than five enemies.",
	"The model 'horse_armored_elite_test' was used for testing mounted combat, later scrapped.",
	"The 'Netherstorm Ruins' subzone originally had puzzle-based daily quests involving rune circles.",
	"Blizzard devs tested a quest called 'Brew of Destiny' that aged your character visually upon drinking.",
	'In early PTR builds, Garrosh Hellscream had placeholder voice lines from Ragnaros.',
	"The cut raid 'Azjol-Nerub: Inner Kingdoms' included assets of spider-riding cultists.",
	"A test event titled 'The Sky Breaks' randomly rained fire in Nagrand in alpha zones.",
	'Tirisfal once had a scrapped Scarlet Crusade siege scenario using catapults and NPC squads.',
	"One early raid test boss was named 'Lord Placeholder' and dropped every tier piece for all classes.",
	"There's a hidden underwater forge in Loch Modan used for dwarf-only blacksmithing tests.",
	'A Cataclysm-era bug made Hogger scale infinitely with player health, creating immortal Hogger runs.',
	"In internal events, Blizzard devs roleplayed as 'Dreadlords of HR' in mock invasions.",
	"Shattrath once had a 'light side / dark side' faction system similar to SWTOR in early notes.",
	'Dalaran sewers originally allowed duels that triggered guard attacks regardless of winner.',
	"The toy 'Orb of the Sin'dorei' was a leftover dev tool to test racial perspective on emotes.",
	"The dev-only title 'of the Sandwich Lords' was briefly active on GM accounts during Wrath.",
	"Northrend's map files list a zone called 'Tuskarr Ice Fort' that never made it to beta.",
	'During alpha, players could fall under Deepholm and land in a debug nether dimension.',
	"The death knight ability 'Anti-Magic Shell' once blocked ALL damage in its first implementation.",
	"An unused 'Siege Shaman' enemy type had a totem-launching artillery system.",
	'Old Grim Batol concepts involved a prison break event for red dragons pre-Cataclysm.',
	"The name 'Felwood' came from an early dev note that read 'make this wood look... fel'.",
	"Beta map files contained a mini continent labeled 'South Seas', only reachable via debug flypaths.",
	"Wrath's launch event included a scrapped cinematic where Arthas freezes Teldrassil mid-speech.",
	"Searing Gorge once had a hidden quest that granted a passive ability called 'Lung of Flame'.",
	'Shadow Priests briefly had a passive in beta that let them hear whispers when idle near undead.',
	'Stratholme had a phased version where you could cleanse the city, scrapped before Classic release.',
	"Gnomes originally had a racial 'Explosive Curiosity' that caused them to self-destruct on death.",
	"An early PvP zone called 'The Black Morass Battleground' was removed due to instability.",
	'A cut trinket from Scholomance was supposed to summon ghost students who mocked you.',
	'The Wrath Gate cinematic originally had an alternate ending where Sylvanas duels Putress.',
	"The Druid spell 'Symbiosis' once let you steal passive racial bonuses from other races.",
	'A gnome-only crafting bench in Ironforge once required real-time emote input to function.',
	"Early NPC AI used a function called 'RunAwayIfScared', leading to many unintentionally fleeing guards.",
	"The 'Old Town' in Stormwind once had a rogue-only social zone called 'The Blinds'.",
	'Malygos was originally voiced by the same actor as Thrall in test builds due to actor shortages.',
	"In alpha, Night Elves started in a zone called 'Ashenvale_Ghost_Forest_DevOnly'.",
	"Patch 1.10 included a hidden Easter egg where typing '/moo' near Thunder Bluff summoned a cow spirit.",
	'Early shaman totems used to interact with terrain physics, resulting in floating totems on hills.',
	'A Hunter bug in BC made it possible to tame your own pet if it was resurrected mid-cast.',
	'The Cataclysm login screen was originally a flooded Ironforge, changed due to readability.',
	"The Wailing Caverns boss 'Mutanus the Devourer' had a dev-only intro line: 'My meat is LEGENDARY!'",
	"The rare 'Darkmoon Rabbit' was first spawned as a joke mob during BlizzCon server tests.",
	"A secret GM teleport command called '.hole' took you to a void cube under Orgrimmar.",
	'Fel Reavers were originally designed to whisper your name when nearby, but it creeped testers out.',
	"There was a test scenario called 'Molten Gameshow' where bosses asked trivia mid-fight.",
	'An abandoned Karazhan wing included a playable chess match where your character controlled pawns.',
	"A weapon called 'Stick of Infinite Poking' existed in alpha and pinged enemies endlessly.",
	"The toy 'Piccolo of the Flaming Fire' was added to troll raid leaders by forcing dance loops.",
	"There was an unused spell called 'Arcane Time Bomb' that created a 30-second countdown to massive AoE damage.",
	'Blizzard once tested destructible terrain in Warsong Gulch, but scrapped it due to balance issues.',
	'A version of the Burning Legion invasion had meteor strikes that would leave permanent terrain scars in zones.',
	"The goblin starting zone originally featured a mob called 'Explosion Enthusiast' that chain-reacted on death.",
	'In early Alpha, there was a working swimming animation for mounts that was removed for performance reasons.',
	"Test dungeons labeled 'DM_Tutorial_Basement' included dev notes like 'Make the rats angrier'.",
	'A scrapped mechanic in the Illidan fight had players go blind if they looked directly at his glaives.',
	"The Argent Tournament was originally a PvP battleground called 'Silvermoon Jousting Grounds'.",
	'Devs experimented with a mechanic where guild leaders could post bounties on enemy players.',
	"The 'Spirit Healer' once had dialogue choices for resurrection taxes in early beta.",
	"The underwater zone 'Abyssal Maw' had a cut boss named 'Thal'kiel the Deep Thinker' with psychic-based mechanics.",
	"The gnome racial 'Escape Artist' originally worked on all crowd control effects, including stuns.",
	"There was a time in Classic when 'Slow Fall' spells could be chained mid-air for infinite flight.",
	"A hidden Frostfire Ridge cave called 'Test Cave SFX' had 14 layers of echo in voice triggers.",
	"The original Wailing Caverns had a boss named 'Lurker Below' years before it appeared in Serpentshrine Cavern.",
	"A cut WotLK raid 'Icecrown Crypts' had necromancer NPCs named after Blizzard QA staff.",
	'Goblin zeppelins in early alpha could be hijacked and crashed into cities during stress tests.',
	"There was a dev-only trinket called 'Ultimate Reset Button' that cleared all cooldowns and filled mana.",
	"A test model labeled 'dragon_hug_variant1' was used to prototype dragon riding animations.",
	"During TBC, players could climb the Blade's Edge Mountains spires before flying was enabled, breaking geometry.",
	'An early version of AV had mounted wolf cavalry spawns that auto-engaged mid-map.',
	"The 'Warden AI' for anti-cheat once accidentally flagged all mages for blinking through doors.",
	"Blizzard tested a boss mechanic where the boss would read your character's real name from the WoW license.",
	"The unused 'Black Temple Crypts' instance had over 200 unused NPCs labeled 'noone_suspects'.",
	'A fishing pole in beta once granted +1000 strength as a tooltip typo, making it BIS for warriors.',
	"There was a zone in Vanilla alpha named 'Emerald Wastes' that featured time-shifted dragons.",
	"A dungeon prototype titled 'Zul'Farrak Remastered' appeared in internal patch notes but never released.",
	'Hunter pets once gained stats from player gear in early alpha, making tanking raptors viable.',
	"The Silithus scar was originally animated to slowly expand each week leading into Ahn'Qiraj.",
	'A daily quest in MoP beta allowed you to ride Sha-corrupted beasts with different control schemes.',
	"Naxx 2.0 was internally codenamed 'Project Frostbloom' during Wrath development.",
	"There was an engineering item called 'Thermal Detonator' that caused players to explode on logout.",
	"The Troll raid 'Zul'Gurub' originally included a spectral boat boss who sank the instance mid-fight.",
	"Blizzard considered letting players build towers in Silithus to fight against 'world creep'.",
	"The internal quest tool was nicknamed 'ScribblePad' and exported scripts as .lua and .txt dual files.",
	'During internal April Fools testing, all mobs were replaced with Murky wearing elite armor.',
	"There's a retired item called 'Boots of Test' that had zero armor but +5000 swim speed.",
	"A model of 'Old Thrall' with beard physics was tested for a storyline that never aired.",
	"The unfinished 'Halls of Reflection' once had a cinematic where Sylvanas gets possessed by Frostmourne.",
	"There's a cloaked goblin dev NPC named 'Crispy Steve' hidden in Booty Bay, disabled in live.",
	"Early builds of Zul'Drak had siege mechanics that let you ride proto-drakes through walls.",
	"A non-functional mount called 'Void Elk' was in the Legion files with placeholder animations.",
	'The Gallywix cutscene in BfA originally had him lose his mustache mid-dialogue from engine physics bugs.',
	"One of the first profession test items was 'Hammer of Cloth Gathering', which only dropped linen.",
	'In Cata alpha, Deathwing had a debug hitbox so large it triggered aggro from half the continent.',
	"A PvP reward crate named 'Loot of the Doomed' crashed clients if opened without honor rank.",
	'Early Brewfest events used barrels that exploded if clicked out of order, locking the quest.',
	'The original voice lines for the Lich King were re-recorded after the first actor laughed during screams.',
	'Shaman totems once generated heat maps on the server backend to track player proximity in PvP.',
	'The Alliance gunship in ICC once clipped into the Citadel wall, flinging tanks into the void.',
	'The Wrath beta had a bug where Death Knights spawned without any textures, appearing as glowing green blobs.',
	"Developers used a private Stormwind instance labeled 'SW_Prototype_Alleyway' to test crime-themed questlines.",
	'In pre-release Pandaria builds, mounts could be knocked off bridges by wind gusts in Kun-Lai Summit.',
	"There's a cut raid called 'Crypts of the Damned' that featured alternate versions of ICC bosses.",
	"The spell 'Meteor Punch' used by Ragnaros was initially a placeholder ability named 'Smack-o-Tron 5000'.",
	"During MoP beta, players found a dev room behind the Temple of the Jade Serpent labeled 'JokeZone'.",
	'A visual bug during early Cata made water textures reflect the sky upside down, causing vertigo.',
	"A cancelled Worgen capital was codenamed 'Wolfhome' and appeared on old zone development maps.",
	"The model 'GhostHorse_Variant03' was a test for flying undead mounts that never made it to live.",
	'Blizzard internally tested a weapon affix system that dynamically changed weapon types in combat.',
	"The mob 'Doom Lord Xorgok' was cut from Shadowmoon Valley but still exists in the game files.",
	"Players once found a mail item named 'Test Letter From Metzen' with lorem ipsum text and jokes.",
	"A quest called 'Fel Stitches' in Outland was pulled because it was too graphic for the ESRB.",
	'The NPC pathing engine was temporarily replaced in MoP beta with one from StarCraft II.',
	"Horde originally had a quest in Silverpine to poison Stormwind's water supply - it was removed.",
	'Early versions of TBC included a massive forge under Hellfire Citadel as a future dungeon hub.',
	'The Scourge invasion 2.0 during Wrath was originally more destructive and included city fires.',
	"Blackwing Descent's elevator had a test script that sometimes dropped players 300 meters instantly.",
	"The 'Spectral Pirate' model was used as a placeholder for Arthas in very early ICC builds.",
	"The game client once had a hidden command '/debug_panic' which crashed the client intentionally.",
	"Blood Elves had a racial in alpha called 'Mana Drain', which stole mana from nearby allies and enemies.",
	'There was a WoW dev prank where every ogre in Dustwallow Marsh was replaced with red murlocs for 10 minutes.',
	"An abandoned zone called 'Plaguewood Vale' was set to be used in a Naxxramas quest chain.",
	"The toy 'Piccolo of the Flaming Fire' originally caused forced /dance animations in PvP combat.",
	'In WotLK alpha, the Wintergrasp keep had rotating cannons you could man and aim freely.',
	"The command '/dancebattle' was prototyped to start a DDR-style emote contest - scrapped for time.",
	'Some devs used in-game totems with invisible names to test line-of-sight detection in real time.',
	"A Titan NPC labeled 'Amun'Rez' was hidden under Uldum during Cataclysm testing, never surfaced in lore.",
	"Before Legion's launch, one build accidentally made all squirrels level 110 and hostile.",
	'Blizzard once considered a system where players could betray their faction for questlines.',
	"The tooltip for a dev-only item read: 'If you're reading this, you're not supposed to have it.'",
	"An old Scarlet Crusade dungeon was cut from the map and stored in the 'unused_instances' directory.",
	'The original ICC ending had Bolvar transform into a dragon before becoming the Lich King.',
	"There's a phased copy of Dalaran in Wrath that exists purely to test teleport failures.",
	'Burning Crusade once had a mechanic where mounts could fatigue and slow down from overuse.',
	'The first test of zone phasing involved planting trees in Elwynn Forest and watching them disappear.',
	"The unfinished island 'Zereth Mortis Prototype' contains dev scribbles on the terrain texture.",
	"A bug once caused Deathwing's roar to apply fear to friendly NPCs globally, crashing mailboxes.",
	'During Classic beta, players could use Mind Control to make NPCs buy and sell vendor-only items.',
	'Blizzard internally prototyped a mount breeding system where traits passed between offspring.',
	"In an old alpha, Pandaren could be summoned using a spell called 'Bamboo Call'.",
	'An unfinished subzone in Icecrown Citadel was set to include a PvP zone inside the raid.',
	'Blizzard once debated removing fall damage entirely due to pathing bugs in Ironforge.',
	"A retired mechanic called 'Dungeon Fear Level' adjusted mob aggression based on group wipes.",
	"One dev-only pet was a tiny Deathwing that cast 'Deathcoil' on critters every 30 seconds.",
	"An early enhancement shaman talent was 'Chain Cleave' - removed for being broken in PvP.",
	"A scrapped dungeon called 'The Forgotten Vault' had puzzles based on real-world math formulas.",
	"There's an internal title called 'of QA Hell' used for stress test characters only.",
	"The model for the Spirit Healer has no feet - it floats using an internal bone-tag called 'soulPivot'.",
	'A version of Ragnaros once had voice lines sung entirely in distorted guitar riffs - test only.',
	"A hidden dev area under Orgrimmar in early alpha was named 'Ogr_Test_Box_01' and used for pathfinding tests.",
	'During Legion alpha, developers accidentally enabled scaling up to level 130 - bosses instantly killed players.',
	"Blizzard tested an early 'debt' system where players who died too much would lose temporary stat points.",
	"A PvP zone called 'Ashen Fields' was cut from Wrath's Icecrown, meant to be a spiritual successor to Alterac.",
	"Test raid boss 'Kronus the Test Colossus' used Onyxia's sound files sped up by 300%.",
	'In a 2004 beta build, warlocks could mount while casting Hellfire, wiping entire battlegrounds.',
	"The Cut 'Plague Island' instance used altered Scholomance textures and had no collision.",
	'Draenei originally had a racial that let them call down a Naaru to AoE heal and stun enemies.',
	'Developers used dev characters named after Greek gods to test divine spell mechanics.',
	"During testing, Garrosh Hellscream had a spell named 'Unsubscribe' that caused instant death.",
	"A rogue spell called 'Snap Tendon' in Cataclysm beta disabled jumping for 30 seconds - removed quickly.",
	"Northrend once had a zone-wide debuff called 'Soul Rot' that affected every living NPC.",
	"The Wand of Simulated Fire was based on an internal dev prank item called 'Dev_Lightshow_01'.",
	'Blizzard once enabled flight in all Classic zones for a week by accident - explored by gliders.',
	"The unused boss 'Warlord Vekgar' in Ahn'Qiraj was meant to teleport players into lava.",
	"A daily quest from MoP beta rewarded '1 Dev Token', which had a tooltip reading 'haha nope'.",
	'The Argent Tournament originally featured jousting dragons instead of horses.',
	'Blizzard experimented with player housing in Shattrath, placing portals to dev-only interiors.',
	"'Spell_Dev_SquishyBoom' was a placeholder AOE explosion effect that applied 1,000,000 fall damage.",
	"Ghostcrawler once admitted a dev-only weapon called 'Furybringer' could solo Ragnaros in 3 seconds.",
	"NPCs in the cut zone 'Shrouded Wastes' were scaled to 300% normal size for camera stress tests.",
	'During Pandaria alpha, the world boss Oondasta had 0.1 second respawns for performance analysis.',
	'Blizzard tested random weather effects that could apply debuffs like Slippery or Blinding.',
	"In Legion dev builds, Illidan had a spell named 'Dev_Hug_And_Punch' during scripting passes.",
	"Unreleased test zone 'Nexus Caverns' included giant mushrooms and jellyfish skyboxes.",
	"A tooltip typo in TBC read '30% chance to smell', causing years of player jokes.",
	'Blizzard accidentally released a PTR build where every enemy had 1 HP but 1,000,000 armor.',
	"Old dev-only food item 'Sandwich of Fortitude' boosted morale, not stats.",
	"In early TBC maps, you could find a floating Naga city named 'City_of_Tides_Test'.",
	'The original mount system in WoW Beta involved whistling and waiting for the mount to walk to you.',
	"Dev testers called the gnome starting area 'Launchpad Labs' due to all the explosive bugs.",
	'In Classic alpha, the Paladin bubble spell had no cooldown and could be cast while stunned.',
	"Several cut quests reference an NPC named 'Throk the Beta Crusher' with a broken weapon model.",
	"A rare spawn from beta named 'Skullgnaw the Absolutely Horrid' was removed for scaring kids.",
	"The Cut 'Twilight Sea' dungeon was just a purple cave with whale sounds and no mobs.",
	'Blizzard considered a zone-wide PvP mechanic where Wintergrasp could cause eruptions in Storm Peaks.',
	"A TBC-era vendor accidentally sold a dev-only item called 'Ban Hammer of GMs Past'.",
	'The test version of Algalon had 8 million HP and dropped nothing but linen cloth.',
	'In Cata beta, Hyjal trees had collision so big they would stop flying mounts in midair.',
	"A hidden buff called 'Aura of Spectatorship' was used to track devs during BlizzCon test demos.",
	"The model 'gnome_chickenbot_test' was used as a tank dummy in beta raids.",
	"The Argent Crusade's original name was 'Light's Final Order', changed for sounding too apocalyptic.",
	"A scrapped dungeon called 'Molten Nest' was meant to house fire spiders under Blackrock.",
	'Blizzard once ran a stress test where Darnassus was flooded with 5,000 neutral ogres.',
	"A placeholder splash screen in WotLK said 'Now with 60% more Lich'.",
	'An internal dev server featured Elune as a killable boss for spell testing.',
	'The legendary cloak test version used the Thunderfury icon as a joke.',
	"In MoP, players once glitched into a terrain called 'Sky Pancake', which had gravity reversal.",
	"Blizzard once tried a 'hot potato' boss mechanic that physically passed debuffs between players.",
	'The first playable version of WoW ran entirely in a StarCraft engine fork before being ported to its own client.',
}
